require:
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

Style/EmptyElse:
  EnforcedStyle: empty

RSpec/BeforeAfterAll:
  Enabled: false