version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ebpr-data-warehouse-image ./

  post_build:
    commands:
      - echo Build completed on `date`
      - docker save -o ebpr-data-warehouse-image.tar ebpr-register-api-image:latest

artifacts:
  files:
    - '**/*'


