version: 0.2

env:
  variables:
    DEPLOY_APPNAME: "epbr-data-warehouse-integration"

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Paketo image...
      - pack build ebpr-data-warehouse-image --builder paketobuildpacks/builder-jammy-full:0.3.387 --post-buildpack paketo-buildpacks/npm-install@1.1.1 --post-buildpack paketo-buildpacks/ruby --default-process rake

  post_build:
    commands:
      - echo Build completed on `date`
      - docker save -o ebpr-data-warehouse-image.tar ebpr-data-warehouse-image:latest

artifacts:
  files:
    - '**/*'
