version: 0.2

runtime-versions:
  ruby: 2.7

env:
  variables:
    DEPLOY_APPNAME: "dluhc-epb-data-warehouse-staging"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-staging-login"
    PAAS_PW: "epbr-govpaas-staging-pw"
    PAAS_SPACE: "epbr-govpaas-staging-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    EPB_UNLEASH_URI: "epbr-unleash-staging-uri"
    EPB_UNLEASH_AUTH_TOKEN: "epbr-unleash-staging-auth-token"
    EPB_AUTH_CLIENT_ID: "epbr-data-warehouse-auth-client-id-staging"
    EPB_AUTH_CLIENT_SECRET: "epbr-data-warehouse-auth-client-secret-staging"
    EPB_AUTH_SERVER: "epbr-auth-server-staging"
    EPB_API_URL: "epbr-api-url-staging"
    SENTRY_DSN: "epbr-sentry-dsn-data-warehouse"

phases:
  install:
    runtime-versions:
      ruby: 2.7
  pre_build:
    commands:
      - echo ">>>>>>>> DEPLOY TO STAGING ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf cancel-deployment ${DEPLOY_APPNAME} || true
  build:
    commands:
      - make deploy-app
      - make migrate-db-and-wait-for-success
  post_build:
    commands:
      - cf logout
