version: 0.2

runtime-versions:
  ruby: 2.7

env:
  variables:
    DEPLOY_APPNAME: "dluhc-epb-data-warehouse-staging"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-staging-login"
    PAAS_PW: "epbr-govpaas-staging-pw"
    PAAS_SPACE: "epbr-govpaas-staging-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    EPB_UNLEASH_URI: "epbr-unleash-staging-uri"
    EPB_UNLEASH_AUTH_TOKEN: "epbr-unleash-staging-auth-token"

phases:
  install:
    runtime-versions:
      ruby: 2.7
  pre_build:
    commands:
      - echo ">>>>>>>> DEPLOY TO STAGING ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf cancel-deployment ${DEPLOY_APPNAME} || true
  build:
    commands:
      - make deploy-app
      - make migrate-db-and-wait-for-success
      - cf run-task ${DEPLOY_APPNAME} --command "rake db:seed" --name seed-db
  post_build:
    commands:
      - cf logout
