version: 0.2

runtime-versions:
  ruby: 3.0
  nodejs: 14

env:
  variables:
    DEPLOY_APPNAME: "dluhc-epb-data-warehouse-production"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-production-login"
    PAAS_PW: "epbr-govpaas-production-pw"
    PAAS_SPACE: "epbr-govpaas-production-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    EPB_UNLEASH_URI: "epbr-unleash-production-uri"
    EPB_UNLEASH_AUTH_TOKEN: "epbr-unleash-production-auth-token"
    EPB_AUTH_CLIENT_ID: "epbr-data-warehouse-auth-client-id-production"
    EPB_AUTH_CLIENT_SECRET: "epbr-data-warehouse-auth-client-secret-production"
    EPB_AUTH_SERVER: "epbr-auth-server-production"
    EPB_API_URL: "epbr-api-url-production"
    SENTRY_DSN: "epbr-sentry-dsn-data-warehouse"

phases:
  install:
    runtime-versions:
      ruby: 3.0
      nodejs: 14
  pre_build:
    commands:
      - echo ">>>>>>>> DEPLOY TO PRODUCTION ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf cancel-deployment ${DEPLOY_APPNAME} || true
  build:
    commands:
      - make deploy-app
      - make migrate-db-and-wait-for-success
  post_build:
    commands:
      - cf logout
