RSpec.describe "parsing with an NI RdSAP configuration (18.0)" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from RdSAP (NI)" do
    let(:rdsap) do
      Samples.xml("RdSAP-Schema-NI-18.0")
    end

    it "parses the document in the expected format" do
      expectation = { "schema_version_original" => "LIG-18.3",
                      "sap_version" => 9.93,
                      "calculation_software_name" => "eTech SMART EPC engine",
                      "calculation_software_version" => "2.0.x",
                      "inspection_date" => "2017-11-13",
                      "report_type" => 2,
                      "completion_date" => "2017-11-13",
                      "registration_date" => "2017-11-13",
                      "status" => "entered",
                      "language_code" => 1,
                      "tenure" => 1,
                      "transaction_type" => 1,
                      "property_type" => 0,
                      "scheme_assessor_id" => "SCHE020202",
                      "uprn" => 6_668_668_968,
                      "address_line_1" => "83, Virtual Lane",
                      "post_town" => "BELFAST",
                      "postcode" => "BT1 1AA",
                      "region_code" => 10,
                      "country_code" => "NIR",
                      "walls" =>
                        [{ "description" =>
                             { "language" => "1",
                               "value" => "Solid brick, as built, no insulation (assumed)" },
                           "energy_efficiency_rating" => 1,
                           "environmental_efficiency_rating" => 1 }],
                      "roofs" =>
                       [{ "description" => { "language" => "1", "value" => "Pitched, 100 mm loft insulation" }, "energy_efficiency_rating" => 3, "environmental_efficiency_rating" => 3 },
                        { "description" =>
                            { "language" => "1",
                              "value" => "Pitched, 150 mm loft insulation" },
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "floors" =>
                       [{ "description" =>
                            { "language" => "1",
                              "value" => "Suspended, no insulation (assumed)" },
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 },
                        { "description" =>
                            { "language" => "1",
                              "value" => "Solid, no insulation (assumed)" },
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 }],
                      "window" =>
                        { "description" =>
                            { "language" => "1",
                              "value" => "Single glazed" },
                          "energy_efficiency_rating" => 1,
                          "environmental_efficiency_rating" => 1 },
                      "main-heating" => [{
                        "description" =>
                          { "language" => "1",
                            "value" => "Boiler and radiators, oil" },
                        "energy_efficiency_rating" => 2,
                        "environmental_efficiency_rating" => 3,
                      }],
                      "main_heating_controls" =>
                        [{ "description" =>
                             { "language" => "1",
                               "value" => "Programmer, no room thermostat" },
                           "energy_efficiency_rating" => 1,
                           "environmental_efficiency_rating" => 1 }],
                      "hot_water" =>
                       { "description" =>
                           { "language" => "1",
                             "value" => "From main system, no cylinder thermostat" },
                         "energy_efficiency_rating" => 1,
                         "environmental_efficiency_rating" => 1 },
                      "lighting" =>
                       { "description" =>
                           { "language" => "1",
                             "value" => "No low energy lighting" },
                         "energy_efficiency_rating" => 1,
                         "environmental_efficiency_rating" => 1 },
                      "secondary_heating" =>
                       { "description" =>
                           { "language" => "1",
                             "value" => "Room heaters, dual fuel (mineral and wood)" },
                         "energy_efficiency_rating" => 0,
                         "environmental_efficiency_rating" => 0 },
                      "has_hot_water_cylinder" => "true",
                      "has_heated_separate_conservatory" => "true",
                      "dwelling_type" => { "language" => "1", "value" => "Detached house" },
                      "total_floor_area" => 217,
                      "has_fixed_air_conditioning" => "false",
                      "multiple_glazed_proportion" => 0,
                      "energy_rating_average" => 60,
                      "energy_rating_current" => 11,
                      "energy_rating_potential" => 37,
                      "environmental_impact_current" => 11,
                      "environmental_impact_potential" => 31,
                      "energy_consumption_current" => 455,
                      "energy_consumption_potential" => 278,
                      "co2_emissions_current" => 25.0,
                      "co2_emissions_potential" => 15.0,
                      "co2_emissions_current_per_floor_area" => 118,
                      "lighting_cost_current" => { "currency" => "GBP", "value" => 202 },
                      "lighting_cost_potential" => { "currency" => "GBP", "value" => 101 },
                      "heating_cost_current" => { "currency" => "GBP", "value" => 3120 },
                      "heating_cost_potential" => { "currency" => "GBP", "value" => 1978 },
                      "hot_water_cost_current" => { "currency" => "GBP", "value" => 219 },
                      "hot_water_cost_potential" => { "currency" => "GBP", "value" => 115 },
                      "suggested_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 1,
                          "improvement_type" => "D",
                          "improvement_details" => { "improvement_number" => 10 },
                          "typical_saving" => { "currency" => "GBP", "value" => 125 },
                          "indicative_cost" => 120,
                          "energy_performance_rating" => 13,
                          "environmental_impact_rating" => 12 },
                        { "sequence" => 2,
                          "improvement_category" => 1,
                          "improvement_type" => "E",
                          "improvement_details" => { "improvement_number" => 35 },
                          "typical_saving" => { "currency" => "GBP", "value" => 83 },
                          "indicative_cost" => 155,
                          "energy_performance_rating" => 13,
                          "environmental_impact_rating" => 13 },
                        { "sequence" => 3,
                          "improvement_category" => 1,
                          "improvement_type" => "G",
                          "improvement_details" => { "improvement_number" => 12 },
                          "typical_saving" => { "currency" => "GBP", "value" => 353 },
                          "indicative_cost" => 450,
                          "energy_performance_rating" => 19,
                          "environmental_impact_rating" => 17 },
                        { "sequence" => 4,
                          "improvement_category" => 2,
                          "improvement_type" => "W1",
                          "improvement_details" => { "improvement_number" => 57 },
                          "typical_saving" => { "currency" => "GBP", "value" => 138 },
                          "indicative_cost" => "1,200",
                          "energy_performance_rating" => 21,
                          "environmental_impact_rating" => 19 },
                        { "sequence" => 5,
                          "improvement_category" => 2,
                          "improvement_type" => "I",
                          "improvement_details" => { "improvement_number" => 20 },
                          "typical_saving" => { "currency" => "GBP", "value" => 647 },
                          "indicative_cost" => "3,000",
                          "energy_performance_rating" => 37,
                          "environmental_impact_rating" => 31 },
                        { "sequence" => 6,
                          "improvement_category" => 3,
                          "improvement_type" => "N",
                          "improvement_details" => { "improvement_number" => 19 },
                          "typical_saving" => { "currency" => "GBP", "value" => 37 },
                          "indicative_cost" => "6,000",
                          "energy_performance_rating" => 38,
                          "environmental_impact_rating" => 32 },
                        { "sequence" => 7,
                          "improvement_category" => 3,
                          "improvement_type" => "O",
                          "improvement_details" => { "improvement_number" => 8 },
                          "typical_saving" => { "currency" => "GBP", "value" => 110 },
                          "indicative_cost" => "6,500",
                          "energy_performance_rating" => 41,
                          "environmental_impact_rating" => 35 },
                        { "sequence" => 8,
                          "improvement_category" => 3,
                          "improvement_type" => "Q",
                          "improvement_details" => { "improvement_number" => 7 },
                          "typical_saving" => { "currency" => "GBP", "value" => 701 },
                          "indicative_cost" => "14,000",
                          "energy_performance_rating" => 63,
                          "environmental_impact_rating" => 55 },
                        { "sequence" => 9,
                          "improvement_category" => 3,
                          "improvement_type" => "U",
                          "improvement_details" => { "improvement_number" => 34 },
                          "typical_saving" => { "currency" => "GBP", "value" => 293 },
                          "indicative_cost" => "8,000",
                          "energy_performance_rating" => 68,
                          "environmental_impact_rating" => 59 }],
                      "built_form" => 1,
                      "extensions_count" => 1,
                      "multiple_glazing_type" => "ND",
                      "glazed_area" => 1,
                      "door_count" => 2,
                      "insulated_door_count" => 0,
                      "percent_draughtproofed" => 0,
                      "habitable_room_count" => 8,
                      "heated_room_count" => 8,
                      "fixed_lighting_outlets_count" => 31,
                      "low_energy_fixed_lighting_outlets_count" => 0,
                      "low_energy_lighting" => 0,
                      "measurement_type" => 1,
                      "mechanical_ventilation" => 0,
                      "open_fireplaces_count" => 3,
                      "solar_water_heating" => "N",
                      "conservatory_type" => 3,
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "identifier" => "Main Dwelling",
                          "construction_age_band" => "A",
                          "sap_floor_dimensions" =>
                           [{ "floor" => 0,
                              "floor_construction" => 2,
                              "floor_insulation" => 1,
                              "heat_loss_perimeter" => { "quantity" => "metres", "value" => 31.4 },
                              "party_wall_length" => 0,
                              "total_floor_area" => { "quantity" => "square metres", "value" => 87.15 },
                              "room_height" => { "quantity" => "metres", "value" => 2.8 } },
                            { "floor" => 1,
                              "heat_loss_perimeter" => { "quantity" => "metres", "value" => 31.4 },
                              "party_wall_length" => 0,
                              "total_floor_area" => { "quantity" => "square metres", "value" => 85.26 },
                              "room_height" => { "quantity" => "metres", "value" => 2.8 } }],
                          "floor_heat_loss" => 7,
                          "roof_construction" => 4,
                          "roof_insulation_location" => 2,
                          "roof_insulation_thickness" => "100mm",
                          "wall_construction" => 3,
                          "wall_insulation_type" => 4,
                          "wall_thickness_measured" => "Y",
                          "wall_thickness" => 270,
                          "wall_dry_lined" => "N",
                          "wall_insulation_thickness" => "NI",
                          "party_wall_construction" => "NA" },
                        { "building_part_number" => 2,
                          "identifier" => "Extension 1",
                          "construction_age_band" => "A",
                          "sap_floor_dimensions" =>
                           [{ "floor" => 0,
                              "floor_construction" => 1,
                              "floor_insulation" => 1,
                              "heat_loss_perimeter" => { "quantity" => "metres", "value" => 20.4 },
                              "party_wall_length" => 0,
                              "total_floor_area" => { "quantity" => "square metres", "value" => 22.2 },
                              "room_height" => { "quantity" => "metres", "value" => 2.8 } },
                            { "floor" => 1,
                              "heat_loss_perimeter" => { "quantity" => "metres", "value" => 20.4 },
                              "party_wall_length" => 0,
                              "total_floor_area" => { "quantity" => "square metres", "value" => 22.2 },
                              "room_height" => { "quantity" => "metres", "value" => 2.8 } }],
                          "floor_heat_loss" => 7,
                          "roof_construction" => 4,
                          "roof_insulation_location" => 2,
                          "roof_insulation_thickness" => "150mm",
                          "wall_construction" => 3,
                          "wall_insulation_type" => 4,
                          "wall_thickness_measured" => "Y",
                          "wall_thickness" => 270,
                          "wall_dry_lined" => "N",
                          "wall_insulation_thickness" => "NI",
                          "party_wall_construction" => "NA" }],
                      "sap_heating" =>
                       { "main_heating_details" =>
                          [{ "main_heating_number" => 1,
                             "main_heating_category" => 2,
                             "main_fuel_type" => 28,
                             "main_heating_control" => 2102,
                             "main_heating_data_source" => 2,
                             "sap_main_heating_code" => 125,
                             "boiler_flue_type" => 1,
                             "fan_flue_present" => "N",
                             "heat_emitter_type" => 1,
                             "main_heating_fraction" => 1,
                             "has_fghrs" => "N",
                             "emitter_temperature" => "NA",
                             "central_heating_pump_age" => 1 }],
                         "water_heating_code" => 901,
                         "water_heating_fuel" => 28,
                         "secondary_heating_type" => 631,
                         "secondary_fuel_type" => 9,
                         "immersion_heating_type" => "NA",
                         "cylinder_size" => 2,
                         "cylinder_insulation_type" => 2,
                         "cylinder_insulation_thickness" => 80,
                         "cylinder_thermostat" => "N",
                         "has_fixed_air_conditioning" => "false",
                         "instantaneous_wwhrs" =>
                          { "rooms_with_bath_and_or_shower" => 1,
                            "rooms_with_mixer_shower_no_bath" => 0,
                            "rooms_with_bath_and_mixer_shower" => 1 } },
                      "sap_energy_source" =>
                       { "meter_type" => 2,
                         "mains_gas" => "N",
                         "wind_turbines_count" => 0,
                         "wind_turbines_terrain_type" => 2,
                         "photovoltaic_supply" =>
                           { "none_or_no_details" => { "percent_roof_area" => 0, "pv_connection" => 0 } } } }

      expect(use_case.execute(xml: rdsap,
                              schema_type: "RdSAP-Schema-NI-18.0",
                              assessment_id: "7777-6666-5555-4444-3333")).to eq(expectation)
    end
  end
end
