RSpec.describe "parsing with an NI RdSAP configuration" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from RdSAP (NI)" do
    let(:rdsap) do
      Samples.xml("RdSAP-Schema-NI-19.0")
    end

    it "parses the document in the expected format" do
      expectation = { "schema_version_original" => "LIG-19.0",
                      "sap_version" => 9.94,
                      "calculation_software_name" => "Elmhurst Energy Systems RdSAP Calculator",
                      "calculation_software_version" => "4.05r0005",
                      "inspection_date" => "2020-07-30",
                      "report_type" => 2,
                      "completion_date" => "2020-07-30",
                      "registration_date" => "2020-07-30",
                      "status" => "entered",
                      "language_code" => 1,
                      "tenure" => 1,
                      "transaction_type" => 1,
                      "property_type" => 0,
                      "scheme_assessor_id" => "EXM/000000",
                      "address_line_1" => "35, Address Lane",
                      "post_town" => "New Town",
                      "postcode" => "BT1 1AA",
                      "uprn" => 9_876_543_210,
                      "region_code" => 10,
                      "country_code" => "NIR",
                      "walls" =>
                       [{ "description" => "Cavity wall, filled cavity",
                          "energy_efficiency_rating" => 3,
                          "environmental_efficiency_rating" => 3 }],
                      "roofs" =>
                       [{ "description" => "Pitched, 100 mm loft insulation",
                          "energy_efficiency_rating" => 3,
                          "environmental_efficiency_rating" => 3 }],
                      "floors" =>
                       [{ "description" => "Suspended, no insulation (assumed)",
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 }],
                      "window" =>
                       { "description" => "Fully double glazed",
                         "energy_efficiency_rating" => 4,
                         "environmental_efficiency_rating" => 4 },
                      "main-heating" =>
                       [{ "description" => "Boiler and radiators, mains gas",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "main_heating_controls" =>
                       [{ "description" => "Programmer, room thermostat and TRVs",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "hot_water" =>
                       { "description" => "From main system",
                         "energy_efficiency_rating" => 4,
                         "environmental_efficiency_rating" => 4 },
                      "lighting" =>
                       { "description" => "Low energy lighting in all fixed outlets",
                         "energy_efficiency_rating" => 5,
                         "environmental_efficiency_rating" => 5 },
                      "secondary_heating" =>
                       { "description" => "Room heaters, dual fuel (mineral and wood)",
                         "energy_efficiency_rating" => 0,
                         "environmental_efficiency_rating" => 0 },
                      "has_hot_water_cylinder" => "false",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Semi-detached house",
                      "total_floor_area" => 152,
                      "has_fixed_air_conditioning" => "false",
                      "multiple_glazed_proportion" => 100,
                      "energy_rating_average" => 60,
                      "energy_rating_current" => 67,
                      "energy_rating_potential" => 71,
                      "environmental_impact_current" => 60,
                      "environmental_impact_potential" => 65,
                      "energy_consumption_current" => 208,
                      "energy_consumption_potential" => 182,
                      "co2_emissions_current" => 5.7,
                      "co2_emissions_potential" => 5.0,
                      "co2_emissions_current_per_floor_area" => 38,
                      "lighting_cost_current" => { "currency" => "GBP", "value" => 98 },
                      "lighting_cost_potential" => { "currency" => "GBP", "value" => 98 },
                      "heating_cost_current" => { "currency" => "GBP", "value" => 1010 },
                      "heating_cost_potential" => { "currency" => "GBP", "value" => 877 },
                      "hot_water_cost_current" => { "currency" => "GBP", "value" => 107 },
                      "hot_water_cost_potential" => { "currency" => "GBP", "value" => 107 },
                      "suggested_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 1,
                          "improvement_type" => "A",
                          "improvement_details" => { "improvement_number" => 5 },
                          "typical_saving" => { "currency" => "GBP", "value" => 37 },
                          "indicative_cost" => "£100 - £350",
                          "energy_performance_rating" => 68,
                          "environmental_impact_rating" => 62 },
                        { "sequence" => 2,
                          "improvement_category" => 2,
                          "improvement_type" => "W1",
                          "improvement_details" => { "improvement_number" => 57 },
                          "typical_saving" => { "currency" => "GBP", "value" => 96 },
                          "indicative_cost" => "£800 - £1,200",
                          "energy_performance_rating" => 71,
                          "environmental_impact_rating" => 65 },
                        { "sequence" => 3,
                          "improvement_category" => 3,
                          "improvement_type" => "U",
                          "improvement_details" => { "improvement_number" => 34 },
                          "typical_saving" => { "currency" => "GBP", "value" => 327 },
                          "indicative_cost" => "£3,500 - £5,500",
                          "energy_performance_rating" => 77,
                          "environmental_impact_rating" => 71 }],
                      "built_form" => 2,
                      "extensions_count" => 0,
                      "multiple_glazing_type" => 2,
                      "glazed_area" => 1,
                      "door_count" => 2,
                      "insulated_door_count" => 0,
                      "percent_draughtproofed" => 100,
                      "habitable_room_count" => 7,
                      "heated_room_count" => 7,
                      "fixed_lighting_outlets_count" => 20,
                      "low_energy_fixed_lighting_outlets_count" => 20,
                      "low_energy_lighting" => 100,
                      "measurement_type" => 1,
                      "mechanical_ventilation" => 0,
                      "open_fireplaces_count" => 2,
                      "solar_water_heating" => "N",
                      "conservatory_type" => 1,
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "identifier" => "Main Dwelling",
                          "construction_age_band" => "C",
                          "sap_floor_dimensions" =>
                           [{ "floor" => 0,
                              "floor_construction" => 2,
                              "floor_insulation" => 1,
                              "heat_loss_perimeter" => { "quantity" => "metres", "value" => 34.83 },
                              "party_wall_length" => { "quantity" => "metres", "value" => 7.31 },
                              "total_floor_area" => { "quantity" => "square metres", "value" => 79.26 },
                              "room_height" => { "quantity" => "metres", "value" => 2.66 } },
                            { "floor" => 1,
                              "heat_loss_perimeter" => { "quantity" => "metres", "value" => 31.51 },
                              "party_wall_length" => { "quantity" => "metres", "value" => 7.31 },
                              "total_floor_area" => { "quantity" => "square metres", "value" => 72.85 },
                              "room_height" => { "quantity" => "metres", "value" => 2.55 } }],
                          "floor_insulation_thickness" => "NI",
                          "floor_heat_loss" => 7,
                          "roof_construction" => 4,
                          "roof_insulation_location" => 2,
                          "roof_insulation_thickness" => "100mm",
                          "wall_construction" => 4,
                          "wall_insulation_type" => 2,
                          "wall_thickness_measured" => "Y",
                          "wall_thickness" => 300,
                          "wall_dry_lined" => "N",
                          "wall_insulation_thickness" => "NI",
                          "party_wall_construction" => 0 }],
                      "sap_heating" =>
                       { "main_heating_details" =>
                          [{ "main_heating_number" => 1,
                             "main_heating_category" => 2,
                             "main_fuel_type" => 26,
                             "main_heating_control" => 2106,
                             "main_heating_data_source" => 1,
                             "main_heating_index_number" => 16_650,
                             "boiler_flue_type" => 2,
                             "fan_flue_present" => "Y",
                             "heat_emitter_type" => 1,
                             "main_heating_fraction" => 1,
                             "has_fghrs" => "N",
                             "emitter_temperature" => 0,
                             "central_heating_pump_age" => 0 }],
                         "water_heating_code" => 901,
                         "water_heating_fuel" => 26,
                         "secondary_heating_type" => 633,
                         "secondary_fuel_type" => 9,
                         "immersion_heating_type" => "NA",
                         "cylinder_size" => 1,
                         "has_fixed_air_conditioning" => "false",
                         "instantaneous_wwhrs" =>
                          { "rooms_with_bath_and_or_shower" => 1,
                            "rooms_with_mixer_shower_no_bath" => 0,
                            "rooms_with_bath_and_mixer_shower" => 1 } },
                      "sap_energy_source" =>
                       { "meter_type" => 2,
                         "mains_gas" => "Y",
                         "wind_turbines_count" => 0,
                         "wind_turbines_terrain_type" => 2,
                         "photovoltaic_supply" =>
                          { "none_or_no_details" => { "percent_roof_area" => 0, "pv_connection" => 0 } } } }

      expect(use_case.execute(xml: rdsap,
                              schema_type: "RdSAP-Schema-NI-19.0",
                              assessment_id: "9999-0000-6543-8765-9876")).to eq(expectation)
    end
  end
end
