RSpec.describe "parsing with an NI RdSAP configuration (17.4)" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from RdSAP (NI)" do
    let(:rdsap) do
      Samples.xml("RdSAP-Schema-NI-17.4")
    end

    it "parses the document in the expected format" do
      expectation = { "schema_version_original" => "LIG-17.4",
                      "sap_version" => 9.92,
                      "calculation_software_name" => "Elmhurst Energy Systems RdSAP Calculator",
                      "calculation_software_version" => "2.11r11",
                      "inspection_date" => "2017-06-01",
                      "report_type" => 2,
                      "completion_date" => "2017-06-07",
                      "registration_date" => "2017-06-07",
                      "status" => "entered",
                      "language_code" => 1,
                      "tenure" => 1,
                      "transaction_type" => 1,
                      "property_type" => 0,
                      "scheme_assessor_id" => "SCHE020202",
                      "address_line_1" => "36 Nowhere Street",
                      "post_town" => "BELFAST",
                      "postcode" => "BT1 1AA",
                      "uprn" => 98_798_798_789,
                      "region_code" => 10,
                      "country_code" => "NIR",
                      "walls" =>
                       [{ "description" => "Cavity wall, filled cavity",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "roofs" =>
                       [{ "description" => "Pitched, no insulation (assumed)",
                          "energy_efficiency_rating" => 1,
                          "environmental_efficiency_rating" => 1 },
                        { "description" => "Pitched, limited insulation (assumed)",
                          "energy_efficiency_rating" => 2,
                          "environmental_efficiency_rating" => 2 }],
                      "floors" =>
                       [{ "description" => "Suspended, no insulation (assumed)",
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 },
                        { "description" => "Solid, no insulation (assumed)",
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 }],
                      "window" =>
                       { "description" => "Single glazed",
                         "energy_efficiency_rating" => 1,
                         "environmental_efficiency_rating" => 1 },
                      "main-heating" =>
                       [{ "description" => "Boiler and radiators, oil",
                          "energy_efficiency_rating" => 2,
                          "environmental_efficiency_rating" => 3 }],
                      "main_heating_controls" =>
                       [{ "description" => "Programmer, no room thermostat",
                          "energy_efficiency_rating" => 1,
                          "environmental_efficiency_rating" => 1 }],
                      "hot_water" =>
                       { "description" => "From main system, no cylinder thermostat",
                         "energy_efficiency_rating" => 1,
                         "environmental_efficiency_rating" => 1 },
                      "lighting" =>
                       { "description" => "Low energy lighting in 8% of fixed outlets",
                         "energy_efficiency_rating" => 1,
                         "environmental_efficiency_rating" => 1 },
                      "secondary_heating" =>
                       { "description" => "Room heaters, electric",
                         "energy_efficiency_rating" => 0,
                         "environmental_efficiency_rating" => 0 },
                      "has_hot_water_cylinder" => "true",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Semi-detached house",
                      "total_floor_area" => 100,
                      "has_fixed_air_conditioning" => "false",
                      "multiple_glazed_proportion" => 0,
                      "energy_rating_average" => 60,
                      "energy_rating_current" => 21,
                      "energy_rating_potential" => 48,
                      "environmental_impact_current" => 21,
                      "environmental_impact_potential" => 42,
                      "energy_consumption_current" => 432,
                      "energy_consumption_potential" => 261,
                      "co2_emissions_current" => 11,
                      "co2_emissions_potential" => 6.4,
                      "co2_emissions_current_per_floor_area" => 109,
                      "lighting_cost_current" => { "currency" => "GBP", "value" => 121 },
                      "lighting_cost_potential" => { "currency" => "GBP", "value" => 63 },
                      "heating_cost_current" => { "currency" => "GBP", "value" => 1259 },
                      "heating_cost_potential" => { "currency" => "GBP", "value" => 890 },
                      "hot_water_cost_current" => { "currency" => "GBP", "value" => 361 },
                      "hot_water_cost_potential" => { "currency" => "GBP", "value" => 118 },
                      "suggested_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 1,
                          "improvement_type" => "E",
                          "improvement_details" => { "improvement_number" => 35 },
                          "typical_saving" => { "currency" => "GBP", "value" => 47 },
                          "indicative_cost" => "£55",
                          "energy_performance_rating" => 22,
                          "environmental_impact_rating" => 21 },
                        { "sequence" => 2,
                          "improvement_category" => 1,
                          "improvement_type" => "G",
                          "improvement_details" => { "improvement_number" => 12 },
                          "typical_saving" => { "currency" => "GBP", "value" => 169 },
                          "indicative_cost" => "£350 - £450",
                          "energy_performance_rating" => 27,
                          "environmental_impact_rating" => 25 },
                        { "sequence" => 3,
                          "improvement_category" => 2,
                          "improvement_type" => "W1",
                          "improvement_details" => { "improvement_number" => 57 },
                          "typical_saving" => { "currency" => "GBP", "value" => 38 },
                          "indicative_cost" => "£800 - £1,200",
                          "energy_performance_rating" => 29,
                          "environmental_impact_rating" => 26 },
                        { "sequence" => 4,
                          "improvement_category" => 2,
                          "improvement_type" => "I",
                          "improvement_details" => { "improvement_number" => 20 },
                          "typical_saving" => { "currency" => "GBP", "value" => 416 },
                          "indicative_cost" => "£2,200 - £3,000",
                          "energy_performance_rating" => 48,
                          "environmental_impact_rating" => 42 },
                        { "sequence" => 5,
                          "improvement_category" => 3,
                          "improvement_type" => "N",
                          "improvement_details" => { "improvement_number" => 19 },
                          "typical_saving" => { "currency" => "GBP", "value" => 41 },
                          "indicative_cost" => "£4,000 - £6,000",
                          "energy_performance_rating" => 50,
                          "environmental_impact_rating" => 44 },
                        { "sequence" => 6,
                          "improvement_category" => 3,
                          "improvement_type" => "O",
                          "improvement_details" => { "improvement_number" => 8 },
                          "typical_saving" => { "currency" => "GBP", "value" => 82 },
                          "indicative_cost" => "£3,300 - £6,500",
                          "energy_performance_rating" => 54,
                          "environmental_impact_rating" => 48 },
                        { "sequence" => 7,
                          "improvement_category" => 3,
                          "improvement_type" => "U",
                          "improvement_details" => { "improvement_number" => 34 },
                          "typical_saving" => { "currency" => "GBP", "value" => 267 },
                          "indicative_cost" => "£5,000 - £8,000",
                          "energy_performance_rating" => 63,
                          "environmental_impact_rating" => 55 }],
                      "built_form" => 2,
                      "extensions_count" => 1,
                      "multiple_glazing_type" => "ND",
                      "glazed_area" => 1,
                      "door_count" => 2,
                      "insulated_door_count" => 0,
                      "percent_draughtproofed" => 100,
                      "habitable_room_count" => 5,
                      "heated_room_count" => 5,
                      "fixed_lighting_outlets_count" => 12,
                      "low_energy_fixed_lighting_outlets_count" => 1,
                      "low_energy_lighting" => 8,
                      "measurement_type" => 1,
                      "mechanical_ventilation" => 0,
                      "open_fireplaces_count" => 2,
                      "solar_water_heating" => "N",
                      "conservatory_type" => 1,
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "identifier" => "Main Dwelling",
                          "construction_age_band" => "D",
                          "sap_floor_dimensions" =>
                           [{ "floor" => 0,
                              "floor_construction" => 2,
                              "floor_insulation" => 1,
                              "heat_loss_perimeter" => { "quantity" => "metres", "value" => 13.38 },
                              "party_wall_length" => { "quantity" => "metres", "value" => 7.28 },
                              "total_floor_area" => { "quantity" => "square metres", "value" => 44.4 },
                              "room_height" => { "quantity" => "metres", "value" => 2.4 } },
                            { "floor" => 1,
                              "heat_loss_perimeter" => { "quantity" => "metres", "value" => 20.9 },
                              "party_wall_length" => { "quantity" => "metres", "value" => 7.28 },
                              "total_floor_area" => { "quantity" => "square metres", "value" => 45.99 },
                              "room_height" => { "quantity" => "metres", "value" => 2.42 } }],
                          "floor_heat_loss" => 7,
                          "roof_construction" => 4,
                          "roof_insulation_location" => 4,
                          "roof_insulation_thickness" => "ND",
                          "wall_construction" => 4,
                          "wall_insulation_type" => 2,
                          "wall_thickness_measured" => "Y",
                          "wall_thickness" => 300,
                          "wall_dry_lined" => "N",
                          "wall_insulation_thickness" => "NI",
                          "party_wall_construction" => 0 },
                        { "building_part_number" => 2,
                          "identifier" => "Extension 1",
                          "construction_age_band" => "F",
                          "sap_floor_dimensions" =>
                           [{ "floor" => 0,
                              "floor_construction" => 1,
                              "floor_insulation" => 1,
                              "heat_loss_perimeter" => { "quantity" => "metres", "value" => 10 },
                              "party_wall_length" => { "quantity" => "metres", "value" => 0 },
                              "total_floor_area" => { "quantity" => "square metres", "value" => 10 },
                              "room_height" => { "quantity" => "metres", "value" => 2.4 } }],
                          "floor_heat_loss" => 7,
                          "roof_construction" => 5,
                          "roof_insulation_location" => 4,
                          "roof_insulation_thickness" => "ND",
                          "wall_construction" => 4,
                          "wall_insulation_type" => 2,
                          "wall_thickness_measured" => "Y",
                          "wall_thickness" => 300,
                          "wall_dry_lined" => "N",
                          "wall_insulation_thickness" => "NI",
                          "party_wall_construction" => "NA" }],
                      "sap_heating" =>
                       { "main_heating_details" =>
                          [{ "main_heating_number" => 1,
                             "main_heating_category" => 2,
                             "main_fuel_type" => 28,
                             "main_heating_control" => 2102,
                             "main_heating_data_source" => 2,
                             "sap_main_heating_code" => 125,
                             "boiler_flue_type" => 2,
                             "fan_flue_present" => "N",
                             "heat_emitter_type" => 1,
                             "main_heating_fraction" => 1,
                             "has_fghrs" => "N",
                             "emitter_temperature" => "NA",
                             "central_heating_pump_age" => 0 }],
                         "water_heating_code" => 901,
                         "water_heating_fuel" => 28,
                         "secondary_heating_type" => 691,
                         "secondary_fuel_type" => 29,
                         "immersion_heating_type" => "NA",
                         "cylinder_size" => 0,
                         "has_fixed_air_conditioning" => "false",
                         "instantaneous_wwhrs" =>
                          { "rooms_with_bath_and_or_shower" => 1,
                            "rooms_with_mixer_shower_no_bath" => 0,
                            "rooms_with_bath_and_mixer_shower" => 0 } },
                      "sap_energy_source" =>
                       { "meter_type" => 2,
                         "mains_gas" => "N",
                         "wind_turbines_count" => 0,
                         "wind_turbines_terrain_type" => 2,
                         "photovoltaic_supply" =>
                          { "none_or_no_details" =>
                             { "percent_roof_area" => 0, "pv_connection" => 0 } } } }

      expect(use_case.execute(xml: rdsap,
                              schema_type: "RdSAP-Schema-NI-17.4",
                              assessment_id: "8888-7777-6666-5555-4444")).to eq(expectation)
    end
  end
end
