RSpec.describe "the parser and the rdsap configuration" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading xml from RdSap" do
    let(:rdsap) do
      Samples.xml("RdSAP-Schema-21.0.0")
    end

    it "parses the document in the expected format" do
      expectation = { "calculation_software_name" => "SomeSoft RdSAP Calculator",
                      "calculation_software_version" => "13.05r16",
                      "schema_version_original" => "SAP-19.0",
                      "sap_version" => 10.2,
                      "walls" =>
                       [{ "description" => "Solid brick, as built, no insulation (assumed)",
                          "energy_efficiency_rating" => 1,
                          "environmental_efficiency_rating" => 1 },
                        { "description" => "Cavity wall, as built, insulated (assumed)",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "roofs" =>
                       [{ "description" => "Pitched, 25 mm loft insulation",
                          "energy_efficiency_rating" => 2,
                          "environmental_efficiency_rating" => 2 },
                        { "description" => "Pitched, 250 mm loft insulation",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "floors" =>
                       [{ "description" => "Suspended, no insulation (assumed)",
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 },
                        { "description" => "Solid, insulated (assumed)",
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 }],
                      "window" =>
                       { "description" => "Fully double glazed",
                         "energy_efficiency_rating" => 3,
                         "environmental_efficiency_rating" => 3 },
                      "main_heating" =>
                       [{ "description" => "Boiler and radiators, anthracite",
                          "energy_efficiency_rating" => 3,
                          "environmental_efficiency_rating" => 1 },
                        { "description" => "Boiler and radiators, mains gas",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "main_heating_controls" =>
                       [{ "description" => "Programmer, room thermostat and TRVs",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 },
                        { "description" => "Time and temperature zone control",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "hot_water" =>
                       { "description" => "From main system",
                         "energy_efficiency_rating" => 4,
                         "environmental_efficiency_rating" => 4 },
                      "lighting" =>
                       { "description" => "Low energy lighting in 50% of fixed outlets",
                         "energy_efficiency_rating" => 4,
                         "environmental_efficiency_rating" => 4 },
                      "secondary_heating" =>
                       { "description" => "Room heaters, electric",
                         "energy_efficiency_rating" => 0,
                         "environmental_efficiency_rating" => 0 },
                      "has_hot_water_cylinder" => "true",
                      "dwelling_type" => "Mid-terrace house",
                      "total_floor_area" => 55,
                      "has_fixed_air_conditioning" => "false",
                      "multiple_glazed_proportion" => 100,
                      "energy_rating_current" => 50,
                      "energy_rating_potential" => 72,
                      "energy_rating_average" => 60,
                      "environmental_impact_current" => 52,
                      "environmental_impact_potential" => 74,
                      "energy_consumption_current" => 230,
                      "energy_consumption_potential" => 88,
                      "co2_emissions_current" => 2.4,
                      "co2_emissions_current_per_floor_area" => 20,
                      "co2_emissions_potential" => 1.4,
                      "lighting_cost_current" => 123.45,
                      "lighting_cost_potential" => 84.23,
                      "heating_cost_current" => 365.98,
                      "heating_cost_potential" => 250.34,
                      "hot_water_cost_current" => 200.4,
                      "hot_water_cost_potential" => 180.43,
                      "suggested_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 6,
                          "improvement_type" => "Z3",
                          "typical_saving" => 360,
                          "energy_performance_rating" => 50,
                          "environmental_impact_rating" => 50,
                          "indicative_cost" => "£100 - £350",
                          "improvement_details" =>
                                                      { "improvement_number" => 5 } },
                        { "sequence" => 2,
                          "improvement_category" => 2,
                          "improvement_type" => "Z2",
                          "typical_saving" => 99,
                          "energy_performance_rating" => 60,
                          "environmental_impact_rating" => 64,
                          "indicative_cost" => 2000,
                          "improvement_details" =>
                            { "improvement_number" => 1 } },
                        { "sequence" => 3,
                          "improvement_category" => 2,
                          "improvement_type" => "Z2",
                          "typical_saving" => 99,
                          "energy_performance_rating" => 60,
                          "environmental_impact_rating" => 64,
                          "indicative_cost" => 1000,
                          "improvement_details" =>
                            { "improvement_texts" =>
                                { "improvement_description" => "Improvement desc" } } }],
                      "renewable_heat_incentive" =>
                       { "space_heating_existing_dwelling" => 13_120,
                         "water_heating" => 2285,
                         "impact_of_loft_insulation" => -2114,
                         "impact_of_cavity_insulation" => -122,
                         "impact_of_solid_wall_insulation" => -3560 },
                      "addendum" =>
                       { "addendum_numbers" => [1, 8],
                         "stone_walls" => "true",
                         "system_build" => "true" },
                      "property_type" => 0,
                      "built_form" => 2,
                      "extensions_count" => 0,
                      "door_count" => 3,
                      "insulated_door_count" => 2,
                      "draughtproofed_door_count" => 1,
                      "insulated_door_u_value" => 3,
                      "windows_transmission_details" =>
                       { "u_value" => 2,
                         "solar_transmittance" => 0.72,
                         "data_source" => 2 },
                      "percent_draughtproofed" => 100,
                      "habitable_room_count" => 5,
                      "heated_room_count" => 5,
                      "measurement_type" => 1,
                      "mechanical_ventilation_index_number" => 12,
                      "mechanical_ventilation" => 6,
                      "mechanical_vent_duct_type" => 3,
                      "mechanical_vent_duct_placement" => 2,
                      "mechanical_vent_duct_insulation" => 2,
                      "mechanical_vent_duct_insulation_level" => 2,
                      "mechanical_vent_measured_installation" => "false",
                      "solar_water_heating" => "N",
                      "conservatory_type" => 1,
                      "sap_flat_details" =>
                       { "flat_location" => 1,
                         "storey_count" => 3,
                         "level" => 1,
                         "top_storey" => "N",
                         "heat_loss_corridor" => 2,
                         "unheated_corridor_length" => 10 },
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "identifier" => "Main Dwelling",
                          "construction_age_band" => "M",
                          "sap_floor_dimensions" =>
                            [{ "floor" => 0,
                               "floor_construction" => 1,
                               "floor_insulation" => 1,
                               "heat_loss_perimeter" =>
                                 { "quantity" => "metres",
                                   "value" => 19.5 },
                               "party_wall_length" =>
                                 { "quantity" => "metres",
                                   "value" => 7.9 },
                               "total_floor_area" =>
                                 { "quantity" => "square metres",
                                   "value" => 45.82 },
                               "room_height" =>
                                 { "quantity" => "metres",
                                   "value" => 2.45 } },
                             { "floor" => 1,
                               "heat_loss_perimeter" =>
                                 { "quantity" => "metres",
                                   "value" => 19.5 },
                               "party_wall_length" =>
                                 { "quantity" => "metres", "value" => 7.9 },
                               "total_floor_area" =>
                                 { "quantity" => "square metres",
                                   "value" => 45.82 },
                               "room_height" => { "quantity" => "metres", "value" => 2.59 } }],
                          "floor_insulation_thickness" => "NI",
                          "floor_heat_loss" => 7,
                          "roof_construction" => 4,
                          "roof_insulation_location" => 2,
                          "roof_insulation_thickness" => "200mm",
                          "wall_construction" => 4,
                          "wall_insulation_type" => 2,
                          "wall_thickness_measured" => "N",
                          "wall_dry_lined" => "N",
                          "wall_insulation_thickness" => "NI",
                          "party_wall_construction" => 0,
                          "sap_room_in_roof" => { "floor_area" => 100, "construction_age_band" => "B" } }],
                      "sap_heating" => { "main_heating_details" => [{ "main_heating_number" => 1, "main_heating_category" => 2, "main_fuel_type" => 26, "main_heating_control" => 2106, "main_heating_data_source" => 1, "sap_main_heating_code" => 101, "main_heating_index_number" => 17_507, "boiler_flue_type" => 2, "fan_flue_present" => "N", "heat_emitter_type" => 1, "main_heating_fraction" => 1, "has_fghrs" => "N", "emitter_temperature" => 0, "central_heating_pump_age" => 0, "boiler_ignition_type" => 1 }], "water_heating_code" => 901, "water_heating_fuel" => 26, "immersion_heating_type" => "NA", "cylinder_size" => 1, "has_fixed_air_conditioning" => "false", "instantaneous_wwhrs" => { "wwhrs_index_number1" => 1, "wwhrs_index_number2" => 2 }, "secondary_fuel_type" => 25, "shower_outlets" => { "shower_outlet" => { "shower_outlet_type" => 1, "shower_wwhrs" => 1 } } },
                      "sap_energy_source" => { "meter_type" => 2, "mains_gas" => "Y", "wind_turbines_count" => 0, "wind_turbines_terrain_type" => 4, "photovoltaic_supply" => { "none_or_no_details" => { "percent_roof_area" => 0 } }, "pv_battery_count" => 1, "pv_batteries" => { "pv_battery" => { "battery_capacity" => 5 } }, "electricity_smart_meter_present" => "true", "gas_smart_meter_present" => "false", "is_dwelling_export_capable" => "false", "wind_turbine_details" => { "rotor_diameter" => 0, "hub_height" => 0 }, "pv_connection" => 0 },
                      "sap_windows" => [{ "window_location" => 0, "window_height" => 2.0, "window_width" => 1.2, "draught_proofed" => "true", "glazing_type" => 14, "window_type" => 2, "orientation" => 1, "window_transmission_details" => { "data_source" => 2, "u_value" => 1.0, "solar_transmittance" => 1.0 }, "pvc_frame" => "false", "glazing_gap" => 6, "frame_factor" => 1.0, "window_wall_type" => 6, "permanent_shutters_present" => "N", "permanent_shutters_insulated" => "N" }, { "window_location" => 1, "window_height" => 2.0, "window_width" => 1.2, "draught_proofed" => "true", "glazing_type" => 1, "window_type" => 2, "orientation" => 1, "window_transmission_details" => { "data_source" => 2, "u_value" => 1.0, "solar_transmittance" => 1.0 }, "pvc_frame" => "false", "glazing_gap" => 6, "frame_factor" => 1.0, "window_wall_type" => 6, "permanent_shutters_present" => "N", "permanent_shutters_insulated" => "N" }],
                      "cfl_fixed_lighting_bulbs_count" => 5,
                      "led_fixed_lighting_bulbs_count" => 10,
                      "low_energy_fixed_lighting_bulbs_count" => 16,
                      "incandescent_fixed_lighting_bulbs_count" => 0,
                      "pressure_test_certificate_number" => 0,
                      "wet_rooms_count" => 0,
                      "pressure_test" => 6,
                      "inspection_date" => "2023-12-01",
                      "report_type" => 2,
                      "completion_date" => "2023-12-01",
                      "registration_date" => "2023-12-01",
                      "status" => "entered",
                      "language_code" => 1,
                      "region_code" => 1,
                      "country_code" => "ENG",
                      "transaction_type" => 16,
                      "tenure" => 1,
                      "scheme_assessor_id" => "SPEC000000",
                      "address_line_1" => "1 Some Street",
                      "post_town" => "Whitbury",
                      "postcode" => "A0 0AA",
                      "uprn" => "UPRN-000000000000" }

      result = use_case.execute(xml: rdsap,
                                schema_type: "RdSAP-Schema-21.0.0",
                                assessment_id: "0000-0000-0000-0000-0000")

      expect(result).to eq(expectation)
    end
  end
end
