RSpec.describe "the parser and the CEPC configuration for schema 7.0" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from CEPC" do
    let(:cepc) { Samples.xml "CEPC-7.0", "cepc+rr" }

    it "parses the document in the expected format" do
      expectation = { "issue_date" => "2013-08-16",
                      "report_type" => 3,
                      "valid_until" => "2023-08-15",
                      "related_rrn" => "4444-5555-6666-7777-8889",
                      "inspection_date" => "2013-08-10",
                      "registration_date" => "2013-08-15",
                      "status" => "entered",
                      "language_code" => 1,
                      "scheme_assessor_id" => "SCHE020302",
                      "building_complexity" => "Level 3",
                      "location_description" => "Located in main shopping area in Posttown town centre",
                      "uprn" => 987_345_673_489,
                      "address_line_2" => "Acme Coffee",
                      "address_line_3" => "13 Old Street",
                      "post_town" => "POSTTOWN",
                      "postcode" => "PT42 7AD",
                      "property_type" => "A3/A4/A5 Restaurant and Cafes/Drinking Establishments and Hot Food takeaways",
                      "owner" => "Joe Coffee",
                      "is_heritage_site" => "N",
                      "methodology" => "SBEM",
                      "calculation_tool" => "CLG, iSBEM, v4.1.e, SBEM, v4.1.e.5",
                      "output_engine" => "EPCgen, v4.1.e.5",
                      "inspection_type" => "Physical",
                      "summary_of_performance" =>
                       { "building_data" =>
                          [{ "analysis_type" => "ACTUAL",
                             "area" => 313.8,
                             "area_exterior" => 873.7,
                             "weather" => "BEL",
                             "q50_infiltration" => 25,
                             "building_w_k" => 1317.44,
                             "building_w_m2k" => 1.50789,
                             "building_alpha" => 3.81869,
                             "activities" => { "activity" => { "id" => 1031, "area" => 41.1 } },
                             "global_performance" =>
                              { "kwh_m2_heating" => 139.499,
                                "kwh_m2_cooling" => 0,
                                "kwh_m2_auxiliary" => 1.06611,
                                "kwh_m2_lighting" => 139.423,
                                "kwh_m2_dhw" => 27.3554,
                                "kwh_m2_equipment" => 66.704,
                                "kwh_m2_natural_gas" => 0,
                                "kwh_m2_lpg" => 0,
                                "kwh_m2_biogas" => 0,
                                "kwh_m2_oil" => 0,
                                "kwh_m2_coal" => 0,
                                "kwh_m2_anthracite" => 0,
                                "kwh_m2_smokeless" => 0,
                                "kwh_m2_dual_fuel" => 0,
                                "kwh_m2_biomass" => 0,
                                "kwh_m2_supplied" => 307.344,
                                "kwh_m2_waste_heat" => 0,
                                "kwh_m2_district_heating" => 0,
                                "kwh_m2_displaced" => 0,
                                "kwh_m2_pvs" => 0,
                                "kwh_m2_wind" => 0,
                                "kwh_m2_chp" => 0,
                                "kwh_m2_ses" => 0 },
                             "hvac_systems" =>
                              { "hvac_system_data" =>
                                 { "area" => 171.2,
                                   "type" => "Other local room heater - unfanned",
                                   "heat_source" => "Room heater",
                                   "fuel_type" => "Grid Supplied Electricity",
                                   "mj_m2_heating_dem" => 736.402,
                                   "mj_m2_cooling_dem" => 683.721,
                                   "kwh_m2_heating" => 255.695,
                                   "kwh_m2_cooling" => 0,
                                   "kwh_m2_auxiliary" => 1.95411,
                                   "heating_sseff" => 0.8,
                                   "cooling_sseer" => 0,
                                   "heating_gen_seff" => 1,
                                   "cooling_gen_seer" => 0,
                                   "activities" => { "activity" => { "id" => 1031, "area" => 41.1 } } } } },
                           { "analysis_type" => "NOTIONAL",
                             "area" => 313.8,
                             "area_exterior" => 873.7,
                             "weather" => "BEL",
                             "q50_infiltration" => 6.0896,
                             "building_w_k" => 301.464,
                             "building_w_m2k" => 0.345043,
                             "building_alpha" => 42.6344,
                             "activities" => { "activity" => { "id" => 1031, "area" => 41.1 } },
                             "global_performance" =>
                              { "kwh_m2_heating" => 57.2199,
                                "kwh_m2_cooling" => 0,
                                "kwh_m2_auxiliary" => 0.284295,
                                "kwh_m2_lighting" => 25.9805,
                                "kwh_m2_dhw" => 32.702,
                                "kwh_m2_equipment" => 66.704,
                                "kwh_m2_natural_gas" => 0,
                                "kwh_m2_lpg" => 0,
                                "kwh_m2_biogas" => 0,
                                "kwh_m2_oil" => 89.9222,
                                "kwh_m2_coal" => 0,
                                "kwh_m2_anthracite" => 0,
                                "kwh_m2_smokeless" => 0,
                                "kwh_m2_dual_fuel" => 0,
                                "kwh_m2_biomass" => 0,
                                "kwh_m2_supplied" => 26.2648,
                                "kwh_m2_waste_heat" => 0,
                                "kwh_m2_district_heating" => 0,
                                "kwh_m2_displaced" => 0,
                                "kwh_m2_pvs" => 0,
                                "kwh_m2_wind" => 0,
                                "kwh_m2_chp" => 0,
                                "kwh_m2_ses" => 0 },
                             "hvac_systems" =>
                              { "hvac_system_data" =>
                                 { "area" => 171.2,
                                   "type" => "Other local room heater - unfanned",
                                   "heat_source" => "Room heater",
                                   "fuel_type" => "Oil",
                                   "mj_m2_heating_dem" => 299.036,
                                   "mj_m2_cooling_dem" => 287.737,
                                   "kwh_m2_heating" => 104.881,
                                   "kwh_m2_cooling" => 0,
                                   "kwh_m2_auxiliary" => 0.521096,
                                   "heating_sseff" => 0.792,
                                   "cooling_sseer" => 0,
                                   "heating_gen_seff" => 0,
                                   "cooling_gen_seer" => 0,
                                   "activities" => { "activity" => { "id" => 1031, "area" => 41.1 } } } } },
                           { "analysis_type" => "REFERENCE",
                             "area" => 313.8,
                             "area_exterior" => 873.7,
                             "weather" => "BEL",
                             "q50_infiltration" => 10,
                             "building_w_k" => 565.419,
                             "building_w_m2k" => 0.647155,
                             "building_alpha" => 10,
                             "activities" => { "activity" => { "id" => 1031, "area" => 41.1 } },
                             "global_performance" =>
                              { "kwh_m2_heating" => 89.2728,
                                "kwh_m2_cooling" => 28.3203,
                                "kwh_m2_auxiliary" => 2.31352,
                                "kwh_m2_lighting" => 61.7212,
                                "kwh_m2_dhw" => 60.7897,
                                "kwh_m2_equipment" => 66.704,
                                "kwh_m2_natural_gas" => 150.062,
                                "kwh_m2_lpg" => 0,
                                "kwh_m2_biogas" => 0,
                                "kwh_m2_oil" => 0,
                                "kwh_m2_coal" => 0,
                                "kwh_m2_anthracite" => 0,
                                "kwh_m2_smokeless" => 0,
                                "kwh_m2_dual_fuel" => 0,
                                "kwh_m2_biomass" => 0,
                                "kwh_m2_supplied" => 92.355,
                                "kwh_m2_waste_heat" => 0,
                                "kwh_m2_district_heating" => 0,
                                "kwh_m2_displaced" => 0,
                                "kwh_m2_pvs" => 0,
                                "kwh_m2_wind" => 0,
                                "kwh_m2_chp" => 0,
                                "kwh_m2_ses" => 0 },
                             "hvac_systems" =>
                              { "hvac_system_data" =>
                                 { "area" => 171.2,
                                   "type" => "Other local room heater - unfanned",
                                   "heat_source" => "Room heater",
                                   "fuel_type" => "Natural Gas",
                                   "mj_m2_heating_dem" => 430.025,
                                   "mj_m2_cooling_dem" => 420.467,
                                   "kwh_m2_heating" => 163.632,
                                   "kwh_m2_cooling" => 51.9095,
                                   "kwh_m2_auxiliary" => 4.24056,
                                   "heating_sseff" => 0.73,
                                   "cooling_sseer" => 2.25,
                                   "heating_gen_seff" => 0,
                                   "cooling_gen_seer" => 0,
                                   "activities" => { "activity" => { "id" => 1031, "area" => 41.1 } } } } }] },
                      "transaction_type" => 1,
                      "asset_rating" => 134,
                      "new_build_benchmark" => 34,
                      "existing_stock_benchmark" => 90,
                      "ser" => 59.26,
                      "ber" => 158.9,
                      "ter" => 39.95,
                      "tyr" => 106.52,
                      "technical_information" =>
                       { "main_heating_fuel" => "Grid Supplied Electricity",
                         "building_environment" => "Heating and Natural Ventilation",
                         "floor_area" => 314,
                         "building_level" => 3 },
                      "ac_questionnaire" =>
                        { "ac_present" => "No",
                          "ac_rated_output" => { "ac_rating_unknown_flag" => 1 },
                          "ac_inspection_commissioned" => 4 } }

      actual = use_case.execute(xml: cepc,
                                schema_type: "CEPC-7.0",
                                assessment_id: "4444-5555-6666-7777-8888")

      expect(actual).to eq(expectation)
    end
  end

  context "when loading XML from CEPC-RR" do
    let(:cepc_rr) { Samples.xml "CEPC-7.0", "cepc+rr" }

    it "parses the document in the expected format" do
      expectation = { "issue_date" => "2013-08-16",
                      "report_type" => 4,
                      "valid_until" => "2023-08-15",
                      "related_rrn" => "4444-5555-6666-7777-8888",
                      "inspection_date" => "2013-08-10",
                      "registration_date" => "2013-08-15",
                      "status" => "entered",
                      "language_code" => 1,
                      "scheme_assessor_id" => "SCHE020302",
                      "building_complexity" => "Level 3",
                      "location_description" => "Located in main shopping area in Posttown town centre",
                      "uprn" => 987_345_673_489,
                      "address_line_2" => "Acme Coffee",
                      "address_line_3" => "13 Old Street",
                      "post_town" => "POSTTOWN",
                      "postcode" => "PT42 7AD",
                      "property_type" => "A3/A4/A5 Restaurant and Cafes/Drinking Establishments and Hot Food takeaways",
                      "owner" => "Joe Coffee",
                      "is_heritage_site" => "N",
                      "methodology" => "SBEM",
                      "calculation_tool" => "CLG, iSBEM, v4.1.e, SBEM, v4.1.e.5",
                      "output_engine" => "EPCgen, v4.1.e.5",
                      "inspection_type" => "Physical",
                      "short_payback" =>
                       [{ "recommendation_code" => "EPC-L2",
                          "recommendation" => "Replace tungsten GLS lamps with CFLs: Payback period dependent on hours of use.",
                          "co2_impact" => "LOW" },
                        { "recommendation_code" => "EPC-L5",
                          "recommendation" => "Consider replacing T8 lamps with retrofit T5 conversion kit.",
                          "co2_impact" => "MEDIUM" },
                        { "recommendation_code" => "EPC-H2",
                          "recommendation" => "Add time control to heating system.",
                          "co2_impact" => "LOW" },
                        { "recommendation_code" => "EPC-H7",
                          "recommendation" => "Add optimum start/stop to the heating system.",
                          "co2_impact" => "MEDIUM" },
                        { "recommendation_code" => "EPC-L7",
                          "recommendation" => "Introduce HF (high frequency) ballasts for fluorescent tubes: Reduced number of fittings required.",
                          "co2_impact" => "LOW" }],
                      "medium_payback" =>
                       [{ "recommendation_code" => "EPC-E4",
                          "recommendation" => "Some walls have uninsulated cavities - introduce cavity wall insulation.",
                          "co2_impact" => "MEDIUM" },
                        { "recommendation_code" => "EPC-E5",
                          "recommendation" => "Some windows have high U-values - consider installing secondary glazing.",
                          "co2_impact" => "MEDIUM" },
                        { "recommendation_code" => "EPC-H6",
                          "recommendation" => "Add local temperature control to the heating system.",
                          "co2_impact" => "MEDIUM" },
                        { "recommendation_code" => "EPC-H8",
                          "recommendation" => "Add weather compensation controls to heating system.",
                          "co2_impact" => "MEDIUM" },
                        { "recommendation_code" => "EPC-E6",
                          "recommendation" => "Some loft spaces are poorly insulated - install/improve insulation.",
                          "co2_impact" => "MEDIUM" },
                        { "recommendation_code" => "EPC-H5",
                          "recommendation" => "Add local time control to heating system.",
                          "co2_impact" => "LOW" },
                        { "recommendation_code" => "EPC-E7",
                          "recommendation" => "Carry out a pressure test, identify and treat identified air leakage. Enter result in EPC calculation.",
                          "co2_impact" => "MEDIUM" }],
                      "long_payback" =>
                       [{ "recommendation_code" => "EPC-E8",
                          "recommendation" => "Some glazing is poorly insulated. Replace/improve glazing and/or frames.",
                          "co2_impact" => "MEDIUM" },
                        { "recommendation_code" => "EPC-R5",
                          "recommendation" => "Consider installing an air source heat pump.",
                          "co2_impact" => "HIGH" },
                        { "recommendation_code" => "EPC-R3",
                          "recommendation" => "Consider installing solar water heating.",
                          "co2_impact" => "LOW" },
                        { "recommendation_code" => "EPC-R4",
                          "recommendation" => "Consider installing PV.",
                          "co2_impact" => "LOW" }],
                      "technical_information" => { "building_environment" => "Heating and Natural Ventilation", "floor_area" => 314, "building_level" => 3 } }

      actual = use_case.execute(xml: cepc_rr,
                                schema_type: "CEPC-7.0",
                                assessment_id: "4444-5555-6666-7777-8889")

      expect(actual).to eq(expectation)
    end
  end

  context "when loading XML from DEC" do
    let(:dec) { Samples.xml "CEPC-7.0", "dec+rr" }

    it "parses the document in the expected format" do
      expectation = { "issue_date" => "2016-02-23",
                      "valid_until" => "2017-04-24",
                      "report_type" => 1,
                      "inspection_date" => "2016-04-11",
                      "registration_date" => "2016-04-25",
                      "status" => "entered",
                      "related_rrn" => "3333-4444-5555-6666-7778",
                      "language_code" => 1,
                      "scheme_assessor_id" => "SCHE000111",
                      "uprn" => 876_764_383_383,
                      "address_line_1" => "Mr Blobby's Sports Academy",
                      "address_line_2" => "Mr Blobby's Academy",
                      "address_line_3" => "Blobby Custard Lane",
                      "post_town" => "POSTTOWN",
                      "postcode" => "PT4 1SK",
                      "property_type" => "Schools And Seasonal Public Buildings; Swimming Pool Centre",
                      "occupier" => "Mr Blobby's Sports Academy",
                      "methodology" => "ORCalc",
                      "calculation_tool" => "Property-Tectonics Ltd, Lifespan DEC, v3.6.1",
                      "output_engine" => "ORGen v3.6.2",
                      "or_assessment_start_date" => "2015-01-01",
                      "or_assessment_end_date" => "2016-01-01",
                      "building_category" => "S3; H6",
                      "or_building_data" =>
                        { "internal_environment" => "Mixed-mode with Natural Ventilation",
                          "assessment_period_alignment" => "End Of Main Heating Fuel Period",
                          "hvac_system" => "Radiators" },
                      "or_benchmark_data" =>
                        { "main_benchmark" => "Schools And Seasonal Public Buildings",
                          "benchmarks" =>
                            [{ "benchmark" =>
                                 { "name" => "Swimming pool",
                                   "benchmark_id" => 2,
                                   "area_metric" => "Gross floor area measured as RICS Gross Internal Area (GIA)",
                                   "floor_area" => 254.52,
                                   "tufa" => 254.52,
                                   "benchmark" => "Swimming Pool Centre",
                                   "occupancy_level" => "Extended Occupancy" } }] },
                      "or_energy_consumption" =>
                        { "electricity" =>
                            { "consumption" => 296_820,
                              "start_date" => "2015-01-01",
                              "end_date" => "2015-12-31",
                              "estimate" => 0 },
                          "gas" =>
                            { "consumption" => 786_655,
                              "start_date" => "2015-01-01",
                              "end_date" => "2016-01-01",
                              "estimate" => 0 } },
                      "or_previous_data" =>
                        { "previous_rating_1" => { "or" => 95, "ormm" => 11, "oryyyy" => 2014 },
                          "previous_rating_2" => { "or" => 113, "ormm" => 11, "oryyyy" => 2013 },
                          "asset_rating" => 0 },
                      "dec_annual_energy_summary" =>
                        { "annual_energy_use_electrical" => 61,
                          "annual_energy_use_fuel_thermal" => 161,
                          "renewables_fuel_thermal" => 0,
                          "renewables_electrical" => 0,
                          "typical_thermal_use" => 244,
                          "typical_electrical_use" => 67 },
                      "dec_status" => 0,
                      "reason_type" => 2,
                      "dec_related_party_disclosure" => 3,
                      "this_assessment" =>
                        { "nominated_date" => "2016-02-23",
                          "energy_rating" => 77,
                          "electricity_co2" => 163,
                          "heating_co2" => 153,
                          "renewables_co2" => 0 },
                      "year1_assessment" =>
                        { "nominated_date" => "2014-11-30",
                          "energy_rating" => 95,
                          "electricity_co2" => 266,
                          "heating_co2" => 176,
                          "renewables_co2" => 0 },
                      "year2_assessment" =>
                        { "nominated_date" => "2013-11-30",
                          "energy_rating" => 113,
                          "electricity_co2" => 333,
                          "heating_co2" => 238,
                          "renewables_co2" => 0 },
                      "technical_information" =>
                        { "main_heating_fuel" => "Natural Gas",
                          "building_environment" => "Mixed-mode with Natural Ventilation",
                          "floor_area" => 4901,
                          "separately_metered_electric_heating" => 0 },
                      "ac_questionnaire" =>
                        { "ac_present" => "Yes",
                          "ac_rated_output" => { "ac_rating_unknown_flag" => 1 },
                          "ac_estimated_output" => 2,
                          "ac_inspection_commissioned" => 4 } }

      actual = use_case.execute(xml: dec,
                                schema_type: "CEPC-7.0",
                                assessment_id: "3333-4444-5555-6666-7777")

      expect(actual).to eq(expectation)
    end
  end

  context "when loading XML from DEC-RR" do
    let(:dec_rr) { Samples.xml "CEPC-7.0", "dec+rr" }

    it "parses the document in the expected format" do
      expectation = { "issue_date" => "2016-02-23",
                      "valid_until" => "2023-02-23",
                      "report_type" => 2,
                      "inspection_date" => "2016-01-11",
                      "registration_date" => "2016-02-23",
                      "status" => "entered",
                      "related_rrn" => "3333-4444-5555-6666-7778",
                      "language_code" => 1,
                      "scheme_assessor_id" => "SCHE000111",
                      "uprn" => 876_764_383_383,
                      "address_line_1" => "Mr Blobby's Sports Academy",
                      "address_line_2" => "Mr Blobby's Academy",
                      "address_line_3" => "Blobby Custard Lane",
                      "post_town" => "POSTTOWN",
                      "postcode" => "PT4 1SK",
                      "property_type" => "Schools And Seasonal Public Buildings; Swimming Pool Centre",
                      "occupier" => "Mr Blobby's Sports Academy",
                      "methodology" => "ORCalc",
                      "calculation_tool" => "Property-Tectonics Ltd, Lifespan DEC, v3.6.1",
                      "output_engine" => "ORGen v3.6.1",
                      "inspection_type" => "Physical",
                      "short_payback" =>
                        [{ "recommendation_code" => "BF6",
                           "recommendation" =>
                             "Consider how building fabric airtightness could be improved, for example sealing, draught stripping and closing off unused ventilation openings, chimneys etc.",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "CON10",
                           "recommendation" => "Seek to minimise simultaneous operation of heating and cooling systems.",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "X24",
                           "recommendation" => "Boiler plant should be regularly tested and adjusted by experts for operating efficiency.",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "HS17",
                           "recommendation" => "If stratification occurs consider re-circulating the air during heating.",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "CON16",
                           "recommendation" =>
                             "If natural ventilation does not provide adequate cooling during the day, consider introducing external air at night to cool the internal space.",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "X9",
                           "recommendation" =>
                             "Engage experts to assess the air conditioning systems in accordance with CIBSE TM 44.  (This could be an appropriate opportunity to engage an accredited energy assessor to undertake an inspection in compliance with the EPB Regulations SI 2007/991 as amended.)",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "SP3",
                           "recommendation" =>
                             "Consider installing automated controls and monitoring systems to electrical equipment and portable appliances to minimise electricity waste.",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "X17",
                           "recommendation" => "Consider a programme of fitting energy meters to the pool complex as part of the service and maintenance regime.",
                           "co2_impact" => "HIGH" },
                         { "recommendation_code" => "X27",
                           "recommendation" =>
                             "Consider with chefs and kitchens managers implementing an energy efficiency plan including maintenance and servicing provisions and operational targets, monitoring and incentives.",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "X28",
                           "recommendation" => "Consider with chefs and kitchen managers implementing a training programme and monitoring systems with incentives.",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "CA23",
                           "recommendation" =>
                             "Ensure catering equipment such as large ovens and dishwashers are utilised at maximum capacity, and/or install smaller capacity appliances to increase operational flexibility.",
                           "co2_impact" => "LOW" }],
                      "medium_payback" =>
                        [{ "recommendation_code" => "BF5",
                           "recommendation" => "Consider applying reflective coating to windows and/or fit shading devices to reduce unwanted solar gain.",
                           "co2_impact" => "LOW" },
                         { "recommendation_code" => "BF22",
                           "recommendation" =>
                             "Consider engaging experts to review the condition of the building fabric and propose measures to improve energy performance, i.e. building pressure tests for air tightness and thermography tests to ensure insulation continuity.",
                           "co2_impact" => "HIGH" },
                         { "recommendation_code" => "BF9", "recommendation" => "Consider introducing or improving cavity wall insulation.", "co2_impact" => "HIGH" },
                         { "recommendation_code" => "CON18",
                           "recommendation" => "Consider upgrading major time controls to include optimum start/stop.",
                           "co2_impact" => "HIGH" },
                         { "recommendation_code" => "SP14",
                           "recommendation" =>
                             "Consider with experts implementation of an energy efficient equipment procurement regime that will upgrade existing equipment and renew in a planned cost-effective programme.",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "X18",
                           "recommendation" =>
                             "Consider with experts how the pool complex air tightness can be improved, for example sealed better and fitted with air lock or revolving doors.",
                           "co2_impact" => "HIGH" },
                         { "recommendation_code" => "P3",
                           "recommendation" => "Consider with experts the benefits of installing a heat recovery system to pool water and pool hall heating.",
                           "co2_impact" => "HIGH" }],
                      "long_payback" =>
                        [{ "recommendation_code" => "BF2", "recommendation" => "Consider introducing or improving insulation of flat roofs.", "co2_impact" => "HIGH" },
                         { "recommendation_code" => "X5",
                           "recommendation" =>
                             "Engage experts to review overall heating strategy and propose an investment programme for upgrading and/or switching to alternative solutions.",
                           "co2_impact" => "MEDIUM" },
                         { "recommendation_code" => "AE9",
                           "recommendation" => "Consider a Combined Heating and Power (CHP) system as an alternative to conventional boilers.",
                           "co2_impact" => "HIGH" },
                         { "recommendation_code" => "AE4",
                           "recommendation" => "Consider installing building mounted photovoltaic electricity generating panels.",
                           "co2_impact" => "HIGH" }],
                      "technical_information" =>
                        { "building_environment" => "Mixed-mode with Natural Ventilation",
                          "floor_area" => 4901,
                          "renewable_sources" => "Not applicable",
                          "special_energy_uses" => "Not applicable" },
                      "site_services" =>
                        { "service_1" => { "description" => "Electricity", "quantity" => 296_820 },
                          "service_2" => { "description" => "Natural Gas", "quantity" => 786_655 },
                          "service_3" => { "description" => "Not Used", "quantity" => 0 } } }

      actual = use_case.execute(xml: dec_rr,
                                schema_type: "CEPC-7.0",
                                assessment_id: "3333-4444-5555-6666-7778")

      expect(actual).to eq(expectation)
    end
  end

  context "when loading XML from AC-CERT" do
    let(:ac_cert) { Samples.xml "CEPC-7.0", "ac-cert+rr" }

    it "parses the document in the expected format" do
      expectation = { "issue_date" => "2015-05-05",
                      "report_type" => 6,
                      "valid_until" => "2020-05-14",
                      "related_rrn" => "9999-8888-7777-6666-5554",
                      "inspection_date" => "2015-05-04",
                      "registration_date" => "2015-05-04",
                      "status" => "entered",
                      "language_code" => 1,
                      "building_complexity" => "Level 3",
                      "scheme_assessor_id" => "SCHE000111",
                      "uprn" => 876_764_383_383,
                      "address_line_1" => "Mr Blobby's Sports Academy",
                      "address_line_2" => "Mr Blobby's Academy",
                      "address_line_3" => "Blobby Custard Lane",
                      "post_town" => "POSTTOWN",
                      "postcode" => "PT4 1SK",
                      "property_type" => "Schools And Seasonal Public Buildings; Swimming Pool Centre",
                      "occupier" => "Mr Blobby's Sports Academy",
                      "calculation_tool" => "Quidos, AIRS, v2.0",
                      "equipment_owner" =>
                       { "equipment_owner_name" => "Mr Joe Blobby",
                         "telephone_number" => "07855 55555555",
                         "organisation_name" => "Mr Blobby's Sports Academy",
                         "registered_address" =>
                          { "address_line_2" => "Mr Blobby's Sports Academy",
                            "address_line_3" => "Blobby Road",
                            "address_line_4" => "Blobby Blobby",
                            "post_town" => "POSTTOWN",
                            "postcode" => "PT14 5FA" } },
                      "building_name" => "Mr Blobby's Sports Academy",
                      "f_gas_compliant_date" => "13/05/2014",
                      "ac_rated_output" => { "ac_kw_rating" => 80 },
                      "random_sampling_flag" => "Y",
                      "treated_floor_area" => 567,
                      "ac_system_metered_flag" => 1,
                      "refrigerant_charge_total" => 43,
                      "ac_sub_systems" =>
                       [{ "sub_system_number" => "VOL001/SYS001",
                          "sub_system_description" =>
                           "Mr Blobby's Sports Academy has a number of air conditioned rooms served by 11 split A/C systems covered within the scope of this report. The total air conditioned floor space is 684 M2 with a total cooling capacity of 80 KW",
                          "refrigerant_types" => %w[R407C],
                          "sub_system_age" => 9 }] }

      actual = use_case.execute(xml: ac_cert,
                                schema_type: "CEPC-7.0",
                                assessment_id: "9999-8888-7777-6666-5555")

      expect(actual).to eq(expectation)
    end
  end
end
