default: &default
  adapter: postgresql
  host: 127.0.0.1
  username: postgres
  password: mysecretpassword
  port: 5432
development:
  <<: *default
  database: epb_eav_development
test:
  adapter: postgresql
  host: 127.0.0.1
  username: postgres
  password: mysecretpassword
  port: 5432
  database: epb_eav_test