development:
  adapter: postgresql
  database: epb_eav_development
  encoding: utf8
  host: 127.0.0.1
  username: postgres
  password: <%= ENV['DOCKER_POSTGRES_PASSWORD'] %>
test:
  adapter: postgresql
  database: epb_eav_test
  encoding: utf8
  host: 127.0.0.1
  username: postgres
  password: <%= ENV['DOCKER_POSTGRES_PASSWORD'] %>
production:
  adapter: postgresql
  database: epb_eav
  encoding: utf8
  pool: 10
  url: <%= ENV['DATABASE_URL'] %>
