default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  database: epb_eav_development
  host: 127.0.0.1
  username: postgres
  password: <%= ENV['DOCKER_POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: epb_eav_test
  host: 127.0.0.1
  username: postgres
  password: <%= ENV['DOCKER_POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: epb_eav
  pool: 10
  url: <%= ENV['DATABASE_URL'] %>
