development:
  adapter: postgresql
  database: epb_eav_development
  encoding: utf8
  host: localhost
  port: 5432
  username: epbr_eav_user
  password: password

test:
  adapter: postgresql
  database: epb_eav_test
  encoding: utf8
  host: localhost
  port: 5432
  username: epbr_eav_user
  password: password
