RSpec.describe "the parser and the SAP configuration" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from SAP (SAP 16.2)" do
    let(:sap) { Samples.xml "SAP-Schema-16.2", "sap" }

    it "parses the document into the expected format" do
      expectation = { "sap_version" => 9.9,
                      "bedf_revision_number" => 333,
                      "calculation_software_name" => "NHER Plan Assessor",
                      "calculation_software_version" => 5.4,
                      "inspection_date" => "2013-02-06",
                      "report_type" => 3,
                      "completion_date" => "2013-02-06",
                      "registration_date" => "2013-02-06",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "transaction_type" => 6,
                      "seller_commission_report" => "Y",
                      "property_type" => 0,
                      "scheme_assessor_id" => 0,
                      "address_line_1" => "17, Street Terrace",
                      "post_town" => "Town",
                      "postcode" => "AA1 1AA",
                      "uprn" => 0,
                      "region_code" => 16,
                      "country_code" => "EAW",
                      "assessment_date" => "2013-02-06",
                      "renewable_heat_incentive" => { "rhi_new_dwelling" => { "space_heating" => 41_938, "water_heating" => 2876 } },
                      "walls" =>
                       [{ "description" => "Average thermal transmittance 0.17 W/m²K",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "roofs" =>
                       [{ "description" => "Average thermal transmittance 0.14 W/m²K",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "floors" =>
                       [{ "description" => "Average thermal transmittance 0.13 W/m²K",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "windows" =>
                       { "description" => "High performance glazing", "energy_efficiency_rating" => 5, "environmental_efficiency_rating" => 5 },
                      "main_heating" =>
                       [{ "description" => "Ground source heat pump, underfloor, electric",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 5 }],
                      "main_heating_controls" =>
                       [{ "description" => "Time and temperature zone control",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "secondary_heating" => { "description" => "Room heaters, wood logs", "energy_efficiency_rating" => 0, "environmental_efficiency_rating" => 0 },
                      "hot_water" => { "description" => "From main system, plus solar", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 5 },
                      "lighting" => { "description" => "Low energy lighting in all fixed outlets", "energy_efficiency_rating" => 5, "environmental_efficiency_rating" => 5 },
                      "air_tightness" => { "description" => "Air permeability 6.4 m³/h.m² (as tested)", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 4 },
                      "has_fixed_air_conditioning" => "false",
                      "has_hot_water_cylinder" => "true",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Detached house",
                      "total_floor_area" => 709,
                      "energy_rating_current" => 85,
                      "energy_rating_potential" => 85,
                      "environmental_impact_current" => 88,
                      "environmental_impact_potential" => 88,
                      "energy_consumption_current" => 63,
                      "energy_consumption_potential" => 63,
                      "co2_emissions_current" => 6.5,
                      "co2_emissions_current_per_floor_area" => 9,
                      "co2_emissions_potential" => 6.5,
                      "lighting_cost_current" => 154,
                      "lighting_cost_potential" => 154,
                      "heating_cost_current" => 2132,
                      "heating_cost_potential" => 2132,
                      "hot_water_cost_current" => 105,
                      "hot_water_cost_potential" => 105,
                      "energy_rating_average" => 60,
                      "lzc_energy_sources" => [4, 7, 10, 11],
                      "data_type" => 2,
                      "schema_version" => "LIG-16.0",
                      "built_form" => 1,
                      "living_area" => 44.4,
                      "orientation" => 0,
                      "conservatory_type" => 1,
                      "is_in_smoke_control_area" => "unknown",
                      "sap_heating" => { "water_heating_code" => 901, "water_fuel_type" => 39, "has_hot_water_cylinder" => "true", "secondary_heating_category" => 10, "secondary_heating_data_source" => 3, "secondary_heating_code" => 633, "secondary_fuel_type" => 20, "has_fixed_air_conditioning" => "false", "is_heat_pump_assisted_by_immersion" => "false", "is_secondary_heating_hetas_approved" => "false", "hot_water_store_size" => 300, "hot_water_store_heat_loss_source" => 3, "hot_water_store_insulation_type" => 1, "hot_water_store_insulation_thickness" => 80, "is_primary_pipework_insulated" => "true", "has_cylinder_thermostat" => "true", "is_cylinder_in_heated_space" => "true", "is_hot_water_separately_timed" => "true", "has_solar_panel" => "true", "solar_panel_aperture_area" => 5.26, "solar_panel_collector_type" => 3, "solar_panel_collector_data_source" => 2, "solar_panel_collector_zero_loss_efficiency" => 60, "solar_panel_collector_heat_loss_rate" => 3, "solar_panel_collector_pitch" => 3, "solar_panel_collector_orientation" => 3, "solar_panel_collector_overshading" => 1, "has_solar_powered_pump" => "false", "is_solar_store_combined_cylinder" => "true", "solar_store_volume" => 100, "main_heating_details" => [{ "main_heating_number" => 1, "main_heating_category" => 4, "main_heating_data_source" => 3, "main_heating_code" => 201, "main_fuel_type" => 39, "main_heating_control" => 2207, "heat_emitter_type" => 2, "underfloor_heat_emitter_type" => 2, "is_central_heating_pump_in_heated_space" => "true", "has_delayed_start_thermostat" => "false", "is_main_heating_hetas_approved" => "false", "load_or_weather_compensation" => 0, "main_heating_fraction" => 1 }] },
                      "sap_energy_source" => { "pv_arrays" => [{ "peak_power" => 3.6, "orientation" => 5, "pitch" => 3, "overshading" => 1 }], "wind_turbines_count" => 0, "wind_turbine_terrain_type" => 3, "fixed_lighting_outlets_count" => 40, "low_energy_fixed_lighting_outlets_count" => 40, "low_energy_fixed_lighting_outlets_percentage" => 100, "electricity_tariff" => 1 },
                      "sap_building_parts" =>
                        [{ "building_part_number" => 1,
                           "identifier" => "Main Dwelling",
                           "construction_year" => 2010,
                           "overshading" => 1,
                           "sap_openings" =>
                            [{ "name" => 1, "type" => 1, "location" => "Wall 1", "orientation" => 0, "width" => 0.91, "height" => 2.1 },
                             { "name" => 2, "type" => 2, "location" => "Wall 1", "orientation" => 0, "width" => 0.91, "height" => 2.1 },
                             { "name" => 3, "type" => 3, "location" => "Wall 4", "orientation" => 7, "width" => 3.99, "height" => 0.78 },
                             { "name" => 4, "type" => 4, "location" => "Wall 4", "orientation" => 6, "width" => 3.33, "height" => 0.97 },
                             { "name" => 5, "type" => 5, "location" => "Wall 4", "orientation" => 6, "width" => 3.17, "height" => 0.97 },
                             { "name" => 6, "type" => 6, "location" => "Wall 4", "orientation" => 6, "width" => 1.28, "height" => 0.97 },
                             { "name" => 7, "type" => 7, "location" => "Wall 4", "orientation" => 6, "width" => 2.31, "height" => 0.97 },
                             { "name" => 8, "type" => 8, "location" => "Wall 4", "orientation" => 6, "width" => 2.31, "height" => 0.97 },
                             { "name" => 9, "type" => 9, "location" => "Wall 4", "orientation" => 7, "width" => 5.86, "height" => 1.36 },
                             { "name" => 10, "type" => 10, "location" => "Wall 4", "orientation" => 7, "width" => 3.95, "height" => 1.36 },
                             { "name" => 11, "type" => 11, "location" => "Wall 1", "orientation" => 0, "width" => 1.68, "height" => 2.75 },
                             { "name" => 12, "type" => 12, "location" => "Wall 4", "orientation" => 0, "width" => 1.99, "height" => 2.2 },
                             { "name" => 13, "type" => 13, "location" => "Wall 1", "orientation" => 8, "width" => 1.24, "height" => 0.95 },
                             { "name" => 14, "type" => 14, "location" => "Wall 1", "orientation" => 2, "width" => 1.99, "height" => 0.95 },
                             { "name" => 15, "type" => 15, "location" => "Wall 4", "orientation" => 2, "width" => 2.92, "height" => 2.09 },
                             { "name" => 16, "type" => 16, "location" => "Wall 4", "orientation" => 4, "width" => 1.38, "height" => 2.09 },
                             { "name" => 17, "type" => 17, "location" => "Wall 4", "orientation" => 1, "width" => 1.36, "height" => 2.4 },
                             { "name" => 18, "type" => 18, "location" => "Wall 4", "orientation" => 3, "width" => 2.09, "height" => 2.4 },
                             { "name" => 19, "type" => 19, "location" => "Wall 4", "orientation" => 3, "width" => 1.88, "height" => 2.4 },
                             { "name" => 20, "type" => 20, "location" => "Wall 4", "orientation" => 6, "width" => 0.68, "height" => 0.99 },
                             { "name" => 21, "type" => 21, "location" => "Wall 4", "orientation" => 6, "width" => 0.68, "height" => 0.99 },
                             { "name" => 22, "type" => 22, "location" => "Wall 4", "orientation" => 6, "width" => 0.68, "height" => 0.99 },
                             { "name" => 23, "type" => 23, "location" => "Wall 4", "orientation" => 6, "width" => 0.68, "height" => 0.99 },
                             { "name" => 24, "type" => 24, "location" => "Wall 1", "orientation" => 5, "width" => 0.54, "height" => 0.99 },
                             { "name" => 25, "type" => 25, "location" => "Wall 1", "orientation" => 5, "width" => 0.54, "height" => 0.99 },
                             { "name" => 26, "type" => 26, "location" => "Wall 1", "orientation" => 7, "width" => 0.54, "height" => 0.99 },
                             { "name" => 27, "type" => 27, "location" => "Wall 1", "orientation" => 7, "width" => 0.54, "height" => 0.99 },
                             { "name" => 28, "type" => 28, "location" => "Wall 1", "orientation" => 7, "width" => 0.54, "height" => 0.99 },
                             { "name" => 29, "type" => 29, "location" => "Wall 4", "orientation" => 3, "width" => 1.45, "height" => 1.42 },
                             { "name" => 30, "type" => 30, "location" => "Wall 4", "orientation" => 3, "width" => 1.68, "height" => 1.42 },
                             { "name" => 31, "type" => 31, "location" => "Wall 4", "orientation" => 5, "width" => 1.45, "height" => 1.42 },
                             { "name" => 32, "type" => 32, "location" => "Wall 4", "orientation" => 1, "width" => 1.68, "height" => 1.42 },
                             { "name" => 33, "type" => 33, "location" => "Wall 4", "orientation" => 2, "width" => 1.35, "height" => 2.09 },
                             { "name" => 34, "type" => 34, "location" => "Wall 4", "orientation" => 2, "width" => 1.35, "height" => 2.09 },
                             { "name" => 35, "type" => 35, "location" => "Wall 1", "orientation" => 0, "width" => 3.84, "height" => 2.8 },
                             { "name" => 36, "type" => 36, "location" => "Wall 1", "orientation" => 0, "width" => 4.74, "height" => 2.8 },
                             { "name" => 37, "type" => 37, "location" => "Wall 4", "orientation" => 0, "width" => 2.81, "height" => 2.8 },
                             { "name" => 38, "type" => 38, "location" => "Wall 4", "orientation" => 0, "width" => 6.45, "height" => 2.4 },
                             { "name" => 39, "type" => 39, "location" => "Wall 4", "orientation" => 0, "width" => 3.84, "height" => 2.4 },
                             { "name" => 40, "type" => 40, "location" => "Wall 1", "orientation" => 2, "width" => 1.4, "height" => 2.76 },
                             { "name" => 41, "type" => 41, "location" => "Roof 2", "orientation" => 8, "width" => 0.6, "height" => 0.89 },
                             { "name" => 42, "type" => 42, "location" => "Roof 2", "orientation" => 4, "width" => 7.25, "height" => 0.89 },
                             { "name" => 43, "type" => 43, "location" => "Wall 1", "orientation" => 0, "width" => 1.81, "height" => 2.1 },
                             { "name" => 44, "type" => 44, "location" => "Wall 1", "orientation" => 0, "width" => 2.49, "height" => 2.1 },
                             { "name" => 45, "type" => 45, "location" => "Wall 1", "orientation" => 0, "width" => 3.08, "height" => 2.62 },
                             { "name" => 46, "type" => 46, "location" => "Wall 1", "orientation" => 2, "width" => 1.68, "height" => 1.36 },
                             { "name" => 47, "type" => 47, "location" => "Wall 4", "orientation" => 3, "width" => 1.18, "height" => 2.44 },
                             { "name" => 48, "type" => 48, "location" => "Wall 4", "orientation" => 3, "width" => 1.18, "height" => 1.23 },
                             { "name" => 49, "type" => 49, "location" => "Wall 1", "orientation" => 2, "width" => 4.27, "height" => 2.85 },
                             { "name" => 50, "type" => 50, "location" => "Wall 1", "orientation" => 2, "width" => 1.68, "height" => 4.15 },
                             { "name" => 51, "type" => 51, "location" => "Wall 4", "orientation" => 6, "width" => 1.74, "height" => 2.62 },
                             { "name" => 52, "type" => 52, "location" => "Wall 4", "orientation" => 6, "width" => 2.36, "height" => 0.38 },
                             { "name" => 53, "type" => 53, "location" => "Wall 4", "orientation" => 6, "width" => 1.5, "height" => 0.38 },
                             { "name" => 54, "type" => 54, "location" => "Wall 1", "orientation" => 6, "width" => 0.7, "height" => 0.38 },
                             { "name" => 55, "type" => 55, "location" => "Wall 1", "orientation" => 6, "width" => 0.92, "height" => 0.38 },
                             { "name" => 56, "type" => 56, "location" => "Wall 1", "orientation" => 6, "width" => 0.9, "height" => 0.38 },
                             { "name" => 57, "type" => 57, "location" => "Wall 1", "orientation" => 7, "width" => 1.18, "height" => 2.98 },
                             { "name" => 58, "type" => 58, "location" => "Wall 1", "orientation" => 3, "width" => 1.18, "height" => 2.98 },
                             { "name" => 59, "type" => 59, "location" => "Wall 4", "orientation" => 7, "width" => 0.62, "height" => 0.38 },
                             { "name" => 60, "type" => 60, "location" => "Wall 4", "orientation" => 7, "width" => 1.69, "height" => 0.38 },
                             { "name" => 61, "type" => 61, "location" => "Wall 1", "orientation" => 7, "width" => 2.38, "height" => 0.38 },
                             { "name" => 62, "type" => 62, "location" => "Wall 1", "orientation" => 7, "width" => 1.13, "height" => 0.38 },
                             { "name" => 63, "type" => 63, "location" => "Wall 1", "orientation" => 7, "width" => 0.73, "height" => 0.38 },
                             { "name" => 64, "type" => 64, "location" => "Wall 1", "orientation" => 7, "width" => 1.94, "height" => 0.38 },
                             { "name" => 65, "type" => 65, "location" => "Wall 1", "orientation" => 7, "width" => 1.39, "height" => 0.38 },
                             { "name" => 66, "type" => 66, "location" => "Wall 1", "orientation" => 7, "width" => 1.59, "height" => 0.38 },
                             { "name" => 67, "type" => 67, "location" => "Wall 1", "orientation" => 7, "width" => 1.65, "height" => 0.38 },
                             { "name" => 68, "type" => 68, "location" => "Wall 1", "orientation" => 6, "width" => 0.46, "height" => 0.54 },
                             { "name" => 69, "type" => 69, "location" => "Wall 1", "orientation" => 6, "width" => 0.46, "height" => 0.54 },
                             { "name" => 70, "type" => 70, "location" => "Wall 1", "orientation" => 8, "width" => 1.14, "height" => 1.06 },
                             { "name" => 71, "type" => 71, "location" => "Wall 1", "orientation" => 8, "width" => 1.14, "height" => 1.06 },
                             { "name" => 72, "type" => 72, "location" => "Wall 1", "orientation" => 8, "width" => 1.14, "height" => 1.06 },
                             { "name" => 73, "type" => 73, "location" => "Wall 1", "orientation" => 8, "width" => 1.14, "height" => 1.06 },
                             { "name" => 74, "type" => 74, "location" => "Wall 1", "orientation" => 4, "width" => 1.14, "height" => 1.06 },
                             { "name" => 75, "type" => 75, "location" => "Wall 1", "orientation" => 4, "width" => 1.14, "height" => 1.06 },
                             { "name" => 76, "type" => 76, "location" => "Wall 4", "orientation" => 8, "width" => 2, "height" => 1.09 },
                             { "name" => 77, "type" => 77, "location" => "Wall 4", "orientation" => 8, "width" => 2, "height" => 1.09 },
                             { "name" => 78, "type" => 78, "location" => "Wall 4", "orientation" => 6, "width" => 0.76, "height" => 0.38 },
                             { "name" => 79, "type" => 79, "location" => "Wall 4", "orientation" => 6, "width" => 0.76, "height" => 0.38 },
                             { "name" => 80, "type" => 80, "location" => "Wall 4", "orientation" => 6, "width" => 0.76, "height" => 0.38 },
                             { "name" => 81, "type" => 81, "location" => "Wall 4", "orientation" => 6, "width" => 2.57, "height" => 0.38 },
                             { "name" => 82, "type" => 82, "location" => "Wall 4", "orientation" => 6, "width" => 2.57, "height" => 0.38 },
                             { "name" => 83, "type" => 83, "location" => "Wall 1", "orientation" => 6, "width" => 0.88, "height" => 0.38 },
                             { "name" => 84, "type" => 84, "location" => "Wall 1", "orientation" => 6, "width" => 0.88, "height" => 0.38 },
                             { "name" => 85, "type" => 85, "location" => "Wall 1", "orientation" => 6, "width" => 0.88, "height" => 0.38 },
                             { "name" => 86, "type" => 86, "location" => "Wall 1", "orientation" => 6, "width" => 0.88, "height" => 0.38 },
                             { "name" => 87, "type" => 87, "location" => "Wall 4", "orientation" => 7, "width" => 1.28, "height" => 0.38 },
                             { "name" => 88, "type" => 88, "location" => "Wall 4", "orientation" => 7, "width" => 1.28, "height" => 0.38 },
                             { "name" => 89, "type" => 89, "location" => "Wall 4", "orientation" => 7, "width" => 1.28, "height" => 0.38 },
                             { "name" => 90, "type" => 90, "location" => "Wall 4", "orientation" => 7, "width" => 1.35, "height" => 0.38 },
                             { "name" => 91, "type" => 91, "location" => "Wall 4", "orientation" => 7, "width" => 1.35, "height" => 0.38 },
                             { "name" => 92, "type" => 92, "location" => "Wall 4", "orientation" => 7, "width" => 1.35, "height" => 0.38 },
                             { "name" => 93, "type" => 93, "location" => "Wall 1", "orientation" => 7, "width" => 0.55, "height" => 0.38 },
                             { "name" => 94, "type" => 94, "location" => "Wall 1", "orientation" => 7, "width" => 0.55, "height" => 0.38 },
                             { "name" => 95, "type" => 95, "location" => "Wall 1", "orientation" => 7, "width" => 0.55, "height" => 0.38 },
                             { "name" => 96, "type" => 96, "location" => "Wall 1", "orientation" => 7, "width" => 0.55, "height" => 0.38 },
                             { "name" => 97, "type" => 97, "location" => "Wall 1", "orientation" => 7, "width" => 0.55, "height" => 0.38 },
                             { "name" => 98, "type" => 98, "location" => "Wall 1", "orientation" => 7, "width" => 0.92, "height" => 0.38 },
                             { "name" => 99, "type" => 99, "location" => "Wall 1", "orientation" => 7, "width" => 0.92, "height" => 0.38 },
                             { "name" => 100, "type" => 100, "location" => "Wall 1", "orientation" => 7, "width" => 1.23, "height" => 0.38 },
                             { "name" => 101, "type" => 101, "location" => "Wall 1", "orientation" => 7, "width" => 1.23, "height" => 0.38 }],
                           "sap_roofs" => [{ "name" => "Roof 1", "description" => "Roof 1 ZINC FLAT", "roof_type" => 2, "total_roof_area" => 145, "u_value" => 0.129 }, { "name" => "Roof 2", "description" => "Roof 2 THATCH ROOF", "roof_type" => 2, "total_roof_area" => 93.03, "u_value" => 0.139 }, { "name" => "Roof 3", "description" => "Roof 3 DORMER", "roof_type" => 2, "total_roof_area" => 4.8, "u_value" => 0.19 }, { "name" => "Roof 4", "description" => "Roof 4 SLATE", "roof_type" => 2, "total_roof_area" => 157.54, "u_value" => 0.151 }],
                           "sap_floor_dimensions" => [{ "storey" => 0, "description" => "Floor 1", "floor_type" => 1, "total_floor_area" => 127.88, "storey_height" => 2.65, "heat_loss_area" => 341.2, "u_value" => 0.13 }, { "storey" => 1, "floor_type" => 3, "total_floor_area" => 213.32, "storey_height" => 2.88, "heat_loss_area" => 0, "u_value" => 0 }, { "storey" => 2, "floor_type" => 3, "total_floor_area" => 347.69, "storey_height" => 3.07, "heat_loss_area" => 0, "u_value" => 0 }, { "storey" => 3, "floor_type" => 3, "total_floor_area" => 20.45, "storey_height" => 2.3, "heat_loss_area" => 0, "u_value" => 0 }],
                           "sap_thermal_bridges" => { "thermal_bridge_code" => 1 },
                           "sap_walls" => [{ "name" => "Wall 1", "description" => "Wall 1 BRICK & FLINT", "wall_type" => 2, "total_wall_area" => 407.31, "u_value" => 0.166, "is_curtain_walling" => "false" }, { "name" => "Wall 2", "description" => "Wall 2 CONCRETE", "wall_type" => 1, "total_wall_area" => 122.42, "u_value" => 0.168, "is_curtain_walling" => "false" }, { "name" => "Wall 3", "description" => "Wall 3 INT WALL", "wall_type" => 2, "total_wall_area" => 17.33, "u_value" => 0.181, "is_curtain_walling" => "false" }, { "name" => "Wall 4", "description" => "Wall 4 TF", "wall_type" => 2, "total_wall_area" => 236.58, "u_value" => 0.158, "is_curtain_walling" => "false" }],
                           "thermal_mass_parameter" => 250 }],
                      "sap_opening_types" =>
                        [{ "name" => 1, "description" => "D7", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 2, "description" => "D12", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 3, "description" => "W27", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 4, "description" => "W28A", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 5, "description" => "W29A", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 6, "description" => "W30", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 7, "description" => "W31", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 8, "description" => "W32", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 9, "description" => "W25", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 10, "description" => "W26", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 11, "description" => "D3", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 12, "description" => "D11", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 13, "description" => "W34", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 14, "description" => "W33", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 15, "description" => "W20", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 16, "description" => "W21", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 17, "description" => "W35", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 18, "description" => "W36", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 19, "description" => "W37", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 20, "description" => "W22", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 21, "description" => "W23", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 22, "description" => "W24", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 23, "description" => "W24A", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 24, "description" => "W38", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 25, "description" => "W39", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 26, "description" => "W40", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 27, "description" => "W41", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 28, "description" => "W42", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 29, "description" => "W1A", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 30, "description" => "W2A", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 31, "description" => "W1B", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 32, "description" => "W2B", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 33, "description" => "W18", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 34, "description" => "W19", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 35, "description" => "D4", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 36, "description" => "D6", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 37, "description" => "D5", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 38, "description" => "D9", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 39, "description" => "D10", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 40, "description" => "W17", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 41, "description" => "W14", "data_source" => 2, "type" => 5, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 42, "description" => "W16", "data_source" => 2, "type" => 5, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 43, "description" => "D1", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 44, "description" => "D2", "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.4 },
                         { "name" => 45, "description" => "D8", "data_source" => 2, "type" => 1, "glazing_type" => 1, "u_value" => 1.4 },
                         { "name" => 46, "description" => "W9", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 47, "description" => "W29", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 48, "description" => "W28", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 49, "description" => "W13", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 50, "description" => "W9A", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 51, "description" => "W15", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 52, "description" => "WF", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 53, "description" => "WG", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 54, "description" => "WH", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 55, "description" => "WI", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 56, "description" => "WJ", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 57, "description" => "W30A", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 58, "description" => "W31A", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 59, "description" => "WLL", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 60, "description" => "WMM", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 61, "description" => "WAA", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 62, "description" => "WBB", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 63, "description" => "WCC", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 64, "description" => "WDD", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 65, "description" => "WO", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 66, "description" => "WP", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 67, "description" => "WQ", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 68, "description" => "W1", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 69, "description" => "W10", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 70, "description" => "W2", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 71, "description" => "W3", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 72, "description" => "W4", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 73, "description" => "W5", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 74, "description" => "W6", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 75, "description" => "W7", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 76, "description" => "W11", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 77, "description" => "W12", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 78, "description" => "WA", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 79, "description" => "WB", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 80, "description" => "WC", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 81, "description" => "WD", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 82, "description" => "WE", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 83, "description" => "WK", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 84, "description" => "WL", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 85, "description" => "WM", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 86, "description" => "WN", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 87, "description" => "WFF", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 88, "description" => "WGG", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 89, "description" => "WHH", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 90, "description" => "WII", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 91, "description" => "WJJ", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 92, "description" => "WKK", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 93, "description" => "WR", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 94, "description" => "WS", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 95, "description" => "WT", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 96, "description" => "WU", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 97, "description" => "WV", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 98, "description" => "WW", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 99, "description" => "WX", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 100, "description" => "WY", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 },
                         { "name" => 101, "description" => "WZ", "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 }],
                      "sap_ventilation" => { "open_fireplaces_count" => 0, "open_flues_count" => 0, "flueless_gas_fires_count" => 0, "pressure_test" => 1, "air_permeability" => 6.373, "sheltered_sides_count" => 0, "ventilation_type" => 1, "extract_fans_count" => 9, "psv_count" => 0 } }
      expect(use_case.execute(xml: sap,
                              schema_type: "SAP-Schema-16.2",
                              assessment_id: "1234-1234-1234-1234-1234")).to eq expectation
    end
  end

  context "when loading XML from rdSAP (SAP 16.2)" do
    let(:rdsap) { Samples.xml "SAP-Schema-16.2", "rdsap" }

    it "parses the document into the expected format" do
      expectation = {
        "sap_version" => 9.91,
        "bedf_revision_number" => 340,
        "calculation_software_name" => "Stroma RdSAP Software",
        "calculation_software_version" => "1.4.1.0",
        "inspection_date" => "2013-06-27",
        "report_type" => 2,
        "completion_date" => "2013-07-12",
        "registration_date" => "2013-07-12",
        "status" => "entered",
        "language_code" => 1,
        "restricted_access" => 0,
        "tenure" => 1,
        "transaction_type" => 5,
        "seller_commission_report" => "Y",
        "property_type" => 0,
        "scheme_assessor_id" => 0,
        "address_line_1" => "11, Some Close",
        "address_line_2" => "Long Itchington",
        "post_town" => "Town",
        "postcode" => "AA1 1AA",
        "uprn" => 0,
        "region_code" => 3,
        "country_code" => "EAW",
        "walls" => [{ "description" => "Cavity wall, as built, no insulation (assumed)", "energy_efficiency_rating" => 2, "environmental_efficiency_rating" => 2 }, { "description" => "Cavity wall, as built, insulated (assumed)", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 4 }],
        "roofs" => [{ "description" => "Pitched, 75 mm loft insulation", "energy_efficiency_rating" => 3, "environmental_efficiency_rating" => 3 }],
        "floors" => [{ "description" => "Suspended, no insulation (assumed)", "energy_efficiency_rating" => 0, "environmental_efficiency_rating" => 0 }, { "description" => "To unheated space, limited insulation (assumed)", "energy_efficiency_rating" => 0, "environmental_efficiency_rating" => 0 }],
        "windows" => [{ "description" => "Partial double glazing", "energy_efficiency_rating" => 2, "environmental_efficiency_rating" => 2 }],
        "main_heating" => [{ "description" => "Boiler and radiators, mains gas", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 4 }, { "description" => "Boiler and radiators, mains gas", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 4 }],
        "main_heating_controls" => [{ "description" => "Programmer, room thermostat and TRVs", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 4 }],
        "hot_water" => { "description" => "From main system", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 4 },
        "lighting" => { "description" => "Low energy lighting in 13% of fixed outlets", "energy_efficiency_rating" => 2, "environmental_efficiency_rating" => 2 },
        "secondary_heating" => { "description" => "Room heaters, coal", "energy_efficiency_rating" => 0, "environmental_efficiency_rating" => 0 },
        "has_hot_water_cylinder" => "true",
        "has_heated_separate_conservatory" => "false",
        "dwelling_type" => "Detached house",
        "total_floor_area" => 1563,
        "has_fixed_air_conditioning" => "false",
        "energy_rating_average" => 60,
        "energy_rating_current" => 52,
        "energy_rating_potential" => 69,
        "environmental_impact_current" => 40,
        "environmental_impact_potential" => 58,
        "energy_consumption_current" => 239,
        "energy_consumption_potential" => 153,
        "co2_emissions_current" => 78,
        "co2_emissions_potential" => 51,
        "co2_emissions_current_per_floor_area" => 50,
        "lighting_cost_current" => { "currency" => "GBP", "value" => 635 },
        "lighting_cost_potential" => { "currency" => "GBP", "value" => 344 },
        "heating_cost_current" => { "currency" => "GBP", "value" => 13_144 },
        "heating_cost_potential" => { "currency" => "GBP", "value" => 8582 },
        "hot_water_cost_current" => { "currency" => "GBP", "value" => 188 },
        "hot_water_cost_potential" => { "currency" => "GBP", "value" => 151 },
        "suggested_improvements" => [{ "sequence" => 1, "improvement_category" => 5, "improvement_type" => "A", "improvement_details" => { "improvement_number" => 5 }, "typical_saving" => { "currency" => "GBP", "value" => 637.67 }, "indicative_cost" => "£100  -  £350", "energy_performance_rating" => 55, "environmental_impact_rating" => 42 }, { "sequence" => 2, "improvement_category" => 5, "improvement_type" => "B", "improvement_details" => { "improvement_number" => 6 }, "typical_saving" => { "currency" => "GBP", "value" => 1224.21 }, "indicative_cost" => "£500  -  £1,500", "energy_performance_rating" => 59, "environmental_impact_rating" => 46 }, { "sequence" => 3, "improvement_category" => 5, "improvement_type" => "W", "improvement_details" => { "improvement_number" => 47 }, "typical_saving" => { "currency" => "GBP", "value" => 476.28 }, "indicative_cost" => "£800  -  £1,200", "energy_performance_rating" => 60, "environmental_impact_rating" => 48 }, { "sequence" => 4, "improvement_category" => 5, "improvement_type" => "D", "improvement_details" => { "improvement_number" => 10 }, "typical_saving" => { "currency" => "GBP", "value" => 787.42 }, "indicative_cost" => "£80  -  £120", "energy_performance_rating" => 63, "environmental_impact_rating" => 51 }, { "sequence" => 5, "improvement_category" => 5, "improvement_type" => "E", "improvement_details" => { "improvement_number" => 35 }, "typical_saving" => { "currency" => "GBP", "value" => 234.75 }, "indicative_cost" => "£305", "energy_performance_rating" => 64, "environmental_impact_rating" => 51 }, { "sequence" => 6, "improvement_category" => 5, "improvement_type" => "I", "improvement_details" => { "improvement_number" => 20 }, "typical_saving" => { "currency" => "GBP", "value" => 1219.36 }, "indicative_cost" => "£2,200  -  £3,000", "energy_performance_rating" => 68, "environmental_impact_rating" => 56 }, { "sequence" => 7, "improvement_category" => 5, "improvement_type" => "O", "improvement_details" => { "improvement_number" => 8 }, "typical_saving" => { "currency" => "GBP", "value" => 310.6 }, "indicative_cost" => "£3,300  -  £6,500", "energy_performance_rating" => 69, "environmental_impact_rating" => 58 }],
        "renewable_heat_incentive" => { "space_heating_existing_dwelling" => 207_769, "impact_of_loft_insulation" => -12_585, "impact_of_cavity_insulation" => -21_982, "water_heating" => 3640 },
        "addendum" => { "cavity_fill_recommended" => "true" },
        "schema_version" => "LIG-16.1",
        "built_form" => 1,
        "extensions_count" => 2,
        "multiple_glazing_type" => "ND",
        "glazed_area" => 4,
        "door_count" => 4,
        "insulated_door_count" => 0,
        "percent_draughtproofed" => 0,
        "habitable_room_count" => 15,
        "heated_room_count" => 15,
        "fixed_lighting_outlets_count" => 70,
        "low_energy_fixed_lighting_outlets_count" => 9,
        "low_energy_lighting" => 13,
        "measurement_type" => 1,
        "mechanical_ventilation" => 2,
        "open_fireplaces_count" => 0,
        "solar_water_heating" => "N",
        "conservatory_type" => 2,
        "sap_building_parts" => [{ "building_part_number" => 1, "identifier" => "Main Dwelling", "construction_age_band" => "C", "wall_thickness_measured" => "Y", "wall_thickness" => 320, "wall_dry_lined" => "N", "wall_construction" => 4, "wall_insulation_type" => 4, "roof_construction" => 4, "roof_insulation_location" => 2, "roof_insulation_thickness" => "75mm", "sap_floor_dimensions" => [{ "floor" => 0, "floor_construction" => 2, "floor_insulation" => 1, "heat_loss_perimeter" => 96.43, "total_floor_area" => 668.41, "room_height" => 2.52 }, { "floor" => 1, "heat_loss_perimeter" => 106.57, "total_floor_area" => 691.43, "room_height" => 2.87 }], "floor_heat_loss" => 7 }, { "building_part_number" => 2, "identifier" => "Extension 1", "construction_age_band" => "H", "wall_thickness_measured" => "Y", "wall_thickness" => 500, "wall_dry_lined" => "N", "wall_construction" => 4, "wall_insulation_type" => 4, "roof_construction" => 5, "roof_insulation_location" => 2, "roof_insulation_thickness" => "75mm", "sap_floor_dimensions" => [{ "floor" => 0, "floor_construction" => 1, "floor_insulation" => 1, "heat_loss_perimeter" => 34.27, "total_floor_area" => 82.03, "room_height" => 2.54 }], "floor_heat_loss" => 7 }, { "building_part_number" => 3, "identifier" => "Extension 2", "construction_age_band" => "H", "wall_thickness_measured" => "Y", "wall_thickness" => 280, "wall_dry_lined" => "N", "wall_construction" => 4, "wall_insulation_type" => 4, "roof_construction" => 4, "roof_insulation_location" => 2, "roof_insulation_thickness" => "75mm", "sap_floor_dimensions" => [{ "floor" => 0, "floor_construction" => 2, "floor_insulation" => 1, "heat_loss_perimeter" => 37.71, "total_floor_area" => 121.31, "room_height" => 3.21 }], "floor_heat_loss" => 2 }],
        "sap_windows" =>
          [{ "window_location" => 2, "window_area" => 1, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 2, "window_area" => 1, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 2, "window_area" => 1, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 2, "window_area" => 1, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 2, "window_area" => 1, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 1 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 1 },
           { "window_location" => 2, "window_area" => 1, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 2, "window_area" => 1, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 2, "window_area" => 1, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 2, "window_area" => 1, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 2, "window_area" => 2, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 2, "window_area" => 2, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 2, "window_area" => 2, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 2, "window_area" => 2, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 2, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 4, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 4, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 4, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 3, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 0, "window_area" => 5, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 0, "window_area" => 5, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 0, "window_area" => 1, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 0, "window_area" => 2, "glazing_type" => 3, "window_type" => 1, "u_value" => 3.1, "solar_transmittance" => 0.76, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 3, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 3, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 3, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 8, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 3, "glazing_type" => 5, "window_type" => 1, "u_value" => 4.8, "solar_transmittance" => 0.85, "data_source" => 2, "orientation" => 5 },
           { "window_location" => 0, "window_area" => 2, "glazing_type" => 2, "window_type" => 1, "u_value" => 2, "solar_transmittance" => 0.72, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 0, "window_area" => 3, "glazing_type" => 2, "window_type" => 1, "u_value" => 2, "solar_transmittance" => 0.72, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 0, "window_area" => 3, "glazing_type" => 2, "window_type" => 1, "u_value" => 2, "solar_transmittance" => 0.72, "data_source" => 2, "orientation" => 3 },
           { "window_location" => 0, "window_area" => 6, "glazing_type" => 2, "window_type" => 1, "u_value" => 2, "solar_transmittance" => 0.72, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 8, "glazing_type" => 2, "window_type" => 1, "u_value" => 2, "solar_transmittance" => 0.72, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 8, "glazing_type" => 2, "window_type" => 1, "u_value" => 2, "solar_transmittance" => 0.72, "data_source" => 2, "orientation" => 7 },
           { "window_location" => 0, "window_area" => 9, "glazing_type" => 2, "window_type" => 1, "u_value" => 2, "solar_transmittance" => 0.72, "data_source" => 2, "orientation" => 5 }],
        "sap_heating" => { "main_heating_details" => [{ "main_heating_number" => 1, "main_heating_category" => 2, "main_heating_fraction" => 0.5, "main_heating_data_source" => 2, "sap_main_heating_code" => 101, "main_fuel_type" => 26, "main_heating_control" => 2106, "boiler_flue_type" => 2, "fan_flue_present" => "N", "heat_emitter_type" => 1, "has_fghrs" => "N" }, { "main_heating_number" => 2, "main_heating_category" => 2, "main_heating_fraction" => 0.5, "main_heating_data_source" => 2, "sap_main_heating_code" => 101, "main_fuel_type" => 26, "main_heating_control" => 2106, "boiler_flue_type" => 2, "fan_flue_present" => "Y", "heat_emitter_type" => 1, "has_fghrs" => "N" }], "water_heating_code" => 901, "water_heating_fuel" => 26, "secondary_heating_type" => 631, "secondary_fuel_type" => 33, "cylinder_size" => 4, "cylinder_insulation_type" => 1, "cylinder_insulation_thickness" => 50, "cylinder_thermostat" => "Y", "has_fixed_air_conditioning" => "false", "wwhrs" => { "rooms_with_bath_and_or_shower" => 3, "rooms_with_mixer_shower_no_bath" => 0, "rooms_with_bath_and_mixer_shower" => 3 } },
        "sap_energy_source" => { "meter_type" => 1, "main_gas" => "Y", "wind_turbines_count" => 0, "wind_turbines_terrain_type" => 3, "photovoltaic_supply" => { "percent_roof_area" => 0 } },
      }
      expect(use_case.execute(xml: rdsap,
                              schema_type: "SAP-Schema-16.2",
                              assessment_id: "1234-1234-1234-1234-1234")).to eq expectation
    end
  end
end
