RSpec.describe "the parser and the SAP configuration" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from RdSAP (SAP NI 14.0)" do
    let(:rdsap) { Samples.xml "SAP-Schema-14.0", "rdsap" }

    it "parses the document into the expected format" do
      expectation = { "calculation_software_name" => "RdSAP Software",
                      "calculation_software_version" => "1.4.1.0",
                      "sap_version" => 9.83,
                      "bedf_revision_number" => 353,
                      "inspection_date" => "2020-05-04",
                      "report_type" => 2,
                      "completion_date" => "2020-05-04",
                      "registration_date" => "2020-05-04",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "transaction_type" => 5,
                      "seller_commission_report" => "Y",
                      "property_type" => 3,
                      "scheme_assessor_id" => "SPEC000000",
                      "address_line_1" => "1 Some Street",
                      "address_line_2" => "Some Area",
                      "address_line_3" => "Some County",
                      "post_town" => "Whitbury",
                      "postcode" => "SW1A 2AA",
                      "uprn" => 0,
                      "region_code" => 18,
                      "country_code" => "EAW",
                      "walls" => [{ "energy_efficiency_rating" => 0, "description" => "Brick walls", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "Brick walls", "environmental_efficiency_rating" => 0 }],
                      "roofs" => [{ "energy_efficiency_rating" => 0, "description" => "Slate roof", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "slate roof", "environmental_efficiency_rating" => 0 }],
                      "floors" => [{ "energy_efficiency_rating" => 0, "description" => "Tiled floor", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "Tiled floor", "environmental_efficiency_rating" => 0 }],
                      "windows" => [{ "energy_efficiency_rating" => 0, "description" => "Glass window", "environmental_efficiency_rating" => 0 }],
                      "main_heating" => [{ "energy_efficiency_rating" => 0, "description" => "Gas boiler", "environmental_efficiency_rating" => 0 }],
                      "main_heating_controls" => [{ "energy_efficiency_rating" => 0, "description" => "Thermostat", "environmental_efficiency_rating" => 0 }],
                      "hot_water" => { "energy_efficiency_rating" => 0, "description" => "Gas boiler", "environmental_efficiency_rating" => 0 },
                      "lighting" => { "energy_efficiency_rating" => 0, "description" => "Energy saving bulbs", "environmental_efficiency_rating" => 0 },
                      "secondary_heating" => { "energy_efficiency_rating" => 0, "description" => "Electric heater", "environmental_efficiency_rating" => 0 },
                      "has_hot_water_cylinder" => "false",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Mid-terrace house",
                      "total_floor_area" => 69,
                      "energy_rating_current" => 50,
                      "energy_rating_potential" => 72,
                      "environmental_impact_current" => 52,
                      "environmental_impact_potential" => 70,
                      "energy_consumption_current" => 230,
                      "energy_consumption_potential" => 88,
                      "co2_emissions_current" => 2.4,
                      "co2_emissions_potential" => 1.4,
                      "co2_emissions_current_per_floor_area" => 56,
                      "lighting_cost_current" => 123.45,
                      "lighting_cost_potential" => 84.23,
                      "heating_cost_current" => 365.98,
                      "heating_cost_potential" => 250.34,
                      "hot_water_cost_current" => 200.4,
                      "hot_water_cost_potential" => 180.43,
                      "suggested_improvements" => [{ "sequence" => 1, "improvement_category" => 1, "improvement_type" => "A", "typical_saving" => 360, "energy_performance_rating" => 50, "environmental_impact_rating" => 50, "improvement_details" => { "improvement_number" => 5 } }, { "sequence" => 2, "improvement_category" => 2, "improvement_type" => "B", "typical_saving" => 99, "energy_performance_rating" => 60, "environmental_impact_rating" => 64, "improvement_details" => { "improvement_texts" => { "improvement_description" => "Improvement desc" } } }],
                      "addendum" => { "addendum_numbers" => [1] },
                      "schema_version" => "LIG-16.1",
                      "built_form" => 1,
                      "multiple_glazed_proportion" => 65,
                      "multiple_glazing_type" => 2,
                      "extensions_count" => 0,
                      "glazed_area" => 1,
                      "habitable_room_count" => 4,
                      "heated_room_count" => 4,
                      "low_energy_lighting" => 90,
                      "measurement_type" => 1,
                      "open_fireplaces_count" => 0,
                      "photovoltaic_supply" => 0,
                      "solar_water_heating" => "N",
                      "mechanical_ventilation" => 0,
                      "conservatory_type" => 1,
                      "sap_building_parts" => [{ "building_part_number" => 1, "identifier" => "Main Dwelling", "construction_age_band" => "A", "wall_construction" => 1, "wall_insulation_type" => 4, "roof_construction" => 4, "roof_insulation_location" => 4, "roof_insulation_thickness" => "NI", "sap_floor_dimensions" => [{ "floor" => 0, "floor_construction" => 1, "floor_insulation" => 1, "heat_loss_perimeter" => 13.28, "total_floor_area" => 31.26, "room_height" => 2.45 }, { "floor" => 1, "heat_loss_perimeter" => 13.28, "total_floor_area" => 31.26, "room_height" => 2.32 }], "sap_room_in_roof" => { "floor_area" => 18.3, "construction_age_band" => "A", "insulation" => 0 } }, { "building_part_number" => 2, "identifier" => "Extension 1", "construction_age_band" => "A", "wall_construction" => 3, "wall_insulation_type" => 4, "roof_construction" => 5, "roof_insulation_location" => 4, "roof_insulation_thickness" => "NI", "sap_floor_dimensions" => [{ "floor" => 0, "floor_construction" => 1, "floor_insulation" => 1, "heat_loss_perimeter" => 9.29, "total_floor_area" => 8.47, "room_height" => 2.45 }, { "floor" => 1, "heat_loss_perimeter" => 9.29, "total_floor_area" => 8.47, "room_height" => 2.32 }] }],
                      "sap_heating" => { "main_heating_category" => 7, "secondary_fuel_type" => 10, "main_fuel_type" => 10, "water_heating_fuel" => 10, "main_heating_control" => 2401, "secondary_heating_type" => 693, "water_heating_code" => 903, "immersion_heating_type" => 2, "cylinder_size" => 3, "cylinder_insulation_type" => 2, "cylinder_insulation_thickness" => 50, "main_heating_data_source" => 2, "sap_main_heating_code" => 402, "heat_emitter_type" => 0 },
                      "sap_energy_source" => { "meter_type" => 2, "main_gas" => "Y", "wind_turbines_count" => 0, "wind_turbines_terrain_type" => 2 },
                      "sap_flat_details" => { "flat_location" => 1, "storey_count" => 3, "top_storey" => "Y", "heat_loss_corridor" => 0, "floor_heat_loss" => 3 } }

      expect(use_case.execute(xml: rdsap,
                              schema_type: "SAP-Schema-NI-14.0",
                              assessment_id: "4321-4321-4321-4321-4321")).to eq expectation
    end
  end

  context "when loading XML from SAP (SAP NI 14.0)" do
    let(:sap) { Samples.xml "SAP-Schema-NI-14.0", "sap" }

    it "parses the document into the expected format" do
      expectation = { "sap_version" => 9.83,
                      "bedf_revision_number" => 353,
                      "calculation_software_name" => "NHER Plan Assessor",
                      "calculation_software_version" => 5.4,
                      "inspection_date" => "2020-05-04",
                      "report_type" => 3,
                      "completion_date" => "2020-05-04",
                      "registration_date" => "2020-05-04",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "transaction_type" => 1,
                      "seller_commission_report" => "Y",
                      "property_type" => 2,
                      "scheme_assessor_id" => "SPEC000000",
                      "address_line_1" => "1 Some Street",
                      "address_line_2" => "Some Area",
                      "address_line_3" => "Some County",
                      "post_town" => "Whitbury",
                      "postcode" => "BT4 3SR",
                      "uprn" => 0,
                      "region_code" => 2,
                      "country_code" => "NIR",
                      "assessment_date" => "2014-02-12",
                      "walls" => [{ "energy_efficiency_rating" => 0, "description" => "Brick walls", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "Brick walls", "environmental_efficiency_rating" => 0 }],
                      "roofs" => [{ "energy_efficiency_rating" => 0, "description" => "Slate roof", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "slate roof", "environmental_efficiency_rating" => 0 }],
                      "floors" => [{ "energy_efficiency_rating" => 0, "description" => "Tiled floor", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "Tiled floor", "environmental_efficiency_rating" => 0 }],
                      "windows" => { "energy_efficiency_rating" => 0, "description" => "Glass window", "environmental_efficiency_rating" => 0 },
                      "main_heating" => [{ "energy_efficiency_rating" => 0, "description" => "Gas boiler", "environmental_efficiency_rating" => 0 }],
                      "main_heating_controls" => [{ "energy_efficiency_rating" => 0, "description" => "Thermostat", "environmental_efficiency_rating" => 0 }],
                      "secondary_heating" => { "energy_efficiency_rating" => 0, "description" => "Electric heater", "environmental_efficiency_rating" => 0 },
                      "hot_water" => { "energy_efficiency_rating" => 0, "description" => "Gas boiler", "environmental_efficiency_rating" => 0 },
                      "lighting" => { "energy_efficiency_rating" => 0, "description" => "Energy saving bulbs", "environmental_efficiency_rating" => 0 },
                      "air_tightness" => { "energy_efficiency_rating" => 0, "description" => "Draft Exclusion", "environmental_efficiency_rating" => 0 },
                      "dwelling_type" => "Mid-terrace house",
                      "total_floor_area" => 69,
                      "is_zero_carbon_home" => "true",
                      "energy_rating_current" => 50,
                      "energy_rating_potential" => 72,
                      "environmental_impact_current" => 52,
                      "environmental_impact_potential" => 93,
                      "energy_consumption_current" => 230,
                      "energy_consumption_potential" => 88,
                      "co2_emissions_current" => 2.4,
                      "co2_emissions_current_per_floor_area" => 20,
                      "co2_emissions_potential" => 1.4,
                      "lighting_cost_current" => 123.45,
                      "lighting_cost_potential" => 84.23,
                      "heating_cost_current" => 365.98,
                      "heating_cost_potential" => 250.34,
                      "hot_water_cost_current" => 200.4,
                      "hot_water_cost_potential" => 180.43,
                      "suggested_improvements" => [{ "sequence" => 1, "improvement_category" => 1, "improvement_type" => "A", "typical_saving" => 360, "energy_performance_rating" => 50, "environmental_impact_rating" => 50, "improvement_details" => { "improvement_number" => 5 } }, { "sequence" => 2, "improvement_category" => 2, "improvement_type" => "B", "typical_saving" => 99, "energy_performance_rating" => 60, "environmental_impact_rating" => 64, "improvement_details" => { "improvement_number" => 1 } }],
                      "lzc_energy_sources" => [11],
                      "data_type" => 2,
                      "schema_version" => "LIG-16.0",
                      "built_form" => 1,
                      "living_area" => 24.78,
                      "orientation" => 0,
                      "conservatory_type" => 1,
                      "is_in_smoke_control_area" => "unknown",
                      "sap_heating" => { "water_heating_code" => 901, "water_fuel_type" => 1, "has_hot_water_cylinder" => "false", "secondary_heating_category" => 1, "thermal_store" => 1, "has_fixed_air_conditioning" => "false", "has_solar_panel" => "false", "main_heating_category" => 2, "main_heating_data_source" => 1, "boiler_index_number" => 16_685, "main_heating_control" => 2006, "main_fuel_type" => 36 },
                      "sap_energy_source" => { "pv_peak_power" => 5, "wind_turbines_count" => 0, "wind_turbine_terrain_type" => 1, "fixed_lighting_outlets_count" => 8, "low_energy_fixed_lighting_outlets_count" => 8, "low_energy_fixed_lighting_outlets_percentage" => 100, "electricity_tariff" => 1 },
                      "sap_building_parts" => [{ "building_part_number" => 1, "identifier" => "Main Dwelling", "construction_year" => 1750, "overshading" => 2, "sap_openings" => [{ "name" => 1, "type" => 1, "location" => "Wall 1", "orientation" => 7, "width" => 1.3, "height" => 1.2 }, { "name" => 3, "type" => 1, "location" => "Wall 1", "orientation" => 7, "width" => 1.3, "height" => 1.2 }, { "name" => 4, "type" => 4, "location" => "Wall 1", "orientation" => 7, "width" => 2.2, "height" => 2.1 }, { "name" => 2, "type" => 1, "location" => "Wall 1", "orientation" => 3, "width" => 0.92, "height" => 1.05 }, { "name" => 6, "type" => 1, "location" => "Wall 1", "orientation" => 3, "width" => 0.92, "height" => 1.05 }, { "name" => 7, "type" => 1, "location" => "Wall 1", "orientation" => 3, "width" => 0.92, "height" => 1.05 }, { "name" => 8, "type" => 8, "location" => "Wall 2", "orientation" => 0, "width" => 0.92, "height" => 2.1 }], "sap_floor_dimensions" => [{ "storey" => 1, "description" => "Exposed Floor", "floor_type" => 2, "total_floor_area" => 69.64, "storey_height" => 2.4, "heat_loss_area" => 3.67, "u_value" => 0.23 }], "sap_thermal_bridges" => { "thermal_bridge_code" => 1 } }],
                      "sap_opening_types" => [{ "name" => 1, "data_source" => 4, "type" => 4, "glazing_type" => 11, "solar_transmittance" => 0.33, "u_value" => 0.86 }, { "name" => 4, "data_source" => 2, "type" => 4, "glazing_type" => 6, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.4 }, { "name" => 8, "data_source" => 2, "type" => 1, "glazing_type" => 1, "u_value" => 0.87 }],
                      "sap_flat_details" => { "level" => 1 } }

      expect(use_case.execute(xml: sap,
                              schema_type: "SAP-Schema-NI-14.0",
                              assessment_id: "1234-1234-1234-1234-1234")).to eq expectation
    end
  end
end
