RSpec.describe "the parser and the SAP configuration" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from RdSAP (SAP 10.2)" do
    let(:rdsap) { Samples.xml "SAP-Schema-10.2", "rdsap" }

    it "parses the document into the expected format" do
      expectation = { "inspection_date" => "2020-05-04",
                      "report_type" => 2,
                      "completion_date" => "2020-05-04",
                      "registration_date" => "2020-05-04",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "seller_commission_report" => "Y",
                      "property_type" => 3,
                      "scheme_assessor_id" => "SPEC000000",
                      "address_line_1" => "1 Some Street",
                      "address_line_2" => "Some Area",
                      "address_line_3" => "Some County",
                      "post_town" => "Whitbury",
                      "postcode" => "SW1A 2AA",
                      "uprn" => 0,
                      "walls" => [{ "energy_efficiency_rating" => 0, "description" => "Brick walls", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "Brick walls", "environmental_efficiency_rating" => 0 }],
                      "roofs" => [{ "energy_efficiency_rating" => 0, "description" => "Slate roof", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "slate roof", "environmental_efficiency_rating" => 0 }],
                      "floors" => [{ "energy_efficiency_rating" => 0, "description" => "Tiled floor", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "Tiled floor", "environmental_efficiency_rating" => 0 }],
                      "windows" => [{ "energy_efficiency_rating" => 0, "description" => "Glass window", "environmental_efficiency_rating" => 0 }],
                      "main_heating" => [{ "energy_efficiency_rating" => 0, "description" => "Gas boiler", "environmental_efficiency_rating" => 0 }],
                      "main_heating_controls" => [{ "energy_efficiency_rating" => 0, "description" => "Thermostat", "environmental_efficiency_rating" => 0 }],
                      "hot_water" => { "energy_efficiency_rating" => 0, "description" => "Gas boiler", "environmental_efficiency_rating" => 0 },
                      "lighting" => { "energy_efficiency_rating" => 0, "description" => "Energy saving bulbs", "environmental_efficiency_rating" => 0 },
                      "secondary_heating" => { "energy_efficiency_rating" => 0, "description" => "Electric heater", "environmental_efficiency_rating" => 0 },
                      "energy_rating_current" => 50,
                      "energy_rating_potential" => 72,
                      "environmental_impact_current" => 52,
                      "environmental_impact_potential" => 70,
                      "energy_consumption_current" => 230,
                      "energy_consumption_potential" => 88,
                      "co2_emissions_current" => 2.4,
                      "co2_emissions_potential" => 1.4,
                      "lighting_cost_current" => 123.45,
                      "lighting_cost_potential" => 84.23,
                      "heating_cost_current" => 365.98,
                      "heating_cost_potential" => 250.34,
                      "hot_water_cost_current" => 200.4,
                      "hot_water_cost_potential" => 180.43,
                      "suggested_improvements" => [{ "sequence" => 1, "improvement_category" => 1, "typical_saving" => 360, "energy_performance_rating" => 50, "environmental_impact_rating" => 50 }, { "sequence" => 2, "improvement_category" => 2, "typical_saving" => 99, "energy_performance_rating" => 60, "environmental_impact_rating" => 64, "improvement_description" => "Improvement desc" }],
                      "built_form" => 1,
                      "extensions_count" => 0,
                      "glazed_area" => 1,
                      "habitable_room_count" => 4,
                      "heated_room_count" => 4,
                      "low_energy_lighting" => 90,
                      "measurement_type" => 1,
                      "open_fireplaces_count" => 0,
                      "photovoltaic_supply" => 0,
                      "double_glazed_proportion" => 0,
                      "double_glazing_installed" => 2,
                      "mechanical_ventilation" => 0,
                      "solar_water_heating" => "N",
                      "sap_building_parts" => [{ "construction_year" => "C", "identifier" => "Main", "roof_construction" => 2, "roof_insulation_location" => 2, "roof_insulation_thickness" => "NI", "sap_floor_dimensions" => [{ "floor" => 0, "heat_loss_perimeter" => 13.28, "room_height" => 2.45, "total_floor_area" => 50.26 }, { "floor" => 1, "heat_loss_perimeter" => 13.28, "room_height" => 2.32, "total_floor_area" => 31.26 }], "wall_construction" => 1, "wall_insulation_type" => 4 }, { "construction_year" => "C", "identifier" => "Extension 1", "roof_construction" => 3, "roof_insulation_location" => 2, "roof_insulation_thickness" => "NI", "sap_floor_dimensions" => [{ "floor" => 0, "heat_loss_perimeter" => 9.29, "room_height" => 2.45, "total_floor_area" => 8.47 }, { "floor" => 1, "heat_loss_perimeter" => 9.29, "room_height" => 2.32, "total_floor_area" => 8.47 }], "wall_construction" => 3, "wall_insulation_type" => 4 }],
                      "sap_heating" => { "secondary_fuel_type" => 10, "main_fuel_type" => 10, "water_heating_fuel" => 10, "main_heating_control" => 2401, "secondary_heating_type" => 693, "water_heating_code" => 903, "immersion_heating_type" => 2, "cylinder_size" => 3, "cylinder_insulation_type" => 2, "cylinder_insulation_thickness" => 50, "cylinder_thermostat" => "Y", "sap_main_heating_code" => 402, "heat_emitter_type" => 0, "data_source" => 1 },
                      "sap_energy_source" => { "meter_type" => 2, "main_gas" => "Y" },
                      "sap_flat_details" => { "flat_location" => 1, "storey_count" => 3, "top_storey" => "Y", "heat_loss_corridor" => 0, "floor_heat_loss" => 3 } }

      expect(use_case.execute(xml: rdsap,
                              schema_type: "SAP-Schema-10.2",
                              assessment_id: "4321-4321-4321-4321-4321")).to eq expectation
    end
  end
end
