RSpec.describe "the parser and the SAP configuration" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from RdSAP (SAP 16.1)" do
    let(:rdsap) { Samples.xml "SAP-Schema-16.1", "rdsap" }

    it "parses the document into the expected format" do
      expectation = { "sap_version" => 9.91,
                      "bedf_revision_number" => 333,
                      "calculation_software_name" => "Northgate RDSAP",
                      "calculation_software_version" => "6.2.0.6",
                      "inspection_date" => "2013-01-09",
                      "report_type" => 2,
                      "completion_date" => "2013-01-13",
                      "registration_date" => "2013-01-13",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "transaction_type" => 8,
                      "tenure" => 2,
                      "seller_commission_report" => "Y",
                      "property_type" => 0,
                      "scheme_assessor_id" => 0,
                      "address_line_1" => "15, What the Dickens Road",
                      "post_town" => "Town",
                      "postcode" => "AA1 1AA",
                      "uprn" => 0,
                      "region_code" => 14,
                      "country_code" => "EAW",
                      "walls" =>
                       [{ "description" => "Cavity wall, filled cavity",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 },
                        { "description" => "System built, as built, no insulation (assumed)",
                          "energy_efficiency_rating" => 1,
                          "environmental_efficiency_rating" => 1 },
                        { "description" => "Solid brick, as built, no insulation (assumed)",
                          "energy_efficiency_rating" => 1,
                          "environmental_efficiency_rating" => 1 }],
                      "roofs" =>
                       [{ "description" => "Pitched, 300+ mm loft insulation",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "floors" =>
                       [{ "description" => "Suspended, no insulation (assumed)",
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 }],
                      "windows" =>
                       [{ "description" => "Fully double glazed", "energy_efficiency_rating" => 3, "environmental_efficiency_rating" => 3 }],
                      "main_heating" =>
                       [{ "description" => "Boiler and radiators, mains gas",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "main_heating_controls" =>
                       [{ "description" => "Room thermostat only", "energy_efficiency_rating" => 2, "environmental_efficiency_rating" => 2 }],
                      "hot_water" =>
                       { "description" => "From main system", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 4 },
                      "lighting" =>
                       { "description" => "Low energy lighting in 36% of fixed outlets",
                         "energy_efficiency_rating" => 3,
                         "environmental_efficiency_rating" => 3 },
                      "secondary_heating" => { "description" => "None", "energy_efficiency_rating" => 0, "environmental_efficiency_rating" => 0 },
                      "has_hot_water_cylinder" => "true",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Mid-terrace house",
                      "total_floor_area" => 72,
                      "has_fixed_air_conditioning" => "false",
                      "energy_rating_average" => 60,
                      "energy_rating_current" => 61,
                      "energy_rating_potential" => 85,
                      "environmental_impact_current" => 59,
                      "environmental_impact_potential" => 86,
                      "energy_consumption_current" => 244,
                      "energy_consumption_potential" => 66,
                      "co2_emissions_current" => 3.4,
                      "co2_emissions_potential" => 1.0,
                      "co2_emissions_current_per_floor_area" => 47,
                      "lighting_cost_current" => { "currency" => "GBP", "value" => 69 },
                      "lighting_cost_potential" => { "currency" => "GBP", "value" => 42 },
                      "heating_cost_current" => { "currency" => "GBP", "value" => 546 },
                      "heating_cost_potential" => { "currency" => "GBP", "value" => 378 },
                      "hot_water_cost_current" => { "currency" => "GBP", "value" => 127 },
                      "hot_water_cost_potential" => { "currency" => "GBP", "value" => 68 },
                      "suggested_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 5,
                          "improvement_type" => "Q",
                          "improvement_details" => { "improvement_number" => 7 },
                          "typical_saving" => { "currency" => "GBP", "value" => 66 },
                          "indicative_cost" => "£4,000 - £14,000",
                          "energy_performance_rating" => 65,
                          "environmental_impact_rating" => 63 },
                        { "sequence" => 2,
                          "improvement_category" => 5,
                          "improvement_type" => "W",
                          "improvement_details" => { "improvement_number" => 47 },
                          "typical_saving" => { "currency" => "GBP", "value" => 36 },
                          "indicative_cost" => "£800 - £1,200",
                          "energy_performance_rating" => 67,
                          "environmental_impact_rating" => 66 },
                        { "sequence" => 3,
                          "improvement_category" => 5,
                          "improvement_type" => "E",
                          "improvement_details" => { "improvement_number" => 35 },
                          "typical_saving" => { "currency" => "GBP", "value" => 23 },
                          "indicative_cost" => "£35",
                          "energy_performance_rating" => 68,
                          "environmental_impact_rating" => 67 },
                        { "sequence" => 4,
                          "improvement_category" => 5,
                          "improvement_type" => "G",
                          "improvement_details" => { "improvement_number" => 15 },
                          "typical_saving" => { "currency" => "GBP", "value" => 21 },
                          "indicative_cost" => "£350 - £450",
                          "energy_performance_rating" => 69,
                          "environmental_impact_rating" => 68 },
                        { "sequence" => 5,
                          "improvement_category" => 5,
                          "improvement_type" => "I",
                          "improvement_details" => { "improvement_number" => 20 },
                          "typical_saving" => { "currency" => "GBP", "value" => 75 },
                          "indicative_cost" => "£2,200 - £3,000",
                          "energy_performance_rating" => 73,
                          "environmental_impact_rating" => 73 },
                        { "sequence" => 6,
                          "improvement_category" => 5,
                          "improvement_type" => "N",
                          "improvement_details" => { "improvement_number" => 19 },
                          "typical_saving" => { "currency" => "GBP", "value" => 34 },
                          "indicative_cost" => "£4,000 - £6,000",
                          "energy_performance_rating" => 74,
                          "environmental_impact_rating" => 76 },
                        { "sequence" => 7,
                          "improvement_category" => 5,
                          "improvement_type" => "U",
                          "improvement_details" => { "improvement_number" => 34 },
                          "typical_saving" => { "currency" => "GBP", "value" => 247 },
                          "indicative_cost" => "£9,000 - £14,000",
                          "energy_performance_rating" => 85,
                          "environmental_impact_rating" => 86 }],
                      "alternative_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 6,
                          "improvement_type" => "Z1",
                          "improvement_details" => { "improvement_number" => 51 },
                          "typical_saving" => { "currency" => "GBP", "value" => 57 },
                          "energy_performance_rating" => 72,
                          "environmental_impact_rating" => 74 },
                        { "sequence" => 2,
                          "improvement_category" => 6,
                          "improvement_type" => "Z3",
                          "improvement_details" => { "improvement_number" => 53 },
                          "typical_saving" => { "currency" => "GBP", "value" => 85 },
                          "energy_performance_rating" => 73,
                          "environmental_impact_rating" => 72 }],
                      "addendum" => { "system_build" => "true" },
                      "renewable_heat_incentive" => { "space_heating_existing_dwelling" => 8564, "water_heating" => 2530 },
                      "schema_version" => "LIG-16.1",
                      "built_form" => 4,
                      "multiple_glazing_type" => 3,
                      "multiple_glazed_proportion" => 100,
                      "extensions_count" => 1,
                      "glazed_area" => 1,
                      "habitable_room_count" => 5,
                      "heated_room_count" => 5,
                      "low_energy_lighting" => 36,
                      "fixed_lighting_outlets_count" => 11,
                      "low_energy_fixed_lighting_outlets_count" => 4,
                      "measurement_type" => 1,
                      "open_fireplaces_count" => 0,
                      "conservatory_type" => 1,
                      "solar_water_heating" => "N",
                      "mechanical_ventilation" => 0,
                      "sap_heating" =>
                       { "main_heating_details" =>
                          [{ "main_heating_number" => 1,
                             "main_heating_fraction" => 1,
                             "main_heating_data_source" => 2,
                             "main_heating_category" => 2,
                             "main_fuel_type" => 26,
                             "main_heating_control" => 2103,
                             "sap_main_heating_code" => 101,
                             "boiler_flue_type" => 2,
                             "fan_flue_present" => "Y",
                             "heat_emitter_type" => 1,
                             "has_fghrs" => "N" }],
                         "water_heating_code" => 901,
                         "water_heating_fuel" => 26,
                         "cylinder_size" => 2,
                         "cylinder_insulation_type" => 1,
                         "cylinder_insulation_thickness" => 38,
                         "cylinder_thermostat" => "Y",
                         "has_fixed_air_conditioning" => "false",
                         "wwhrs" =>
                          { "rooms_with_bath_and_or_shower" => 1,
                            "rooms_with_mixer_shower_no_bath" => 0,
                            "rooms_with_bath_and_mixer_shower" => 0 } },
                      "sap_energy_source" =>
                       { "meter_type" => 2,
                         "main_gas" => "Y",
                         "wind_turbines_count" => 0,
                         "wind_turbines_terrain_type" => 1,
                         "photovoltaic_supply" => { "percent_roof_area" => 0 } },
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "identifier" => "Main Dwelling",
                          "construction_age_band" => "C",
                          "wall_insulation_type" => 2,
                          "roof_construction" => 4,
                          "wall_construction" => 4,
                          "roof_insulation_location" => 2,
                          "roof_insulation_thickness" => "300mm+",
                          "sap_floor_dimensions" =>
                           [{ "floor" => 0,
                              "floor_construction" => 2,
                              "floor_insulation" => 1,
                              "heat_loss_perimeter" => 14.9,
                              "room_height" => 2.43,
                              "total_floor_area" => 34.2 },
                            { "floor" => 1, "heat_loss_perimeter" => 9.84, "room_height" => 2.47, "total_floor_area" => 34.2 }],
                          "wall_dry_lined" => "N",
                          "wall_thickness" => 300,
                          "floor_heat_loss" => 7,
                          "wall_thickness_measured" => "Y",
                          "sap_alternative_wall" =>
                           { "wall_construction" => 3,
                             "wall_insulation_type" => 4,
                             "wall_dry_lined" => "N",
                             "wall_thickness_measured" => "N",
                             "wall_area" => 18.9 } },
                        { "building_part_number" => 2,
                          "identifier" => "Extension 1",
                          "construction_age_band" => "E",
                          "wall_insulation_type" => 4,
                          "roof_construction" => 1,
                          "wall_construction" => 8,
                          "roof_insulation_location" => 4,
                          "roof_insulation_thickness" => "NI",
                          "sap_floor_dimensions" =>
                           [{ "floor" => 0,
                              "floor_construction" => 0,
                              "floor_insulation" => 0,
                              "heat_loss_perimeter" => 5.7,
                              "room_height" => 2.26,
                              "total_floor_area" => 3.5 }],
                          "wall_dry_lined" => "N",
                          "wall_thickness" => 200,
                          "floor_heat_loss" => 7,
                          "wall_thickness_measured" => "Y" }],
                      "door_count" => 2,
                      "insulated_door_count" => 0,
                      "percent_draughtproofed" => 100 }

      expect(use_case.execute(xml: rdsap,
                              schema_type: "SAP-Schema-16.1",
                              assessment_id: "4321-4321-4321-4321-4321")).to eq expectation
    end
  end

  context "when loading XML from SAP (SAP-Schema-16.1)" do
    let(:sap) { Samples.xml "SAP-Schema-16.1", "sap" }

    it "parses the document into the expected format" do
      expectation = { "sap_version" => 9.9,
                      "bedf_revision_number" => 333,
                      "calculation_software_name" => "NHER Plan Assessor",
                      "calculation_software_version" => 5.4,
                      "inspection_date" => "2013-01-12",
                      "report_type" => 3,
                      "completion_date" => "2013-01-12",
                      "registration_date" => "2013-01-12",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "transaction_type" => 6,
                      "seller_commission_report" => "Y",
                      "property_type" => 0,
                      "scheme_assessor_id" => 0,
                      "address_line_1" => "28, Place Drive",
                      "post_town" => "Town",
                      "postcode" => "AA1 1AA",
                      "uprn" => 90_000_000_000,
                      "region_code" => 15,
                      "country_code" => "EAW",
                      "assessment_date" => "2013-01-12",
                      "renewable_heat_incentive" => { "rhi_new_dwelling" => { "space_heating" => 1867, "water_heating" => 1839 } },
                      "walls" =>
                       [{ "description" => "Average thermal transmittance 0.30 W/m²K",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "roofs" =>
                       [{ "description" => "Average thermal transmittance 0.15 W/m²K",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "floors" =>
                       [{ "description" => "Average thermal transmittance 0.18 W/m²K",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "windows" =>
                       { "description" => "Fully double glazed", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 4 },
                      "main_heating" =>
                       [{ "description" => "Boiler and radiators, mains gas",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "main_heating_controls" =>
                       [{ "description" => "Programmer, room thermostat and TRVs",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "secondary_heating" => { "description" => "None", "energy_efficiency_rating" => 0, "environmental_efficiency_rating" => 0 },
                      "hot_water" =>
                       { "description" => "From main system", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 4 },
                      "lighting" =>
                       { "description" => "Low energy lighting in 33% of fixed outlets",
                         "energy_efficiency_rating" => 3,
                         "environmental_efficiency_rating" => 3 },
                      "air_tightness" =>
                       { "description" => "Air permeability 7.7 m³/h.m² (as tested)",
                         "energy_efficiency_rating" => 3,
                         "environmental_efficiency_rating" => 3 },
                      "has_fixed_air_conditioning" => "false",
                      "has_hot_water_cylinder" => "false",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Mid-terrace house",
                      "total_floor_area" => 59,
                      "energy_rating_current" => 79,
                      "energy_rating_potential" => 80,
                      "environmental_impact_current" => 83,
                      "environmental_impact_potential" => 84,
                      "energy_consumption_current" => 119,
                      "energy_consumption_potential" => 110,
                      "co2_emissions_current" => 1.3,
                      "co2_emissions_current_per_floor_area" => 22,
                      "co2_emissions_potential" => 1.2,
                      "lighting_cost_current" => 66,
                      "lighting_cost_potential" => 39,
                      "heating_cost_current" => 236,
                      "heating_cost_potential" => 240,
                      "hot_water_cost_current" => 76,
                      "hot_water_cost_potential" => 76,
                      "energy_rating_average" => 60,
                      "suggested_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 1,
                          "improvement_type" => "E",
                          "improvement_details" => { "improvement_number" => 35 },
                          "typical_saving" => 23,
                          "energy_performance_rating" => 80,
                          "environmental_impact_rating" => 84,
                          "indicative_cost" => "£15" },
                        { "sequence" => 2,
                          "improvement_category" => 3,
                          "improvement_type" => "N",
                          "improvement_details" => { "improvement_number" => 19 },
                          "typical_saving" => 25,
                          "energy_performance_rating" => 81,
                          "environmental_impact_rating" => 86,
                          "indicative_cost" => "£4,000 - £6,000" },
                        { "sequence" => 3,
                          "improvement_category" => 3,
                          "improvement_type" => "U",
                          "improvement_details" => { "improvement_number" => 34 },
                          "typical_saving" => 226,
                          "energy_performance_rating" => 94,
                          "environmental_impact_rating" => 98,
                          "indicative_cost" => "£11,000 - £20,000" },
                        { "sequence" => 4,
                          "improvement_category" => 3,
                          "improvement_type" => "V",
                          "improvement_details" => { "improvement_number" => 44 },
                          "typical_saving" => 19,
                          "energy_performance_rating" => 95,
                          "environmental_impact_rating" => 99,
                          "indicative_cost" => "£1,500 - £4,000" }],
                      "data_type" => 2,
                      "schema_version" => "LIG-16.0",
                      "built_form" => 4,
                      "living_area" => 12.04,
                      "orientation" => 0,
                      "conservatory_type" => 1,
                      "is_in_smoke_control_area" => "unknown",
                      "sap_heating" =>
                       { "water_heating_code" => 901,
                         "water_fuel_type" => 1,
                         "has_hot_water_cylinder" => "false",
                         "secondary_heating_category" => 1,
                         "thermal_store" => 1,
                         "has_fixed_air_conditioning" => "false",
                         "has_solar_panel" => "false",
                         "main_heating_details" =>
                          [{ "main_heating_number" => 1,
                             "main_heating_category" => 2,
                             "main_heating_data_source" => 1,
                             "boiler_index_number" => 9901,
                             "main_fuel_type" => 1,
                             "main_heating_control" => 2106,
                             "heat_emitter_type" => 1,
                             "is_flue_fan_present" => "true",
                             "is_central_heating_pump_in_heated_space" => "true",
                             "is_interlocked_system" => "true",
                             "has_delayed_start_thermostat" => "false",
                             "load_or_weather_compensation" => 0,
                             "main_heating_fraction" => 1 }] },
                      "sap_energy_source" =>
                       { "wind_turbines_count" => 0,
                         "wind_turbine_terrain_type" => 2,
                         "fixed_lighting_outlets_count" => 9,
                         "low_energy_fixed_lighting_outlets_count" => 3,
                         "low_energy_fixed_lighting_outlets_percentage" => 33,
                         "electricity_tariff" => 1 },
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "identifier" => "Main Dwelling",
                          "construction_year" => 2012,
                          "overshading" => 2,
                          "sap_openings" =>
                           [{ "name" => 1, "type" => 1, "location" => "Wall 1", "orientation" => 0, "width" => 0.93, "height" => 2.1 },
                            { "name" => 2, "type" => 2, "location" => "Wall 1", "orientation" => 1, "width" => 1.77, "height" => 1.35 },
                            { "name" => 3, "type" => 2, "location" => "Wall 1", "orientation" => 1, "width" => 1.2, "height" => 1.05 },
                            { "name" => 4, "type" => 4, "location" => "Wall 1", "orientation" => 0, "width" => 0.93, "height" => 2.1 },
                            { "name" => 5, "type" => 2, "location" => "Wall 1", "orientation" => 5, "width" => 1.2, "height" => 1.05 },
                            { "name" => 6, "type" => 2, "location" => "Wall 1", "orientation" => 5, "width" => 1.77, "height" => 1.05 }],
                          "sap_roofs" =>
                           [{ "name" => "Roof 1", "description" => "Roof 1", "roof_type" => 2, "total_roof_area" => 29.25, "u_value" => 0.15 }],
                          "sap_floor_dimensions" =>
                           [{ "storey" => 0,
                              "description" => "Floor 1",
                              "floor_type" => 2,
                              "total_floor_area" => 29.25,
                              "storey_height" => 2.37,
                              "heat_loss_area" => 29.25,
                              "u_value" => 0.18 },
                            { "storey" => 1,
                              "floor_type" => 3,
                              "total_floor_area" => 29.25,
                              "storey_height" => 2.59,
                              "heat_loss_area" => 0,
                              "u_value" => 0 }],
                          "sap_thermal_bridges" =>
                           { "thermal_bridge_code" => 4, "user_defined_y_value" => 0.08, "calculation_reference" => "ACDs" },
                          "sap_walls" =>
                           [{ "name" => "Wall 1",
                              "description" => "Wall 1",
                              "wall_type" => 2,
                              "total_wall_area" => 38.69,
                              "u_value" => 0.3,
                              "is_curtain_walling" => "false" },
                            { "name" => "Wall 2",
                              "description" => "High step",
                              "wall_type" => 2,
                              "total_wall_area" => 2.25,
                              "u_value" => 0.3,
                              "is_curtain_walling" => "false" },
                            { "name" => "Wall 3",
                              "description" => "low step",
                              "wall_type" => 2,
                              "total_wall_area" => 2.25,
                              "u_value" => 0.3,
                              "is_curtain_walling" => "false" }],
                          "thermal_mass_parameter" => 250 }],
                      "sap_opening_types" =>
                       [{ "name" => 1, "data_source" => 2, "type" => 1, "glazing_type" => 1, "u_value" => 1.57 },
                        { "name" => 2,
                          "data_source" => 3,
                          "type" => 4,
                          "glazing_type" => 6,
                          "glazing_gap" => 3,
                          "isargonfilled" => "false",
                          "frame_type" => 2,
                          "solar_transmittance" => 0.63,
                          "frame_factor" => 0.7,
                          "u_value" => 1.9 },
                        { "name" => 4, "data_source" => 2, "type" => 2, "glazing_type" => 6, "u_value" => 1.9 }],
                      "sap_ventilation" =>
                       { "open_fireplaces_count" => 0,
                         "open_flues_count" => 0,
                         "flueless_gas_fires_count" => 0,
                         "pressure_test" => 1,
                         "air_permeability" => 7.7,
                         "sheltered_sides_count" => 2,
                         "ventilation_type" => 1,
                         "extract_fans_count" => 3,
                         "psv_count" => 0 } }

      expect(use_case.execute(xml: sap,
                              schema_type: "SAP-Schema-16.1",
                              assessment_id: "1234-1234-1234-1234-1234")).to eq expectation
    end
  end
end
