RSpec.describe "the parser and the SAP configuration" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from RdSAP (SAP 13.0)" do
    let(:rdsap) { Samples.xml "SAP-Schema-13.0", "rdsap" }

    it "parses the document into the expected format" do
      expectation = { "calculation_software_name" => "RdSAP Software",
                      "calculation_software_version" => "1.4.1.0",
                      "sap_version" => 9.82,
                      "inspection_date" => "2020-05-04",
                      "report_type" => 2,
                      "completion_date" => "2020-05-04",
                      "registration_date" => "2020-05-04",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "transaction_type" => 5,
                      "seller_commission_report" => "Y",
                      "property_type" => 3,
                      "scheme_assessor_id" => "SPEC000000",
                      "address_line_1" => "1 Some Street",
                      "address_line_2" => "Some Area",
                      "address_line_3" => "Some County",
                      "post_town" => "Whitbury",
                      "postcode" => "SW1A 2AA",
                      "uprn" => 0,
                      "region_code" => 18,
                      "country_code" => "EAW",
                      "walls" => [{ "energy_efficiency_rating" => 0, "description" => "Brick walls", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "Brick walls", "environmental_efficiency_rating" => 0 }],
                      "roofs" => [{ "energy_efficiency_rating" => 0, "description" => "Slate roof", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "slate roof", "environmental_efficiency_rating" => 0 }],
                      "floors" => [{ "energy_efficiency_rating" => 0, "description" => "Tiled floor", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "Tiled floor", "environmental_efficiency_rating" => 0 }],
                      "windows" => [{ "energy_efficiency_rating" => 0, "description" => "Glass window", "environmental_efficiency_rating" => 0 }],
                      "main_heating" => [{ "energy_efficiency_rating" => 0, "description" => "Gas boiler", "environmental_efficiency_rating" => 0 }],
                      "main_heating_controls" => [{ "energy_efficiency_rating" => 0, "description" => "Thermostat", "environmental_efficiency_rating" => 0 }],
                      "hot_water" => { "energy_efficiency_rating" => 0, "description" => "Gas boiler", "environmental_efficiency_rating" => 0 },
                      "lighting" => { "energy_efficiency_rating" => 0, "description" => "Energy saving bulbs", "environmental_efficiency_rating" => 0 },
                      "secondary_heating" => { "energy_efficiency_rating" => 0, "description" => "Electric heater", "environmental_efficiency_rating" => 0 },
                      "has_hot_water_cylinder" => "false",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Mid-terrace house",
                      "total_floor_area" => 69,
                      "energy_rating_current" => 50,
                      "energy_rating_potential" => 72,
                      "environmental_impact_current" => 52,
                      "environmental_impact_potential" => 70,
                      "energy_consumption_current" => 230,
                      "energy_consumption_potential" => 88,
                      "co2_emissions_current" => 2.4,
                      "co2_emissions_potential" => 1.4,
                      "co2_emissions_current_per_floor_area" => 56,
                      "lighting_cost_current" => 123.45,
                      "lighting_cost_potential" => 84.23,
                      "heating_cost_current" => 365.98,
                      "heating_cost_potential" => 250.34,
                      "hot_water_cost_current" => 200.4,
                      "hot_water_cost_potential" => 180.43,
                      "suggested_improvements" => [{ "sequence" => 1, "improvement_category" => 1, "typical_saving" => 360, "energy_performance_rating" => 50, "environmental_impact_rating" => 50 }, { "sequence" => 2, "improvement_category" => 2, "typical_saving" => 99, "energy_performance_rating" => 60, "environmental_impact_rating" => 64, "improvement_description" => "Improvement desc" }],
                      "schema_version" => "LIG-16.1",
                      "built_form" => 1,
                      "multiple_glazed_proportion" => 65,
                      "multiple_glazing_type" => 2,
                      "extensions_count" => 0,
                      "glazed_area" => 1,
                      "habitable_room_count" => 4,
                      "heated_room_count" => 4,
                      "low_energy_lighting" => 90,
                      "measurement_type" => 1,
                      "open_fireplaces_count" => 0,
                      "photovoltaic_supply" => 0,
                      "solar_water_heating" => "N",
                      "mechanical_ventilation" => 0,
                      "conservatory_type" => 1,
                      "sap_building_parts" => [{ "building_part_number" => 1, "identifier" => "Main Dwelling", "construction_age_band" => "A", "wall_construction" => 1, "wall_insulation_type" => 4, "roof_construction" => 4, "roof_insulation_location" => 4, "roof_insulation_thickness" => "NI", "sap_floor_dimensions" => [{ "floor" => 0, "floor_construction" => 1, "floor_insulation" => 1, "heat_loss_perimeter" => 13.28, "total_floor_area" => 31.26, "room_height" => 2.45 }, { "floor" => 1, "heat_loss_perimeter" => 13.28, "total_floor_area" => 31.26, "room_height" => 2.32 }], "sap_room_in_roof" => { "floor_area" => 18.3, "construction_age_band" => "A", "insulation" => 0 } }, { "building_part_number" => 2, "identifier" => "Extension 1", "construction_age_band" => "A", "wall_construction" => 3, "wall_insulation_type" => 4, "roof_construction" => 5, "roof_insulation_location" => 4, "roof_insulation_thickness" => "NI", "sap_floor_dimensions" => [{ "floor" => 0, "floor_construction" => 1, "floor_insulation" => 1, "heat_loss_perimeter" => 9.29, "total_floor_area" => 8.47, "room_height" => 2.45 }, { "floor" => 1, "heat_loss_perimeter" => 9.29, "total_floor_area" => 8.47, "room_height" => 2.32 }] }],
                      "sap_heating" => { "main_heating_category" => 7, "secondary_fuel_type" => 10, "main_fuel_type" => 10, "water_heating_fuel" => 10, "main_heating_control" => 2401, "secondary_heating_type" => 693, "water_heating_code" => 903, "immersion_heating_type" => 2, "cylinder_size" => 3, "cylinder_insulation_type" => 2, "cylinder_insulation_thickness" => 50, "main_heating_data_source" => 2, "sap_main_heating_code" => 402, "heat_emitter_type" => 0, "bedf_revision_number" => 353 },
                      "sap_energy_source" => { "meter_type" => 2, "main_gas" => "Y", "wind_turbines_count" => 0, "wind_turbines_terrain_type" => 2 },
                      "sap_flat_details" => { "flat_location" => 1, "storey_count" => 3, "top_storey" => "Y", "heat_loss_corridor" => 0, "floor_heat_loss" => 3 } }

      expect(use_case.execute(xml: rdsap,
                              schema_type: "SAP-Schema-13.0",
                              assessment_id: "4321-4321-4321-4321-4321")).to eq expectation
    end
  end

  context "when loading XML from SAP (SAP-Schema-13.0)" do
    let(:sap) { Samples.xml "SAP-Schema-13.0", "sap" }

    it "parses the document into the expected format" do
      expectation = { "sap_version" => 9.81,
                      "bedf_revision_number" => 251,
                      "calculation_software_name" => "Plan Assessor",
                      "calculation_software_version" => 4.2,
                      "inspection_date" => "2020-05-04",
                      "report_type" => 3,
                      "completion_date" => "2020-05-04",
                      "registration_date" => "2020-05-04",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "seller_commission_report" => "Y",
                      "property_type" => 0,
                      "scheme_assessor_id" => "SPEC000000",
                      "transaction_type" => 6,
                      "region_code" => 2,
                      "country_code" => "EAW",
                      "address_line_1" => "1 Some Street",
                      "address_line_2" => "Some Area",
                      "address_line_3" => "Some County",
                      "post_town" => "Whitbury",
                      "postcode" => "SW1A 2AA",
                      "uprn" => 0,
                      "assessment_date" => "2010-03-23",
                      "walls" => [{ "energy_efficiency_rating" => 0, "description" => "Brick walls", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "Brick walls", "environmental_efficiency_rating" => 0 }],
                      "roofs" => [{ "energy_efficiency_rating" => 0, "description" => "Slate roof", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "slate roof", "environmental_efficiency_rating" => 0 }],
                      "floors" => [{ "energy_efficiency_rating" => 0, "description" => "Tiled floor", "environmental_efficiency_rating" => 0 }, { "energy_efficiency_rating" => 0, "description" => "Tiled floor", "environmental_efficiency_rating" => 0 }],
                      "windows" => { "energy_efficiency_rating" => 0, "description" => "Glass window", "environmental_efficiency_rating" => 0 },
                      "main_heating" => [{ "energy_efficiency_rating" => 0, "description" => "Gas boiler", "environmental_efficiency_rating" => 0 }],
                      "main_heating_controls" => [{ "energy_efficiency_rating" => 0, "description" => "Thermostat", "environmental_efficiency_rating" => 0 }],
                      "secondary_heating" => { "energy_efficiency_rating" => 0, "description" => "Electric heater", "environmental_efficiency_rating" => 0 },
                      "hot_water" => { "energy_efficiency_rating" => 0, "description" => "Gas boiler", "environmental_efficiency_rating" => 0 },
                      "lighting" => { "energy_efficiency_rating" => 0, "description" => "Energy saving bulbs", "environmental_efficiency_rating" => 0 },
                      "air_tightness" => { "energy_efficiency_rating" => 0, "description" => "Draft Exclusion", "environmental_efficiency_rating" => 0 },
                      "has_fixed_air_conditioning" => "false",
                      "has_hot_water_cylinder" => "true",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Mid-terrace house",
                      "total_floor_area" => 69,
                      "energy_rating_current" => 50,
                      "energy_rating_potential" => 72,
                      "environmental_impact_current" => 52,
                      "environmental_impact_potential" => 93,
                      "energy_consumption_current" => 230,
                      "energy_consumption_potential" => 88,
                      "co2_emissions_current" => 2.4,
                      "co2_emissions_current_per_floor_area" => 20,
                      "co2_emissions_potential" => 1.4,
                      "lighting_cost_current" => 123.45,
                      "lighting_cost_potential" => 84.23,
                      "heating_cost_current" => 365.98,
                      "heating_cost_potential" => 250.34,
                      "hot_water_cost_current" => 200.4,
                      "hot_water_cost_potential" => 180.43,
                      "suggested_improvements" => [{ "sequence" => 1, "improvement_category" => 1, "improvement_type" => "A", "typical_saving" => 360, "energy_performance_rating" => 50, "environmental_impact_rating" => 50, "improvement_details" => { "improvement_number" => 5 } }, { "sequence" => 2, "improvement_category" => 2, "improvement_type" => "B", "typical_saving" => 99, "energy_performance_rating" => 60, "environmental_impact_rating" => 64, "improvement_details" => { "improvement_texts" => { "improvement_description" => "Improvement desc" } } }],
                      "data_type" => 2,
                      "schema_version" => "LIG-14.0",
                      "built_form" => 2,
                      "living_area" => 11.92,
                      "orientation" => 0,
                      "conservatory_type" => 1,
                      "has_special_feature" => "false",
                      "is_in_smoke_control_area" => "false",
                      "additional_allowable_electricity_generation" => 0,
                      "sap_heating" => { "main_heating_category" => 2, "main_heating_data_source" => 1, "boiler_index_number" => 9895, "main_fuel_type" => 36, "main_heating_control" => 2106, "water_heating_code" => 901, "water_fuel_type" => 1, "has_hot_water_cylinder" => "true", "heat_emitter_type" => 1, "main_heating_flue_type" => 2, "is_flue_fan_present" => "true", "is_central_heating_pump_in_heated_space" => "true", "is_interlocked_system" => "true", "has_delayed_start_thermostat" => "false", "has_load_or_weather_compensation" => "false", "secondary_heating_category" => 1, "thermal_store" => 1, "has_fixed_air_conditioning" => "false", "is_main_heating_hetas_approved" => "false", "is_secondary_heating_hetas_approved" => "false", "hot_water_store_size" => 140, "hot_water_store_heat_loss_source" => 3, "hot_water_store_insulation_type" => 1, "hot_water_store_insulation_thickness" => 50, "is_primary_pipework_insulated" => "true", "has_cylinder_thermostat" => "true", "is_cylinder_in_heated_space" => "true", "is_hot_water_separately_timed" => "true", "has_solar_panel" => "false" },
                      "sap_energy_source" => { "pv_peak_power" => 0.0, "wind_turbines_count" => 0, "wind_turbine_terrain_type" => 1, "fixed_lighting_outlets_count" => 8, "low_energy_fixed_lighting_outlets_count" => 4, "low_energy_fixed_lighting_outlets_percentage" => 50, "electricity_tariff" => 1 },
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "construction_year" => 1750,
                          "overshading" => 1,
                          "sap_openings" => [{ "name" => 1, "type" => 1, "location" => "Filled cavity wall0", "orientation" => 5, "width" => 1.2, "height" => 2.1 }, { "name" => 2, "type" => 2, "location" => "Filled cavity wall0", "orientation" => 5, "width" => 0.75, "height" => 1.2 }, { "name" => 3, "type" => 3, "location" => "Filled cavity wall0", "orientation" => 5, "width" => 0.86, "height" => 1.05 }, { "name" => 4, "type" => 4, "location" => "Filled cavity wall0", "orientation" => 5, "width" => 0.86, "height" => 1.05 }, { "name" => 5, "type" => 5, "location" => "Timber frame1", "orientation" => 5, "width" => 1.5, "height" => 1.05 }, { "name" => 6, "type" => 6, "location" => "Filled cavity wall0", "orientation" => 1, "width" => 0.86, "height" => 1.05 }, { "name" => 7, "type" => 7, "location" => "Filled cavity wall0", "orientation" => 1, "width" => 0.94, "height" => 2.1 }, { "name" => 8, "type" => 8, "location" => "Filled cavity wall0", "orientation" => 1, "width" => 0.86, "height" => 1.05 }, { "name" => 9, "type" => 9, "location" => "Filled cavity wall0", "orientation" => 1, "width" => 0.86, "height" => 1.05 }, { "name" => 10, "type" => 10, "location" => "Timber frame1", "orientation" => 1, "width" => 1.5, "height" => 1.05 }, { "name" => 11, "type" => 11, "location" => "Filled cavity wall0", "orientation" => 7, "width" => 0.86, "height" => 1.05 }],
                          "sap_exposed_roofs" => [{ "name" => "Pitched roof, ins. 0", "description" => "No information", "total_roof_area" => 18.4, "u_value" => 0.15 }, { "name" => "Pitched roof, ins. 1", "description" => "No information", "total_roof_area" => 17.6, "u_value" => 0.2 }],
                          "sap_floor_dimensions" => [{ "storey" => 0, "floor_type" => 2, "total_floor_area" => 28.8, "storey_height" => 2.4, "heat_loss_area" => 28.8, "u_value" => 0.22 }, { "storey" => 1, "floor_type" => 3, "total_floor_area" => 28.8, "storey_height" => 2.5, "heat_loss_area" => 0.0, "u_value" => 0.0 }, { "storey" => 2, "floor_type" => 3, "total_floor_area" => 20.0, "storey_height" => 2, "heat_loss_area" => 0, "u_value" => 0 }],
                          "sap_thermal_bridges" => { "thermal_bridge_code" => 1, "user_defined_y_value" => 0.15 },
                          "sap_exposed_walls" => [{ "name" => "Filled cavity wall0", "description" => "Cavity construction", "wall_type" => 2, "total_wall_area" => 83.3, "u_value" => 0.34, "is_curtain_walling" => "false" }, { "name" => "Timber frame1", "description" => "Timber construction", "wall_type" => 2, "total_wall_area" => 10.4, "u_value" => 0.33, "is_curtain_walling" => "false" }] }],
                      "sap_opening_types" => [{ "name" => 1, "description" => "Lounge", "data_source" => 2, "type" => 4, "glazing_gap" => 3, "isargonfilled" => "false", "frame_type" => 2, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.9 }, { "name" => 2, "description" => "Lounge", "data_source" => 2, "type" => 4, "glazing_gap" => 3, "isargonfilled" => "false", "frame_type" => 2, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.9 }, { "name" => 3, "description" => "Bed 2", "data_source" => 2, "type" => 4, "glazing_gap" => 3, "isargonfilled" => "false", "frame_type" => 2, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.9 }, { "name" => 4, "description" => "Bed 2", "data_source" => 2, "type" => 4, "glazing_gap" => 3, "isargonfilled" => "false", "frame_type" => 2, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.9 }, { "name" => 5, "description" => "En suite", "data_source" => 2, "type" => 4, "glazing_gap" => 3, "isargonfilled" => "false", "frame_type" => 2, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.9 }, { "name" => 6, "description" => "Kitchen", "data_source" => 2, "type" => 4, "glazing_gap" => 3, "isargonfilled" => "false", "frame_type" => 2, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.9 }, { "name" => 7, "description" => "Hall", "data_source" => 3, "type" => 2, "glazing_type" => 4, "glazing_gap" => 3, "isargonfilled" => "true", "frame_type" => 2, "solar_transmittance" => 0.72, "frame_factor" => 0.7, "u_value" => 2.5 }, { "name" => 8, "description" => "Landing", "data_source" => 2, "type" => 4, "glazing_gap" => 3, "isargonfilled" => "false", "frame_type" => 2, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.9 }, { "name" => 9, "description" => "Bed 3", "data_source" => 2, "type" => 4, "glazing_gap" => 3, "isargonfilled" => "false", "frame_type" => 2, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.9 }, { "name" => 10, "description" => "En suite", "data_source" => 2, "type" => 4, "glazing_gap" => 3, "isargonfilled" => "false", "frame_type" => 2, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.9 }, { "name" => 11, "description" => "Bathroom", "data_source" => 2, "type" => 4, "glazing_gap" => 3, "isargonfilled" => "false", "frame_type" => 2, "solar_transmittance" => 0.63, "frame_factor" => 0.7, "u_value" => 1.9 }],
                      "sap_ventilation" => { "open_fireplaces_count" => 0, "open_flues_count" => 0, "fans_vents_count" => 4, "flueless_gas_fires_count" => 0, "pressure_test" => 4, "ground_floor_type" => 1, "wall_type" => 2, "has_draught_lobby" => "false", "draughtstripping" => 100, "sheltered_sides_count" => 1, "ventilation_type" => 1, "mechanical_vent_specific_fan_power" => 0.0 } }

      expect(use_case.execute(xml: sap,
                              schema_type: "SAP-Schema-13.0",
                              assessment_id: "1234-1234-1234-1234-1234")).to eq expectation
    end
  end
end
