RSpec.describe "the parser and the SAP configuration (for Northern Ireland)" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from RdSAP (SAP NI 17.0)" do
    let(:rdsap) { Samples.xml "SAP-Schema-NI-17.0", "rdsap" }

    it "parses the document into the expected format" do
      expectation = { "sap_version" => 9.91,
                      "bedf_revision_number" => 326,
                      "calculation_software_name" => "Stroma RdSAP Software",
                      "calculation_software_version" => "1.4.0.0",
                      "inspection_date" => "2011-09-26",
                      "report_type" => 2,
                      "completion_date" => "2011-09-26",
                      "registration_date" => "2011-09-26",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "tenure" => "ND",
                      "transaction_type" => 1,
                      "seller_commission_report" => "Y",
                      "property_type" => 0,
                      "scheme_assessor_id" => "SCHE010101",
                      "address_line_1" => "1 High Street",
                      "post_town" => "POSTTOWN",
                      "postcode" => "BT1 1AA",
                      "uprn" => 55_555_555_555,
                      "region_code" => 10,
                      "country_code" => "NIR",
                      "walls" =>
                        [{ "description" => "Solid brick, as built, no insulation (assumed)",
                           "energy_efficiency_rating" => 1,
                           "environmental_efficiency_rating" => 1 }],
                      "roofs" =>
                        [{ "description" => "Pitched, no insulation (assumed)",
                           "energy_efficiency_rating" => 1,
                           "environmental_efficiency_rating" => 1 }],
                      "floors" =>
                        [{ "description" => "Solid, no insulation (assumed)",
                           "energy_efficiency_rating" => 0,
                           "environmental_efficiency_rating" => 0 }],
                      "windows" =>
                        [{ "description" => "Fully double glazed",
                           "energy_efficiency_rating" => 3,
                           "environmental_efficiency_rating" => 3 }],
                      "main_heating" =>
                        [{ "description" => "Boiler and radiators, oil",
                           "energy_efficiency_rating" => 3,
                           "environmental_efficiency_rating" => 3 }],
                      "main_heating_controls" =>
                        [{ "description" => "Programmer, no room thermostat",
                           "energy_efficiency_rating" => 1,
                           "environmental_efficiency_rating" => 1 }],
                      "hot_water" =>
                        { "description" => "From main system, no cylinder thermostat",
                          "energy_efficiency_rating" => 2,
                          "environmental_efficiency_rating" => 2 },
                      "lighting" =>
                        { "description" => "Low energy lighting in 8% of fixed outlets",
                          "energy_efficiency_rating" => 1,
                          "environmental_efficiency_rating" => 1 },
                      "secondary_heating" =>
                        { "description" => "None",
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 },
                      "has_hot_water_cylinder" => "true",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Detached house",
                      "total_floor_area" => 136,
                      "has_fixed_air_conditioning" => "false",
                      "energy_rating_average" => 57,
                      "energy_rating_current" => 27,
                      "energy_rating_potential" => 48,
                      "environmental_impact_current" => 21,
                      "environmental_impact_potential" => 37,
                      "energy_consumption_current" => 405,
                      "energy_consumption_potential" => 273,
                      "co2_emissions_current" => 14,
                      "co2_emissions_potential" => 9.4,
                      "co2_emissions_current_per_floor_area" => 102,
                      "lighting_cost_current" => { "currency" => "GBP", "value" => 122 },
                      "lighting_cost_potential" => { "currency" => "GBP", "value" => 64 },
                      "heating_cost_current" => { "currency" => "GBP", "value" => 2079 },
                      "heating_cost_potential" => { "currency" => "GBP", "value" => 1490 },
                      "hot_water_cost_current" => { "currency" => "GBP", "value" => 387 },
                      "hot_water_cost_potential" => { "currency" => "GBP", "value" => 194 },
                      "suggested_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 3,
                          "improvement_type" => "Q",
                          "improvement_details" => { "improvement_number" => 7 },
                          "typical_saving" => { "currency" => "GBP", "value" => 552 },
                          "indicative_cost" => "£4,000 - £14,000",
                          "energy_performance_rating" => 66,
                          "environmental_impact_rating" => 55 },
                        { "sequence" => 2,
                          "improvement_category" => 2,
                          "improvement_type" => "W",
                          "improvement_details" => { "improvement_number" => 47 },
                          "typical_saving" => { "currency" => "GBP", "value" => 93 },
                          "indicative_cost" => "£800 - £1,200",
                          "energy_performance_rating" => 37,
                          "environmental_impact_rating" => 28 },
                        { "sequence" => 3,
                          "improvement_category" => 1,
                          "improvement_type" => "C",
                          "improvement_details" => { "improvement_number" => 2 },
                          "typical_saving" => { "currency" => "GBP", "value" => 85 },
                          "indicative_cost" => "£15 - £30",
                          "energy_performance_rating" => 29,
                          "environmental_impact_rating" => 22 },
                        { "sequence" => 4,
                          "improvement_category" => 1,
                          "improvement_type" => "E",
                          "improvement_details" => { "improvement_number" => 35 },
                          "typical_saving" => { "currency" => "GBP", "value" => 46 },
                          "indicative_cost" => "£55",
                          "energy_performance_rating" => 30,
                          "environmental_impact_rating" => 23 },
                        { "sequence" => 5,
                          "improvement_category" => 1,
                          "improvement_type" => "G",
                          "improvement_details" => { "improvement_number" => 12 },
                          "typical_saving" => { "currency" => "GBP", "value" => 218 },
                          "indicative_cost" => "£350 - £450",
                          "energy_performance_rating" => 35,
                          "environmental_impact_rating" => 26 },
                        { "sequence" => 6,
                          "improvement_category" => 2,
                          "improvement_type" => "I",
                          "improvement_details" => { "improvement_number" => 20 },
                          "typical_saving" => { "currency" => "GBP", "value" => 405 },
                          "indicative_cost" => "£2,200 - £3,000",
                          "energy_performance_rating" => 48,
                          "environmental_impact_rating" => 37 },
                        { "sequence" => 7,
                          "improvement_category" => 3,
                          "improvement_type" => "N",
                          "improvement_details" => { "improvement_number" => 19 },
                          "typical_saving" => { "currency" => "GBP", "value" => 39 },
                          "indicative_cost" => "£4,000 - £6,000",
                          "energy_performance_rating" => 49,
                          "environmental_impact_rating" => 38 },
                        { "sequence" => 8,
                          "improvement_category" => 3,
                          "improvement_type" => "U",
                          "improvement_details" => { "improvement_number" => 34 },
                          "typical_saving" => { "currency" => "GBP", "value" => 209 },
                          "indicative_cost" => "£9,000 - £14,000",
                          "energy_performance_rating" => 73,
                          "environmental_impact_rating" => 61 }],
                      "schema_version" => "LIG-16.1",
                      "built_form" => 1,
                      "extensions_count" => 0,
                      "multiple_glazed_proportion" => 100,
                      "multiple_glazing_type" => 3,
                      "glazed_area" => 1,
                      "door_count" => 2,
                      "insulated_door_count" => 0,
                      "windows_u_value" => 3.1,
                      "solar_transmittance" => 0.76,
                      "windows_data_source" => 2,
                      "percent_draughtproofed" => 100,
                      "habitable_room_count" => 6,
                      "heated_room_count" => 6,
                      "fixed_lighting_outlets_count" => 12,
                      "low_energy_fixed_lighting_outlets_count" => 1,
                      "low_energy_lighting" => 8,
                      "measurement_type" => 1,
                      "mechanical_ventilation" => 0,
                      "open_fireplaces_count" => 0,
                      "solar_water_heating" => "N",
                      "conservatory_type" => 1,
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "identifier" => "Main Dwelling",
                          "construction_age_band" => "B",
                          "wall_thickness_measured" => "Y",
                          "wall_thickness" => 280,
                          "wall_dry_lined" => "N",
                          "wall_construction" => 3,
                          "wall_insulation_type" => 4,
                          "roof_construction" => 5,
                          "roof_insulation_location" => 4,
                          "roof_insulation_thickness" => "NI",
                          "sap_floor_dimensions" =>
                           [{ "floor" => 0, "floor_construction" => 1, "floor_insulation" => 1, "heat_loss_perimeter" => 33.314, "total_floor_area" => 67.38, "room_height" => 2.12 },
                            { "floor" => 1, "heat_loss_perimeter" => 34.454, "total_floor_area" => 68.234, "room_height" => 2.69 }],
                          "floor_heat_loss" => 7 }],
                      "sap_heating" =>
                       { "main_heating_details" =>
                          [{ "main_heating_number" => 1,
                             "main_heating_category" => 2,
                             "main_heating_fraction" => 1,
                             "main_heating_data_source" => 2,
                             "sap_main_heating_code" => 126,
                             "main_fuel_type" => 28,
                             "main_heating_control" => 2102,
                             "boiler_flue_type" => 1,
                             "fan_flue_present" => "N",
                             "heat_emitter_type" => 1,
                             "has_fghrs" => "N" }],
                         "water_heating_code" => 901,
                         "water_heating_fuel" => 28,
                         "cylinder_size" => 2,
                         "cylinder_insulation_type" => 2,
                         "cylinder_insulation_thickness" => 12,
                         "cylinder_thermostat" => "N",
                         "has_fixed_air_conditioning" => "false",
                         "wwhrs" => { "rooms_with_bath_and_or_shower" => 1, "rooms_with_mixer_shower_no_bath" => 0, "rooms_with_bath_and_mixer_shower" => 0 } },
                      "sap_energy_source" =>
                       { "meter_type" => 2, "main_gas" => "N", "wind_turbines_count" => 0, "wind_turbines_terrain_type" => 2, "photovoltaic_supply" => { "percent_roof_area" => 0 } } }

      expect(use_case.execute(xml: rdsap,
                              schema_type: "SAP-Schema-NI-17.0",
                              assessment_id: "4321-4321-4321-4321-4321")).to eq expectation
    end
  end

  context "when loading XML from SAP (SAP NI 17.0)" do
    let(:sap) { Samples.xml "SAP-Schema-NI-17.0", "sap" }

    it "parses the document into the expected format" do
      expectation = { "sap_version" => 9.9,
                      "sap_data_version" => 9.81,
                      "bedf_revision_number" => 329,
                      "calculation_software_name" => "Elmhurst Energy Systems SAP2009 Calculator (Design System)",
                      "calculation_software_version" => "4.3.15.0",
                      "inspection_date" => "2011-12-09",
                      "report_type" => 3,
                      "completion_date" => "2011-12-09",
                      "registration_date" => "2011-12-09",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "transaction_type" => 6,
                      "tenure" => "ND",
                      "seller_commission_report" => "Y",
                      "property_type" => 0,
                      "scheme_assessor_id" => "SCHE010101",
                      "address_line_1" => "999 Letsbe Avenue",
                      "address_line_2" => "District",
                      "post_town" => "POSTTOWN",
                      "postcode" => "BT1 1AA",
                      "uprn" => 55_555_555_555,
                      "region_code" => 10,
                      "country_code" => "NIR",
                      "assessment_date" => "2012-11-09",
                      "walls" =>
                        [{ "description" => "K",
                           "energy_efficiency_rating" => 4,
                           "environmental_efficiency_rating" => 4 }],
                      "roofs" =>
                        [{ "description" => "K",
                           "energy_efficiency_rating" => 4,
                           "environmental_efficiency_rating" => 4 }],
                      "floors" =>
                        [{ "description" => "K",
                           "energy_efficiency_rating" => 5,
                           "environmental_efficiency_rating" => 5 }],
                      "windows" =>
                        { "description" => "High performance glazing",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 },
                      "main_heating" =>
                        [{ "description" => "Boiler and radiators, mains gas",
                           "energy_efficiency_rating" => 4,
                           "environmental_efficiency_rating" => 4 }],
                      "main_heating_controls" =>
                        [{ "description" => "Programmer, room thermostat and TRVs",
                           "energy_efficiency_rating" => 4,
                           "environmental_efficiency_rating" => 4 }],
                      "secondary_heating" =>
                        { "description" => "None",
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 },
                      "hot_water" =>
                        { "description" => "From main system",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 },
                      "lighting" =>
                        { "description" => "Low energy lighting in 50% of fixed outlets",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 },
                      "air_tightness" =>
                        { "description" => "(as tested)",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 },
                      "has_fixed_air_conditioning" => "false",
                      "has_hot_water_cylinder" => "false",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Detached house",
                      "total_floor_area" => 108,
                      "energy_rating_average" => 57,
                      "energy_rating_typical_newbuild" => 81,
                      "energy_rating_current" => 79,
                      "energy_rating_potential" => 80,
                      "environmental_impact_current" => 80,
                      "environmental_impact_potential" => 81,
                      "energy_consumption_current" => 109,
                      "energy_consumption_potential" => 104,
                      "co2_emissions_current" => 2.2,
                      "co2_emissions_potential" => 2.2,
                      "co2_emissions_current_per_floor_area" => 21,
                      "lighting_cost_current" => 86,
                      "lighting_cost_potential" => 57,
                      "heating_cost_current" => 350,
                      "heating_cost_potential" => 354,
                      "hot_water_cost_current" => 104,
                      "hot_water_cost_potential" => 104,
                      "suggested_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 1,
                          "improvement_type" => "E",
                          "improvement_details" => { "improvement_number" => 35 },
                          "typical_saving" => 25,
                          "indicative_cost" => 13,
                          "energy_performance_rating" => 80,
                          "environmental_impact_rating" => 81 },
                        { "sequence" => 2,
                          "improvement_category" => 3,
                          "improvement_type" => "N",
                          "improvement_details" => { "improvement_number" => 19 },
                          "typical_saving" => 27,
                          "indicative_cost" => "6,000",
                          "energy_performance_rating" => 81,
                          "environmental_impact_rating" => 83 },
                        { "sequence" => 3,
                          "improvement_category" => 3,
                          "improvement_type" => "U",
                          "improvement_details" => { "improvement_number" => 34 },
                          "typical_saving" => 222,
                          "indicative_cost" => "20,000",
                          "energy_performance_rating" => 90,
                          "environmental_impact_rating" => 91 }],
                      "data_type" => 2,
                      "schema_version" => "LIG-NI-17.0",
                      "built_form" => 1,
                      "living_area" => 25.14,
                      "orientation" => 1,
                      "conservatory_type" => 1,
                      "is_in_smoke_control_area" => "unknown",
                      "sap_opening_types" =>
                       [{ "name" => "front", "data_source" => 2, "type" => 2, "glazing_type" => 5, "u_value" => 1.5 },
                        { "name" => "front", "data_source" => 2, "type" => 4, "glazing_type" => 5, "solar_transmittance" => 0.72, "frame_factor" => 0.7, "u_value" => 1.5 },
                        { "name" => "back", "data_source" => 2, "type" => 4, "glazing_type" => 5, "solar_transmittance" => 0.72, "frame_factor" => 0.7, "u_value" => 1.5 }],
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "identifier" => "Main Dwelling",
                          "construction_year" => 2012,
                          "overshading" => 2,
                          "sap_openings" =>
                           [{ "name" => "front", "type" => "front", "location" => "Walls (1)", "orientation" => 0, "width" => 1.89, "height" => 1 },
                            { "name" => "front", "type" => "front", "location" => "Walls (1)", "orientation" => 1, "width" => 5.99, "height" => 1 },
                            { "name" => "back", "type" => "back", "location" => "Walls (1)", "orientation" => 5, "width" => 10.88, "height" => 1 }],
                          "sap_floor_dimensions" =>
                           [{ "storey" => 0, "floor_type" => 3, "total_floor_area" => 55.96, "storey_height" => 2.6, "heat_loss_area" => 0, "u_value" => 0 },
                            { "storey" => 1, "floor_type" => 3, "total_floor_area" => 51.93, "storey_height" => 2.4, "heat_loss_area" => 0, "u_value" => 0 }],
                          "sap_roofs" => [{ "name" => "Roof (1)", "description" => "300mm wool", "roof_type" => 2, "total_roof_area" => 55.96, "u_value" => 0.22 }],
                          "sap_walls" =>
                           [{ "name" => "Walls (1)", "description" => "traditional cavity ff", "wall_type" => 2, "total_wall_area" => 149.818, "u_value" => 0.3, "is_curtain_walling" => "false" }],
                          "sap_thermal_bridges" => { "thermal_bridge_code" => 4, "user_defined_y_value" => 0.08, "calculation_reference" => "2006 regulations" },
                          "thermal_mass_parameter" => 250 }],
                      "sap_ventilation" =>
                       { "open_fireplaces_count" => 1,
                         "open_flues_count" => 0,
                         "extract_fans_count" => 2,
                         "psv_count" => 0,
                         "flueless_gas_fires_count" => 0,
                         "pressure_test" => 1,
                         "air_permeability" => 4.56,
                         "sheltered_sides_count" => 2,
                         "ventilation_type" => 1 },
                      "sap_heating" =>
                       { "main_heating_details" =>
                          [{ "main_heating_number" => 1,
                             "main_heating_category" => 2,
                             "main_heating_fraction" => 1,
                             "main_heating_data_source" => 1,
                             "boiler_index_number" => 16_093,
                             "main_fuel_type" => 1,
                             "main_heating_control" => 2106,
                             "heat_emitter_type" => 1,
                             "main_heating_flue_type" => 2,
                             "is_flue_fan_present" => "true",
                             "is_central_heating_pump_in_heated_space" => "true",
                             "is_interlocked_system" => "true",
                             "has_delayed_start_thermostat" => "false",
                             "load_or_weather_compensation" => 1 }],
                         "secondary_heating_category" => 1,
                         "has_fixed_air_conditioning" => "false",
                         "water_heating_code" => 901,
                         "water_fuel_type" => 1,
                         "has_hot_water_cylinder" => "false",
                         "thermal_store" => 1,
                         "has_solar_panel" => "false" },
                      "sap_energy_source" =>
                       { "wind_turbines_count" => 0,
                         "wind_turbine_terrain_type" => 1,
                         "fixed_lighting_outlets_count" => 10,
                         "low_energy_fixed_lighting_outlets_count" => 5,
                         "low_energy_fixed_lighting_outlets_percentage" => 50,
                         "electricity_tariff" => 1 } }

      expect(use_case.execute(xml: sap,
                              schema_type: "SAP-Schema-NI-17.0",
                              assessment_id: "1234-1234-1234-1234-1234")).to eq expectation
    end
  end
end
