RSpec.describe "the parser and the SAP configuration" do
  let(:use_case) { UseCase::ParseXmlCertificate.new }

  context "when loading XML from RdSAP (SAP 16.3)" do
    let(:rdsap) { Samples.xml "SAP-Schema-16.3", "rdsap" }

    it "parses the document into the expected format" do
      expectation = { "calculation_software_name" => "NHER EPC Online",
                      "calculation_software_version" => 8.3,
                      "sap_version" => 9.91,
                      "bedf_revision_number" => 370,
                      "lzc_energy_sources" => [9],
                      "walls" =>
                       [{ "description" => "Cavity wall, as built, insulated (assumed)",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "roofs" =>
                       [{ "description" => "Pitched, 200 mm loft insulation",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "floors" =>
                       [{ "description" => "Suspended, no insulation (assumed)",
                          "energy_efficiency_rating" => 0,
                          "environmental_efficiency_rating" => 0 }],
                      "windows" =>
                       [{ "description" => "Fully double glazed", "energy_efficiency_rating" => 3, "environmental_efficiency_rating" => 3 }],
                      "main_heating" =>
                       [{ "description" => "Electric storage heaters",
                          "energy_efficiency_rating" => 3,
                          "environmental_efficiency_rating" => 1 }],
                      "main_heating_controls" =>
                       [{ "description" => "Manual charge control", "energy_efficiency_rating" => 2, "environmental_efficiency_rating" => 2 }],
                      "hot_water" =>
                       { "description" => "Electric immersion, off-peak",
                         "energy_efficiency_rating" => 3,
                         "environmental_efficiency_rating" => 1 },
                      "lighting" =>
                       { "description" => "Low energy lighting in 71% of fixed outlets",
                         "energy_efficiency_rating" => 5,
                         "environmental_efficiency_rating" => 5 },
                      "secondary_heating" =>
                       { "description" => "Room heaters, electric", "energy_efficiency_rating" => 0, "environmental_efficiency_rating" => 0 },
                      "has_hot_water_cylinder" => "true",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Semi-detached house",
                      "total_floor_area" => 70,
                      "has_fixed_air_conditioning" => "false",
                      "energy_rating_current" => 59,
                      "energy_rating_potential" => 84,
                      "environmental_impact_current" => 37,
                      "environmental_impact_potential" => 63,
                      "energy_consumption_current" => 473,
                      "energy_consumption_potential" => 247,
                      "co2_emissions_current" => 5.9,
                      "co2_emissions_current_per_floor_area" => 84,
                      "co2_emissions_potential" => 3.1,
                      "lighting_cost_current" => { "currency" => "GBP", "value" => 65 },
                      "lighting_cost_potential" => { "currency" => "GBP", "value" => 51 },
                      "heating_cost_current" => { "currency" => "GBP", "value" => 611 },
                      "heating_cost_potential" => { "currency" => "GBP", "value" => 471 },
                      "hot_water_cost_current" => { "currency" => "GBP", "value" => 226 },
                      "hot_water_cost_potential" => { "currency" => "GBP", "value" => 105 },
                      "energy_rating_average" => 60,
                      "suggested_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 5,
                          "improvement_type" => "W",
                          "improvement_details" => { "improvement_number" => 47 },
                          "typical_saving" => { "currency" => "GBP", "value" => 88 },
                          "indicative_cost" => "£800 - £1,200",
                          "energy_performance_rating" => 63,
                          "environmental_impact_rating" => 41 },
                        { "sequence" => 2,
                          "improvement_category" => 5,
                          "improvement_type" => "C",
                          "improvement_details" => { "improvement_number" => 2 },
                          "typical_saving" => { "currency" => "GBP", "value" => 35 },
                          "indicative_cost" => "£15 - £30",
                          "energy_performance_rating" => 65,
                          "environmental_impact_rating" => 43 },
                        { "sequence" => 3,
                          "improvement_category" => 5,
                          "improvement_type" => "E",
                          "improvement_details" => { "improvement_number" => 35 },
                          "typical_saving" => { "currency" => "GBP", "value" => 11 },
                          "indicative_cost" => "£10",
                          "energy_performance_rating" => 65,
                          "environmental_impact_rating" => 44 },
                        { "sequence" => 4,
                          "improvement_category" => 5,
                          "improvement_type" => "L",
                          "improvement_details" => { "improvement_number" => 25 },
                          "typical_saving" => { "currency" => "GBP", "value" => 100 },
                          "indicative_cost" => "£900 - £1,200",
                          "energy_performance_rating" => 69,
                          "environmental_impact_rating" => 47 },
                        { "sequence" => 5,
                          "improvement_category" => 5,
                          "improvement_type" => "N",
                          "improvement_details" => { "improvement_number" => 19 },
                          "typical_saving" => { "currency" => "GBP", "value" => 44 },
                          "indicative_cost" => "£4,000 - £6,000",
                          "energy_performance_rating" => 71,
                          "environmental_impact_rating" => 52 },
                        { "sequence" => 6,
                          "improvement_category" => 5,
                          "improvement_type" => "U",
                          "improvement_details" => { "improvement_number" => 34 },
                          "typical_saving" => { "currency" => "GBP", "value" => 261 },
                          "indicative_cost" => "£9,000 - £14,000",
                          "energy_performance_rating" => 83,
                          "environmental_impact_rating" => 62 },
                        { "sequence" => 7,
                          "improvement_category" => 5,
                          "improvement_type" => "V",
                          "improvement_details" => { "improvement_number" => 44 },
                          "typical_saving" => { "currency" => "GBP", "value" => 22 },
                          "indicative_cost" => "£1,500 - £4,000",
                          "energy_performance_rating" => 84,
                          "environmental_impact_rating" => 63 }],
                      "alternative_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 6,
                          "improvement_type" => "J2",
                          "improvement_details" => { "improvement_number" => 54 },
                          "typical_saving" => { "currency" => "GBP", "value" => 50 },
                          "energy_performance_rating" => 68,
                          "environmental_impact_rating" => 88 },
                        { "sequence" => 2,
                          "improvement_category" => 6,
                          "improvement_type" => "Z1",
                          "improvement_details" => { "improvement_number" => 51 },
                          "typical_saving" => { "currency" => "GBP", "value" => 178 },
                          "energy_performance_rating" => 75,
                          "environmental_impact_rating" => 76 },
                        { "sequence" => 3,
                          "improvement_category" => 6,
                          "improvement_type" => "Z3",
                          "improvement_details" => { "improvement_number" => 53 },
                          "typical_saving" => { "currency" => "GBP", "value" => 179 },
                          "energy_performance_rating" => 73,
                          "environmental_impact_rating" => 72 }],
                      "renewable_heat_incentive" => { "space_heating_existing_dwelling" => 7554, "water_heating" => 3424 },
                      "schema_version" => "LIG-16.1",
                      "property_type" => 0,
                      "built_form" => 2,
                      "multiple_glazed_proportion" => 100,
                      "multiple_glazing_type" => 1,
                      "extensions_count" => 0,
                      "glazed_area" => 1,
                      "habitable_room_count" => 3,
                      "measurement_type" => 1,
                      "mechanical_ventilation" => 0,
                      "open_fireplaces_count" => 0,
                      "solar_water_heating" => "N",
                      "conservatory_type" => 1,
                      "fixed_lighting_outlets_count" => 7,
                      "low_energy_fixed_lighting_outlets_count" => 5,
                      "door_count" => 2,
                      "insulated_door_count" => 0,
                      "percent_draughtproofed" => 100,
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "construction_age_band" => "H",
                          "wall_construction" => 4,
                          "wall_insulation_type" => 4,
                          "roof_construction" => 4,
                          "roof_insulation_location" => 2,
                          "roof_insulation_thickness" => "200mm",
                          "floor_heat_loss" => 7,
                          "wall_thickness" => 270,
                          "wall_thickness_measured" => "Y",
                          "sap_floor_dimensions" =>
                           [{ "floor" => 0,
                              "floor_construction" => 3,
                              "floor_insulation" => 1,
                              "heat_loss_perimeter" => 16.837,
                              "total_floor_area" => 35.159,
                              "room_height" => 2.3 },
                            { "floor" => 1, "heat_loss_perimeter" => 16.837, "total_floor_area" => 35.159, "room_height" => 2.3 }],
                          "identifier" => "Main Dwelling",
                          "wall_dry_lined" => "N" }],
                      "sap_heating" =>
                       { "secondary_heating_type" => 691,
                         "secondary_fuel_type" => 29,
                         "water_heating_code" => 903,
                         "water_heating_fuel" => 29,
                         "immersion_heating_type" => 1,
                         "cylinder_size" => 4,
                         "cylinder_insulation_type" => 2,
                         "cylinder_insulation_thickness" => 25,
                         "has_fixed_air_conditioning" => "false",
                         "main_heating_details" =>
                          [{ "main_heating_number" => 1,
                             "main_heating_fraction" => 1,
                             "main_heating_category" => 7,
                             "main_fuel_type" => 29,
                             "main_heating_control" => 2401,
                             "main_heating_data_source" => 2,
                             "sap_main_heating_code" => 401,
                             "has_fghrs" => "N",
                             "heat_emitter_type" => 0 }],
                         "wwhrs" =>
                          { "rooms_with_bath_and_or_shower" => 1,
                            "rooms_with_bath_and_mixer_shower" => 0,
                            "rooms_with_mixer_shower_no_bath" => 0 } },
                      "sap_energy_source" =>
                       { "wind_turbines_count" => 0,
                         "wind_turbines_terrain_type" => 2,
                         "meter_type" => 1,
                         "main_gas" => "N",
                         "photovoltaic_supply" => { "percent_roof_area" => 0 } },
                      "heated_room_count" => 3,
                      "low_energy_lighting" => 71,
                      "inspection_date" => "2014-12-05",
                      "report_type" => 2,
                      "completion_date" => "2014-12-06",
                      "registration_date" => "2014-12-06",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "tenure" => 2,
                      "transaction_type" => 8,
                      "seller_commission_report" => "Y",
                      "scheme_assessor_id" => 0,
                      "address_line_1" => "11, Some Close",
                      "address_line_2" => "Long Itchington",
                      "post_town" => "Town",
                      "postcode" => "AA1 1AA",
                      "uprn" => 0,
                      "region_code" => 6,
                      "country_code" => "EAW" }

      expect(use_case.execute(xml: rdsap,
                              schema_type: "SAP-Schema-16.3",
                              assessment_id: "4321-4321-4321-4321-4321")).to eq expectation
    end
  end

  context "when loading XML from SAP (SAP-Schema-16.3)" do
    let(:sap) { Samples.xml "SAP-Schema-16.3", "sap" }

    it "parses the document into the expected format" do
      expectation = { "sap_version" => 9.9,
                      "bedf_revision_number" => 333,
                      "calculation_software_name" => "SAP Calculator",
                      "calculation_software_version" => 3.59,
                      "inspection_date" => "2014-04-04",
                      "report_type" => 3,
                      "completion_date" => "2014-04-04",
                      "registration_date" => "2014-04-05",
                      "status" => "entered",
                      "language_code" => 1,
                      "restricted_access" => 0,
                      "transaction_type" => 6,
                      "seller_commission_report" => "N",
                      "property_type" => 0,
                      "scheme_assessor_id" => 0,
                      "address_line_1" => "17, Street Terrace",
                      "post_town" => "Town",
                      "postcode" => "AA1 1AA",
                      "uprn" => 0,
                      "region_code" => 3,
                      "country_code" => "EAW",
                      "assessment_date" => "2014-04-04",
                      "walls" =>
                       [{ "description" => "Average thermal transmittance 0.28 W/m²K",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "roofs" =>
                       [{ "description" => "Average thermal transmittance 0.12 W/m²K",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "floors" =>
                       [{ "description" => "Average thermal transmittance 0.17 W/m²K",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "windows" =>
                       { "description" => "High performance glazing", "energy_efficiency_rating" => 5, "environmental_efficiency_rating" => 5 },
                      "main_heating" =>
                       [{ "description" => "Boiler and radiators, mains gas",
                          "energy_efficiency_rating" => 4,
                          "environmental_efficiency_rating" => 4 }],
                      "main_heating_controls" =>
                       [{ "description" => "Time and temperature zone control",
                          "energy_efficiency_rating" => 5,
                          "environmental_efficiency_rating" => 5 }],
                      "secondary_heating" => { "description" => "None", "energy_efficiency_rating" => 0, "environmental_efficiency_rating" => 0 },
                      "hot_water" =>
                       { "description" => "From main system", "energy_efficiency_rating" => 4, "environmental_efficiency_rating" => 4 },
                      "lighting" =>
                       { "description" => "Low energy lighting in all fixed outlets",
                         "energy_efficiency_rating" => 5,
                         "environmental_efficiency_rating" => 5 },
                      "air_tightness" =>
                       { "description" => "Air permeability 3.9 m³/h.m² (assumed)",
                         "energy_efficiency_rating" => 4,
                         "environmental_efficiency_rating" => 4 },
                      "lzc_energy_sources" => [9],
                      "has_fixed_air_conditioning" => "false",
                      "has_hot_water_cylinder" => "true",
                      "has_heated_separate_conservatory" => "false",
                      "dwelling_type" => "Mid-terrace house",
                      "total_floor_area" => 96,
                      "energy_rating_current" => 83,
                      "energy_rating_potential" => 83,
                      "environmental_impact_current" => 85,
                      "energy_rating_average" => 60,
                      "environmental_impact_potential" => 85,
                      "energy_consumption_current" => 85,
                      "energy_consumption_potential" => 85,
                      "co2_emissions_current" => 1.5,
                      "co2_emissions_potential" => 1.5,
                      "co2_emissions_current_per_floor_area" => 16,
                      "lighting_cost_current" => 64,
                      "lighting_cost_potential" => 64,
                      "heating_cost_current" => 260,
                      "heating_cost_potential" => 260,
                      "hot_water_cost_current" => 93,
                      "hot_water_cost_potential" => 93,
                      "suggested_improvements" =>
                       [{ "sequence" => 1,
                          "improvement_category" => 3,
                          "improvement_type" => "N",
                          "improvement_details" => { "improvement_number" => 19 },
                          "typical_saving" => 37,
                          "indicative_cost" => "Â£4,000 - Â£6,000",
                          "energy_performance_rating" => 84,
                          "environmental_impact_rating" => 88 },
                        { "sequence" => 2,
                          "improvement_category" => 3,
                          "improvement_type" => "U",
                          "improvement_details" => { "improvement_number" => 34 },
                          "typical_saving" => 226,
                          "indicative_cost" => "Â£11,000 - Â£20,000",
                          "energy_performance_rating" => 94,
                          "environmental_impact_rating" => 96 }],
                      "renewable_heat_incentive" => { "rhi_new_dwelling" => { "space_heating" => 3127, "water_heating" => 2230 } },
                      "data_type" => 2,
                      "schema_version" => "LIG-16.0",
                      "built_form" => 4,
                      "living_area" => 20.15,
                      "orientation" => 7,
                      "conservatory_type" => 1,
                      "design_water_use" => 1,
                      "is_in_smoke_control_area" => "unknown",
                      "sap_opening_types" =>
                       [{ "name" => "Doors (1)", "data_source" => 3, "type" => 1, "glazing_type" => 1, "u_value" => 1.4 },
                        { "name" => "Doors (2)", "data_source" => 2, "type" => 1, "glazing_type" => 1, "u_value" => 1.5 },
                        { "name" => "Windows (1)",
                          "data_source" => 2,
                          "type" => 4,
                          "glazing_type" => 6,
                          "solar_transmittance" => 0.63,
                          "frame_factor" => 0.7,
                          "u_value" => 1.5 }],
                      "sap_building_parts" =>
                       [{ "building_part_number" => 1,
                          "identifier" => "Main Dwelling",
                          "construction_year" => 2013,
                          "overshading" => 2,
                          "sap_openings" =>
                           [{ "name" => 1, "type" => "Doors (2)", "location" => "Walls (2)", "orientation" => 7, "width" => 2.69, "height" => 2.1 },
                            { "name" => 2, "type" => "Windows (1)", "location" => "Walls (2)", "orientation" => 7, "width" => 0.46, "height" => 1.88 },
                            { "name" => 3, "type" => "Windows (1)", "location" => "Walls (2)", "orientation" => 3, "width" => 0.67, "height" => 0.9 },
                            { "name" => 4, "type" => "Windows (1)", "location" => "Walls (2)", "orientation" => 7, "width" => 0.46, "height" => 1.88 },
                            { "name" => 5, "type" => "Windows (1)", "location" => "Walls (2)", "orientation" => 3, "width" => 1.45, "height" => 1.35 },
                            { "name" => 6, "type" => "Windows (1)", "location" => "Walls (2)", "orientation" => 3, "width" => 1.45, "height" => 1.35 },
                            { "name" => 7, "type" => "Doors (1)", "location" => "Walls (3)", "orientation" => 0, "width" => 1.01, "height" => 2 },
                            { "name" => 8, "type" => "Doors (2)", "location" => "Walls (2)", "orientation" => 7, "width" => 1.74, "height" => 2.1 },
                            { "name" => 9, "type" => "Doors (2)", "location" => "Walls (2)", "orientation" => 3, "width" => 1.79, "height" => 2.1 },
                            { "name" => 10, "type" => "Doors (1)", "location" => "Walls (1)", "orientation" => 0, "width" => 1.01, "height" => 2.1 }],
                          "sap_floor_dimensions" =>
                           [{ "storey" => 0,
                              "floor_type" => 2,
                              "total_floor_area" => 11.72,
                              "storey_height" => 2.4,
                              "heat_loss_area" => 11.8,
                              "u_value" => 0.16,
                              "kappa_value" => 30 },
                            { "storey" => 1,
                              "floor_type" => 3,
                              "total_floor_area" => 41.95,
                              "storey_height" => 2.4,
                              "heat_loss_area" => 24.68,
                              "u_value" => 0.17,
                              "kappa_value" => 30 },
                            { "storey" => 2,
                              "floor_type" => 4,
                              "total_floor_area" => 41.95,
                              "storey_height" => 2.4,
                              "heat_loss_area" => 0,
                              "u_value" => 0,
                              "kappa_value" => 0 }],
                          "sap_roofs" =>
                           [{ "name" => "Roof (1)",
                              "description" => "Pitched roof insulation at ceiling level",
                              "roof_type" => 2,
                              "total_roof_area" => 41.96,
                              "u_value" => 0.11,
                              "kappa_value" => 8.75 },
                            { "name" => "Roof (2)",
                              "description" => "Flat roof - internal insulation",
                              "roof_type" => 2,
                              "total_roof_area" => 4.69,
                              "u_value" => 0.2,
                              "kappa_value" => 8.75 }],
                          "sap_walls" =>
                           [{ "name" => "Walls (1)",
                              "description" => "Masonry cavity wall",
                              "wall_type" => 2,
                              "total_wall_area" => 26.5,
                              "u_value" => 0.29,
                              "kappa_value" => 46.25,
                              "is_curtain_walling" => "false" },
                            { "name" => "Walls (2)",
                              "description" => "Timber frame wall",
                              "wall_type" => 2,
                              "total_wall_area" => 48,
                              "u_value" => 0.28,
                              "kappa_value" => 8.75,
                              "is_curtain_walling" => "false" },
                            { "name" => "Walls (3)",
                              "description" => "Insulated wall to garage",
                              "wall_type" => 3,
                              "total_wall_area" => 7.29,
                              "u_value" => 0.22,
                              "kappa_value" => 8.75,
                              "is_curtain_walling" => "false" },
                            { "name" => "Party wall (1)", "wall_type" => 4, "total_wall_area" => 48.6, "u_value" => 0, "kappa_value" => 17.5 }],
                          "sap_thermal_bridges" =>
                           { "thermal_bridge_code" => 5,
                             "thermal_bridges" =>
                              [{ "thermal_bridge_type" => 10, "length" => 9.8, "psi_value" => 0.06, "psi_value_source" => 2 },
                               { "thermal_bridge_type" => 19, "length" => 4.2, "psi_value" => 0.04, "psi_value_source" => 2 },
                               { "thermal_bridge_type" => 20, "length" => 2.6, "psi_value" => 0.28, "psi_value_source" => 2 },
                               { "thermal_bridge_type" => 22, "length" => 6, "psi_value" => 0.08, "psi_value_source" => 2 },
                               { "thermal_bridge_type" => 23, "length" => 33.6, "psi_value" => 0, "psi_value_source" => 2 },
                               { "thermal_bridge_type" => 4, "length" => 25.86, "psi_value" => 0.05, "psi_value_source" => 2 },
                               { "thermal_bridge_type" => 2, "length" => 12.73, "psi_value" => 0.3, "psi_value_source" => 2 },
                               { "thermal_bridge_type" => 3, "length" => 12.73, "psi_value" => 0.04, "psi_value_source" => 2 }] } }],
                      "sap_ventilation" =>
                       { "open_fireplaces_count" => 0,
                         "open_flues_count" => 0,
                         "extract_fans_count" => 3,
                         "psv_count" => 0,
                         "flueless_gas_fires_count" => 0,
                         "pressure_test" => 1,
                         "air_permeability" => 3.89,
                         "sheltered_sides_count" => 2,
                         "ventilation_type" => 1 },
                      "sap_heating" =>
                       { "main_heating_details" =>
                          [{ "main_heating_number" => 1,
                             "main_heating_category" => 2,
                             "main_heating_fraction" => 1,
                             "main_heating_data_source" => 1,
                             "boiler_index_number" => 16_179,
                             "burner_control" => 3,
                             "main_fuel_type" => 1,
                             "main_heating_control" => 2110,
                             "heat_emitter_type" => 1,
                             "main_heating_flue_type" => 2,
                             "is_flue_fan_present" => "true",
                             "is_central_heating_pump_in_heated_space" => "true",
                             "is_interlocked_system" => "true",
                             "has_delayed_start_thermostat" => "true",
                             "load_or_weather_compensation" => 2 }],
                         "secondary_heating_category" => 1,
                         "has_fixed_air_conditioning" => "false",
                         "water_heating_code" => 901,
                         "water_fuel_type" => 1,
                         "has_hot_water_cylinder" => "true",
                         "thermal_store" => 1,
                         "hot_water_store_size" => 180,
                         "hot_water_store_heat_loss_source" => 2,
                         "hot_water_store_heat_loss" => 1.63,
                         "is_primary_pipework_insulated" => "true",
                         "has_cylinder_thermostat" => "true",
                         "is_cylinder_in_heated_space" => "true",
                         "is_hot_water_separately_timed" => "true",
                         "has_solar_panel" => "false" },
                      "sap_energy_source" =>
                       { "wind_turbines_count" => 0,
                         "wind_turbine_terrain_type" => 1,
                         "fixed_lighting_outlets_count" => 16,
                         "low_energy_fixed_lighting_outlets_count" => 16,
                         "low_energy_fixed_lighting_outlets_percentage" => 100,
                         "electricity_tariff" => 1 } }

      expect(use_case.execute(xml: sap,
                              schema_type: "SAP-Schema-16.3",
                              assessment_id: "1234-1234-1234-1234-1234")).to eq expectation
    end
  end
end
