openapi: 3.1.0

info:
  title: Energy Performance of Buildings Data API
  description: Public API for EPB data integrations
  contact:
    name: MHCLG Digital helpdesk (prefix email subject with "EPB")
    email: mhclg.digital-services@communities.gov.uk
  version: 1.2.2

tags:
  - name: domestic
    description: Domestic Certificates API


paths:
  /domestic/search:
    get:
      description: Returns a list of domestic EPCs
      tags:
        - domestic

      parameters:
        - $ref: '#/components/parameters/Size'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Postcode'
        - $ref: '#/components/parameters/Local-authority'
        - $ref: '#/components/parameters/Constituency'
        - $ref: '#/components/parameters/Domestic-Energy-band'
        - $ref: '#/components/parameters/From-month'
        - $ref: '#/components/parameters/From-year'
        - $ref: '#/components/parameters/To-month'
        - $ref: '#/components/parameters/To-year'

      responses:
        '200':
          description: Successfully returned a list of domestic EPCs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AssessmentId'

        '400':
          $ref: '#/components/responses/400Error'
  /domestic/this-month:
      get:
        description: Returns a list of domestic EPCs published since the 1st day of the last month
        tags:
          - domestic

        parameters:
          - $ref: '#/components/parameters/Size'
          - $ref: '#/components/parameters/Page'
          - $ref: '#/components/parameters/Postcode'
          - $ref: '#/components/parameters/Local-authority'
          - $ref: '#/components/parameters/Constituency'
          - $ref: '#/components/parameters/Domestic-Energy-band'

        responses:
          '200':
            description: Successfully returned a list of domestic EPCs
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/AssessmentId'

          '400':
            $ref: '#/components/responses/400Error'
  /domestic/deltas:
    get:
      description: Returns a list of domestic EPCs removed from the publication since the 1st day of the last month
      tags:
        - domestic

      parameters:
        - $ref: '#/components/parameters/Size'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Postcode'
        - $ref: '#/components/parameters/Local-authority'
        - $ref: '#/components/parameters/Constituency'
        - $ref: '#/components/parameters/Domestic-Energy-band'

      responses:
        '200':
          description: Successfully returned a list of domestic EPCs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AssessmentId'
        '400':
          $ref: '#/components/responses/400Error'
  /domestic/certifcate/{assessmentId}:
    get:
      description: Returns an object all EPC data points
      tags:
        - domestic
      parameters:
        - in: path
          name: assessmentId
          required: true
          description: 'The ID of the assessment being requested, usually RRN'
          schema:
            $ref: '#/components/schemas/AssessmentId'
      responses:
         '200':
           description: JSON representation of an energy performance certificate
           content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Domestic-Certificate"
                examples:
                  jsonObject:
                    summary: A sample RdSAP
                    externalValue: "https://raw.githubusercontent.com/communitiesuk/epb-data-warehouse/refs/heads/main/spec/fixtures/json_export/rdsap.json"
  /domestic/recommendations/{assessmentId}:
    get:
      description: Returns the recommendations for a specific property
      tags:
        - domestic

      parameters:
        - name: assessmentId
          $ref:  '#/components/schemas/AssessmentId'

      responses:
        '200':
          description: Successfully returned a list of recommendations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recommendations'

        '400':
          $ref: '#/components/responses/400Error'


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Domestic-Certificate:
      type: object

    AssessmentId:
      type: string
      pattern: '^\d{4}-\d{4}-\d{4}-\d{4}-\d{4}$'
      example: '0000-0000-0000-0000-0000'

    Recommendation:
      type: object
      properties:
        rrr:
          $ref: '#/components/schemas/AssessmentId'
        improvement_item:
          type: integer
          description: Used to order the recommendations on the output EPC.
        improvement_summary_text:
          type: string
          description: A short description of the suggested improvement.
        improvement_descr_text:
          type: string
          description: Detailed description of the suggested improvement.
        improvement_id:
          type: integer
          description: Code number associated with the improvement measure.
        improvement_id_text:
          type: string
          description: The text associated with the improvement measure.
        INDICATIVE_COST:
          type: string
          example: '¬£800 - ¬£1,200'
          description: The indicative costs are the cost of installed recommendation measures, which are fixed no matter the type of house being assessed. These are displayed as a cost range on the Energy Performance Certificate as costs vary between individual suppliers.
    Recommendations:
      type: array
      items:
        $ref: '#/components/schemas/Recommendation'

  parameters:
    Size:
      name: limit
      in: query
      description: number of rows per page (max 5,000)
      schema:
        type: integer
    Page:
      name: page
      in: query
      description: page number of paginator
      schema:
        type: integer

    Postcode:
      name: postcode
      in: query
      description: An arbitrary postcode or prefix string of e.g. 'P', 'PR', 'PR8' or 'PR82EG'
      schema:
        type: string

    Local-authority:
      name: local-authority
      in: query
      description: Local authority (Adur)
      schema:
        type: string #One of supported parameter codes (./import/resources/local-authority-geo-lookup.csv)
    Constituency:
      name: constituency
      in: query
      description: parliamentary constituency (Aberavon)
      schema:
        type: string #One of supported parameter codes (.import/resources/constituency-geo-lookup.csv)

    Domestic-Energy-band:
      name: energy-band
      in: query
      description: >
        Bands and descriptions:

        - `a` - A rated (92+)

        - `b` - B rated (81-91)

        - `c` - C rated (69-80)

        - `d` - D rated (55-68)

        - `e` - E rated (39-54)

        - `f` - F rated (21-38)

        - `g` - G rated (1-20)


        Bands based on cost of energy [in kWh/year] multiplied by fuel costs. (£/m²/year where cost is derived from kWh).
      style: form
      schema:
        type: array
        items:
          type: string
          enum: [a, b, c, d, e, f, g]
    From-month:
      name: from-month
      in: query
      description: A numeric month identifier 1-12, to establish the start of a date range, where 1 is January and 12 is December. If no from-month parameter is supplied 1 (January) is assumed.
      schema:
        type: integer
        minimum: 1
        maximum: 12
    From-year:
      name: from-year
      in: query
      description: A numeric year identifier to establish the start of a date range between 2008 and the current year, e.g. 2015. If no year parameter is supplied 2008 is assumed.
      schema:
        type: integer
        minimum: 2012
    To-month:
      name: to-month
      in: query
      description: A numeric month identifier 1-12, to establish the end of a date range, where 1 is January and 12 is December. If no to-month parameter is supplied then 12 is assumed.
      schema:
        type: integer
        minimum: 1
        maximum: 12
    To-year:
      name: to-year
      in: query
      description: A numeric year identifier between 2008 and the current year, e.g. 2015. If no to-year parameter is supplied then the current year is assumed.
      schema:
        type: integer
        minimum: 2012



  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string